### ISSUE TITLE
Not working when using Nginx with proxy

### ISSUE THREAD

**Issue by ehayun** [phoenixframework/phoenix_live_view#108]
### Environment

* Elixir version (elixir -v): 1.8.1
* Phoenix version (mix deps): 1.4.2
* NodeJS version (node -v): v8.11.4
* NPM version (npm -v): 5.8.0
* Operating system: Ubuntu 18.10

### Actual behavior

When i am running using http://localhost:4000 everything is OK. When I am running using nginx with proxy It hangs

```
server {
    listen       80;
    server_name  myiex.home;

    location / {
        proxy_pass http://0.0.0.0:4000;
    }
}


``` 
### Expected behavior

should work the same

Note: regular Phoenix projects runs perfect with that approach

**Comment by lawik** [comment]
Could this simply be a matter of Nginx Websocket handling which requires some additional handling? As in: https://www.nginx.com/blog/websocket-nginx/

Since Live View uses Channels as far as I know and Channels generally use WebSockets you need to make sure WebSockets work. I know some additional Nginx configuration was needed last time I did WebSockets through it. I'd recommend looking at the above link and see if it helps.

**Comment by ehayun** [comment]
I will check that. Thanks

**Comment by Gazler** [comment]
https://github.com/phoenixframework/phoenix/issues/3165 - try the config in this issue
