### ISSUE TITLE
Radio buttons are incorrectly displaying form validation errors when they haven't been visited yet

### ISSUE THREAD

**Issue by alexslade** [phoenixframework/phoenix_live_view#1109]
### Environment

* Elixir version (elixir -v): 1.10.3
* Phoenix version (mix deps): 1.5.4
* Phoenix LiveView version (mix deps): 0.14.4
* NodeJS version (node -v): 14.4.0
* NPM version (npm -v): 6.14.5
* Operating system: MacOS Mojave 10.14.6 (18G6020)
* Browsers you attempted to reproduce this bug on (the more the merrier): Firefox, Chrome
* Does the problem persist after removing "assets/node_modules" and trying again? Yes

### Actual behavior

Short video - https://www.loom.com/share/6cd4c25f5a644020b00602393b6101ea
Example repo - https://github.com/alexslade/liveview-radio-bug-demo

In a form with radio button inputs, when I edit an unrelated field, then validation errors appear for the radio buttons. 

### Expected behavior

If I haven't focussed on the radio buttons yet, no validation error should appear for them. 

### Further investigation 
From my initial searching in phoenix_live_view.js it looks like radio buttons aren't considered to be one of the fields that can be focussed. So they aren't getting the same treatment as other fields which have their initial errors hidden until focus. 

I'd be keen to help with a PR for this, but it would be my first phoenix one and I'd appreciate some rough direction to get going. Am I correct in thinking that radio buttons can be considered as fields which can be focussed?

**Comment by josevalim** [comment]
HI @alexslade! Thanks for the detailed report.

If you look at `error_tag`, you can see that it says which input ID it uses to control when show the errors: https://github.com/alexslade/liveview-radio-bug-demo/blob/e28fa017fbd685072be996863301964350970f9d/lib/radio_web/views/error_helpers.ex#L15

The issue though is that for radio buttons we have multiple elements, each with individual IDs, so we probably need to revisit the whole approach. One possible option is to do this matching based on the input names instead of inputs IDs. But this would be a backwards incompatible change...

Alternatively we could also change LV to compare both name and ID... and then we change the generators to use `input_name` instead of `input_id`. @chrismccord would know better.

**Comment by alexslade** [comment]
@josevalim No worries, thanks for creating Elixir :) 

I did experiment with using a `fieldset` tag which might be an appropriate wrapper for radio buttons, and can have an ID. https://developer.mozilla.org/en-US/docs/Web/HTML/Element/fieldset 

When using the fieldset, the errors *are* hidden at first, but then never get shown on focus :) But I suspect that an approach using fieldset, alongside a small modification to the focus detection code, might be a small fix. 

Do you see any blockers to that approach?

**Comment by alexslade** [comment]
I've spiked one approach in #1112, and don't like it. 

I like the idea of using names instead of IDs, though I'll wait for Chris's thoughts before attempting to write a PR for it.

**Comment by josevalim** [comment]
Closing in favor of #1278.
