### ISSUE TITLE
Nested LiveView with Presence tracking in second causes bug

### ISSUE THREAD

**Issue by theMarinac** [phoenixframework/phoenix_live_view#1114]
### Environment

* Elixir version (elixir -v): 1.7 (OS: 1.10.4)
* Phoenix version (mix deps): 1.5.4
* Phoenix LiveView version (mix deps):  0.13.3 -  0.14.4 
* NodeJS version (node -v): v12.14.0
* NPM version (npm -v): 6.14.7
* Operating system: Ubuntu 18.04
* Browsers you attempted to reproduce this bug on (the more the merrier):  Ubuntu Firefox, Ubuntu Chromium, Ubuntu Chrome, Android Chrome, iPhone Safari (iOS 14.3 beta)
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Technically, no? (Can't use LiveView without "assets/node_modules")

### Actual behavior

When using Phoenix.Presence to track online users with nested LiveView (LiveView inside a LiveView) a weird bug occurs and the number of registered users caps at 2 after few users connect (in my test more than 4). Note that this does not happen when using only one LiveView (LiveView inside html.eex)

[Repo with app reproducing the bug](https://github.com/theMarinac/users_online)

### Expected behavior
Expected Presence track to accurately update current users and not cap at 2.

**Comment by josevalim** [comment]
Hi @theMarinac, there are a couple issues with your implementation right now. Can you please address them and let us know if the issue persists?

Specifically:

1. You should get the list of current users AFTER you subscribe, otherwise there is a race condition where a presence has been removed but you didn't receive the notification for it

2. You should only track and subscribe once you are connected

3. Do not rely on `map_size`. Instead, merge the maps properly and only then compute the size

In pseudo-code, you want this:

```elixir
  def mount(_assigns, _session, socket) do
    if connected?(socket) do
      topic = "oracle:neo"

      # Subscribe to the topic
      UsersOnlineWeb.Endpoint.subscribe(topic)

      # Track changes to the topic
      Presence.track(self(), topic, socket.id, %{})

      {:ok, assign(socket, :readers, Presence.list(topic) )}
    else
      {:ok, assign(socket, :readers, %{})}
    end
  end
```

And similarly, when receiving the diffs, apply them to the map instead of doing a size computation. Given you get the list after you subscribe, you can for example receive leaves that you no longer have and receive joins that you already have.

**Comment by theMarinac** [comment]
Oh, I didn't even think about race conditions ... 
I applied changes to the code that you suggested and the bug disappeared. I am much grateful :)
Closing the issue
