### ISSUE TITLE
LiveView waiting all components to render on screen

### ISSUE THREAD

**Issue by diegonogueira** [phoenixframework/phoenix_live_view#1143]
I have a dashboard_live with lots of charts components(line, pie, bar). 

dashboard.html.leex

```elixir
<%= live_component @socket, AppWeb.PieChartComponent, id: "chart1", data: ... %>
<%= live_component @socket, AppWeb.PieChartComponent, id: "chart2", data: ... %>
<%= live_component @socket, AppWeb.PieChartComponent, id: "chart3", data: ... %>
```

The problem is, if one component is slow, the others will waiting for the slow component to be rended..

I can simulate this using `:timer.sleep(3000)` on update of any component.
If I put logs inside the orders components, I have all components done, but the last one is freezing the others to be rended on screen..

thanks,
Diego

**Comment by josevalim** [comment]
Correct, and that's by design and expected. I want the majority of my components to be loaded immediately exactly because they are not doing heavy work.

If you want to load the data asynchronously, then you should do it yourself. For example, you can spawn a task that loads the data and then sends a message back to the LiveView once the data is loaded.
