### ISSUE TITLE
Hook not getting remounted after liveview reconnect

### ISSUE THREAD

**Issue by syfgkjasdkn** [phoenixframework/phoenix_live_view#1174]
### Environment

* Elixir version (elixir -v): Elixir 1.10.4
* Phoenix version (mix deps): 1.5.5
* Phoenix LiveView version (mix deps): 0.14.7
* NodeJS version (node -v): v14.13.0
* NPM version (npm -v): 6.14.8
* Operating system: mac
* Browsers you attempted to reproduce this bug on (the more the merrier): chrome, safari
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: yes

I have a setup where I have a parent liveview for the dashboard and then a separate liveview for each widget on the dashboard. I've noticed that when the parent liveview disconnects (and crashes?), phx-hooks defined on the dashboard (parent liveview) get `reconnected`, but the phx-hooks that are inside the child liveviews, get neither `reconnected` nor `mounted` again (only `destroyed` is called). I can prepare a repro if needed.

[Browser logs](https://gist.github.com/syfgkjasdkn/bd483a0f730b49c7e9b2e7d065e4d5a6)

**Comment by syfgkjasdkn** [comment]
Repro: https://github.com/syfgkjasdkn/liveview-reset

Steps to reproduce:

Open `http://localhost:4000/`, then put the laptop into sleep (suspend), then turn the laptop back on, the map widgets should be empty now.

**Comment by syfgkjasdkn** [comment]
`liveSocket.disconnect() -> liveSocket.connect()` seems to do some extra step since it recreates the child liveview hooks after ~500ms.

**Comment by jonatanklosko** [comment]
I managed to reproduce the issue using your repo, the most recent version of `PhoenixLiveView` and simulating the broken connection with `liveSocket.disconnect() -> liveSocket.connect()`. Thanks for the detailed description, hopefully I figured out a solution in #1277.

**Comment by chrismccord** [comment]
Thanks for taking this on @jonatanklosko! One important note is that a hook should only be created and trigger `mounted` if that DOM node is actually removed and re-added. Under the connection recovery case, if the DOM node is never removed, then `reconnected` should be invoked. Can you verify whether the reconnected scenario is accommodated by your PR? Thanks so much for helping out with this!

**Comment by jonatanklosko** [comment]
As far as I understand this, currently the behavior is as follows:

* the socket gets disconnected
* it calls `destroy` on all the child live views
* consequently this destroys al the children's hooks
* the socket reconnects
* child live views are re-created, but the hooks are not (the actual issue)

I assumed removing the hooks was intentional and the fix would be to make make sure they are mounted when the children re-join. From what you said it seems that the children's hooks shouldn't be destroyed in the first place (even though the views are), so that they can just reconnect. Is that correct?
