### ISSUE TITLE
Feature request: More control over the head of the document. Think live_title_tag for meta tags and such. 

### ISSUE THREAD

**Issue by joshchernoff** [phoenixframework/phoenix_live_view#1194]
I'm working in the context of the head of a given document trying to figure out the best way to update my Open Graph meta tag as I navigate via live_patch and live_redirect. 

As denoted in https://github.com/phoenixframework/phoenix_live_view/blob/fe01854e12e010e8c6bdb01225fc0ce6dcf07d37/guides/server/live-layouts.md#updating-the-html-document-title 

>Because the root layout from the Plug pipeline is rendered outside of LiveView, the contents cannot be dynamically changed.

This produces a challenge when trying to update things like 
```
  <meta name="description" content="Portland's Digital Curator">
  <meta name="author" content="Josh Chernoff <jchernoff@morphic.pro>">

  <meta property="og:title" content="<%= assigns[:page_title] || "Morphic.Pro, LLC" %>">
  <meta property="og:description" content="<%= assigns[:page_description] || "Morphic.Pro, LLC" %>">
```
via 
```
  def handle_params(
     ...
    {:noreply,
     socket
     |> assign(:post, post)
     |> assign(:page_title, page_title(socket.assigns.live_action, post.title))
     |> assign(:page_description, page_description(socket.assigns.live_action, post.excerpt))
    }
  end
```

The idea in short would provide a mechanism like live_title_tag but for other like fields in the head that would also need to dynamically update as we navigate.  

elixir form post: https://elixirforum.com/t/thoughts-about-how-to-update-open-graph-meta-tags-in-the-head-of-a-document-via-in-liveview/35112

my current flawed efforts:
https://github.com/MorphicPro/morphic.pro/pull/288/files

**Comment by josevalim** [comment]
Hi @joshchernoff! The big question is: why do you want to update your open graph meta tags? The meta tags are usually used by search engines and crawlers, and those won’t be using live navigation but the regular render, so there is no need to update them.

The only reason we support the title out of the box is because it has direct impact on the UI and browsers. In any case, if you still want to update them, you can always use the new events system + phoenix hooks to receive those events and update the meta tags accordingly. This is probably something we won’t support out of the box. Thanks!

**Comment by joshchernoff** [comment]
🤦‍♂️ I just got hung up on the fact I was not seeing it update I had not considered who was consuming the tag. Fair, sorry for you time.
