### ISSUE TITLE
Issue with passing in map parameters

### ISSUE THREAD

**Issue by seanking2919** [phoenixframework/phoenix_live_view#1261]
### Environment

* Elixir version 1.11.2
* Phoenix version 1.5.7
* Phoenix LiveView version 0.15.0
* NodeJS version 10.19.0
* NPM version 6.4.19
* Operating system: Linux Mint 20 Ulyana

### Actual behavior

It does not recognize map parameters passed in:

![Screenshot from 2020-12-08 23-18-52](https://user-images.githubusercontent.com/31253278/101592599-c5767e00-39ab-11eb-8e09-3e1b2bf6372c.png)

### Expected behavior

When I run a test with the render_click function like seen below:

```
{:ok, view, _disconnected_html} = live_isolated(conn, ExampleAppWeb.SuggestionForm, session: %{})
      captcha = Captcha.new()

      render_click(view, :refresh_captcha, %{captcha: captcha})
```
All the parameters should be passing like seen below:

![Screenshot from 2020-12-08 23-10-18](https://user-images.githubusercontent.com/31253278/101592463-88aa8700-39ab-11eb-98f8-2993903710bd.png)

**Comment by josevalim** [comment]
The error is coming from your application code. Parameters are always encoded as strings, because they come from the client, but your template is expecting the parameters to have atom keys. You should either work with string keys or use something that validates those keys and cast them into a Captcha in your LiveView, so you can use atom keys in your templates.
