### ISSUE TITLE
Cannot tests an event without an element

### ISSUE THREAD

**Issue by shadowRR** [phoenixframework/phoenix_live_view#1314]
### Environment

* Elixir version (elixir -v): 1.10.4-otp-23
* Phoenix version (mix deps): 1.5.4
* Phoenix LiveView version (mix deps): 0.14.4
* NodeJS version (node -v): v12.18.3
* NPM version (npm -v): 6.14.6
* Operating system: Windows 10

### Missing test feature ?

Hello !

I'm currently stuck in what i believe is a missing feature in liveview tests functions. Let's say that i have part of a livecomponent looking like this:

```
<button phx-click="preview" phx-target="<%= @myself %>">preview</button>
<%= if has_perm?(@current_role) do %>
  <button phx-click="start" phx-target="<%= @myself %>">start</button>
<% end %>
```

Now in the case the user does not have the proper permissions, the second `<button>` won't be rendered. But the `handle_event` related stays available, and if i understand correctly, a user could technically change the `phx-click` value of the first button still visible to `start` (assuming he/she would know the name of the event) and request access to that event (note that i have to test it directly in the livecomponent, because it's related to it). So i've implemented a system to handle properly permissions checks on any calls to `handle_event`, but i haven't found a way to ensure that it works. Since the element is never there (any change to the related current user permissions will automatically update the liveview), i can't seem to find a way to directly call on the event without providing the related element.

Guessing i am missing something obvious ?

**Comment by josevalim** [comment]
All helpers, such as render_click, has a variant where you pass the event name (as an atom) and parameters (as a map), so without looking at the the element on the page. More info in the docs: https://hexdocs.pm/phoenix_live_view/Phoenix.LiveViewTest.html#module-testing-events

Btw, please use the ElixirForum or similar for questions next time, as that's where people usually look first so an answer there can prove helpful to others.

**Comment by shadowRR** [comment]
@josevalim Thanks for your reply, i'll try to use the forum next time. 

I've seen the variant you're pointing to, but they seem to only be able to receive the liveview, which ends up sending the event to it, instead of the livecomponent where my event handler lives. So that doesn't work. I can't seem to find a way to send it to the right target.

**Comment by josevalim** [comment]
Ah, I missed a key point in your description. You are correct. I believe this functionality is missing today.

**Comment by shadowRR** [comment]
Copy that ! I wasn't that clear, at least no enough on my original post, easy to miss what i meant, sorry about that.

I'll assume there's no current way to do it manually ? If that's the case, what are we missing in order to support such case scenario ?

**Comment by josevalim** [comment]
@shadowRR we need to introduce a function, such as `component()` or similar, that finds a component. So not possible today, yeah.

**Comment by josevalim** [comment]
One idea to implement this is to have a dummy LiveView which simply renders the component that we give as argument. This could work as a mechanism to test LiveComponent in the same way we test LiveView via live_isolated.

**Comment by josevalim** [comment]
So I thoughts about this issue and we could support a `view |> component(...)` that allows us to narrow the operation to a component. The question is: what is the argument of `component`? Passing the `cid` is not a good idea because we don't have it on the client, ti is an implementation detail. We could either pass a dom selector (which we expect to point to a component root) or we pass a `{module, id}` and look it up on the LiveView. I think the former is simpler. Implementation-wise, I would simply change the `%View{}` struct to have a `selector` attribute or similar. If the selector exist, we would scope the events to said selector's data-phx-component.

**Comment by josevalim** [comment]
There is another option which is to allow `live_isolated` to receive components and automatically wrap them in a LiveView. The `%View{}` struct returned would have a `.cid` annotation so all events point directly to said component. The upside is that this allows testing of components in isolation. The downside is that folks would need a separate testing for this kind of assertion (which is inconsistent since you can dispatch events to live views directly).
