### ISSUE TITLE
phx-capture-click triggers the LiveView event on clicking the browser scrollbar

### ISSUE THREAD

**Issue by nicolasblanco** [phoenixframework/phoenix_live_view#1336]
### Environment

* Elixir version (elixir -v): 1.11.3
* Phoenix version (mix deps): 1.5.7
* Phoenix LiveView version (mix deps): 0.15.4
* NodeJS version (node -v): v15.6.0
* NPM version (npm -v): 7.4.0
* Operating system: OS X
* Browsers you attempted to reproduce this bug on (the more the merrier): Chrome/Safari/Firefox
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Actual behavior

Hello folks !

I have an issue with the Modal component that is included in the Phoenix generators.

This modal HTML has this Phoenix LiveView attribute:
https://github.com/phoenixframework/phoenix/blob/master/priv/templates/phx.gen.live/modal_component.ex#L8

```
phx-capture-click="close"
```

This code makes that clicking *outside* the modal closes the Modal.

The issue is that clicking *directly* on the browser scrollbar also triggers the click event and because of that it's not possible for the user to use the scrollbar when a Modal component is displayed (because it just closes the modal).

### Expected behavior

I don't know if that's the expected behaviour (maybe), a bug or if there could be a workaround.

If it's normal to trigger the event even when the scrollbar is clicked, there should be a way to disallow this behaviour probably.

**Comment by nicolasblanco** [comment]
![crud](https://user-images.githubusercontent.com/12682/108203579-63fd2900-712b-11eb-92e5-51be49f11576.gif)

**Comment by chrismccord** [comment]
Clicking on scrollbars appears to be a difficult thing to detect and relies on brittle/specific screen size and scroll bar size estimates to try to address. This isn't any particular we are doing on our side, so my best advice is if you have modal content below the fold is to forgo the close event on capture click and rely instead of the user click the X icon. As a workaround you may try to register a click event listener on window before you instantiate LiveView, and attempt to calculate whether the scrollbar was click based on how far the x coordinate is to the screen width and stop propagation if the click was within x pixels of the right margin, but it's not something we'll try do ourselves in LV. Thanks!
