### ISSUE TITLE
component event sent to another component rendered by another view

### ISSUE THREAD

**Issue by garthk** [phoenixframework/phoenix_live_view#1338]
`ImagesComponent` is a stateful `LiveComponent` that can render images. Simplified, it's:

```elixir
defmodule ImagesComponent do
  use MyAppWeb, :live_component

  def render(assigns) do
    ~L"""
    <div>
      <%= for {thumbnail, index} <- Enum.with_index(@thumbnails) do %>
        <%= img_tag(thumbnail_url(thumbnail, @socket),
            phx_click: "select_thumbnail",
            phx_value_figure: index) %>
      <% end %>
    </div>
    """
  end
end
```

(I've taken out the stateful bit: it defines `handle_event/3` to toggle whether or not to show _all_ the thumbnails.)

The `img` above doesn't have a `phx_target`. Nor does the call to `live_component/3` that led to `ImagesComponent`. So, the event should go to the view `ThisView` that called `live_component/3` to render it. In dev, that's true every time. In prod, that's true _almost_ every time.

Sometimes, the event goes to another component rendered by another view open in another tab.

I can't figure out how, or reproduce it, but some of our users' `OtherView` processes started crashing with an `UndefinedFunctionError` in `OtherComponent` when I took out what I was sure was unused code: an `OtherComponent.handle_event/3` which matched on the event `"select_thumbnail"`.

Any suggestions?

### Environment

* Elixir version: Elixir 1.11.2 (compiled with Erlang/OTP 23)
* Phoenix version: phoenix 1.5.7 (Hex package) (mix) locked at 1.5.7 (phoenix) 774cd644
* Phoenix LiveView version: phoenix_live_view 0.15.3 (Hex package) (mix) locked at 0.15.3 (phoenix_live_view) cabcfb67
* NodeJS version: v12.19.0
* NPM version (npm -v): 6.14.8
* Operating system: macOS 10.15.7 (19H524)
* Browsers you attempted to reproduce this bug on: expensive to dig up; can we solve it anyway?
* Does the problem persist after removing "assets/node_modules" and trying again? yes

### Actual behavior

`handle_event/3` invoked in `OtherComponent`, crashing the `OtherView` process that rendered it, despite neither being in any way involved in rendering the only `ImagesComponent` that could send such an event.

### Expected behavior

`handle_event/3` invoked only in `ThisView` as expected.

**Comment by chrismccord** [comment]
> Sometimes, the event goes to another component rendered by another view open in another tab.

This wouldn't be possible since each tab is its own websocket connection. Without actual reproduction it's really impossible to say what could be going on. I would try to rule out duplicate DOM ids – `liveSocket.enableDebug()` will log if it fines some. If you're able to provide more information, please let us know. Thanks!

**Comment by garthk** [comment]
Yeah, I hear you, it's impossible. Y'know, except somehow those messages are getting to the wrong PID. They should be in separate Phoenix channels, no?

**Comment by chrismccord** [comment]
Each tab will be an isolated websocket connection with isolated channels per LV. The only way for one message to make it from the client to another tab is for the LV/component to receive the handle_event and do a send/broadcast to another pid. On our side `handle_event` is always client => server pid and it would be impossible as written for it to happen differently. It's possible we have a bug on the client where we are targeting the component instead of the LV, but it wouldn't be the case where we'd be sending the event across processes.
