### ISSUE TITLE
Add non_rendering_assigns

### ISSUE THREAD

**Issue by josevalim** [phoenixframework/phoenix_live_view#1386]
We are working on an app that needs to keep a bunch of `@data` and, for rendering, we convert this data into a `@data_view`. The thing is that we should never access `@data` in our templates nor does it need to be take into account for change tracking. Currently, LiveView does not give us a place to "hide" this assign. I can think of two options:

1. Add a non_rendering_assigns option with assigns that are discarded before from rendering and are not considered in changed

2. Store them in socket.private (this can be tricky because someone may still decide to access them in private and that will bypass change tracking)

**Comment by benwilson512** [comment]
I vote for #2. There are already plenty of other mechanisms to get state into the UI that isn't change tracked properly (`DateTime.utc_now()` comes to mind as an easy pitfall) so I think the rule already needs to clearly be "use assigns for rendered values". A formal place like `private` to store socket state that isn't change tracked fits with existing patterns.

**Comment by mveytsman** [comment]
I also like #2.

I think this should mean exposing an API like `put_private`/`get_private`. We can also give a loud warning or error if `get_private` is called from within a `render` call.

**Comment by johns10** [comment]
I think I also like 2.  

When I started my live view project, I had envisioned my entire application being presented to the user on a single page with a bunch of nested forms.  In order to accomplish that, I did something similar to what you've described above @josevalim. 

Basically I would load the data into the assigns from the backend into a `:data` assigns.  Then I built a little query engine that would build preloaded objects from the loaded data.  Then on a subscription update, it would update the `:data` and rerun the `prepare_x` function, and assign the result.

Having a socket.private would give me a place to store that data without fiddling with change tracking.

**Comment by wanton7** [comment]
Related Elixir forum thread https://elixirforum.com/t/phoenix-blog-post-failing-big-with-elixir-and-liveview-a-post-mortem/40236/7

**Comment by josevalim** [comment]
Closing this as private (option 2) is already available today.

**Comment by Nicd** [comment]
Looks like LiveView is using `socket.private` itself for things like temporary assigns and lifecycle things. How can a user be sure that their usage doesn't conflict with LV? Using `socket.private` has no API and is not documented in LV docs.
