### ISSUE TITLE
GenServer call :consume_done when process is no longer alive

### ISSUE THREAD

**Issue by speeddragon** [phoenixframework/phoenix_live_view#1394]
### Environment

* Elixir version (elixir -v): 1.10.4
* Phoenix version (mix deps): 1.5.8
* Phoenix LiveView version (mix deps): 0.15.4
* NodeJS version (node -v): v14.4.0
* NPM version (npm -v): 6.14.4
* Operating system: Ubuntu 20.04.1 LTS 
* Browsers you attempted to reproduce this bug on (the more the merrier): -
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: -

### Actual behavior

I have a webpage where people upload photos using live view upload. I've set up Sentry where anything that raises an exception is sent and since I move from some custom upload plugin to Phoenix Live View plugin I've been seen (a few of) these crashes. I've not been able to replicate this myself, but for some reason when the upload is completed and it's ready to communicate the process is no longer alive.

```
Sentry.CrashError: ** (exit) exited in: GenServer.call(#PID<0.12474.2>, :consume_done, :infinity)
    ** (EXIT) no process: the process is not alive or there's no process currently associated with the given name, possibly because its application isn't started
  File "lib/gen_server.ex", line 1023, in GenServer.call/3
  File "lib/phoenix_live_view/upload_channel.ex", line 17, in Phoenix.LiveView.UploadChannel.consume/3
  File "lib/enum.ex", line 1396, in Enum."-map/2-lists^map/1-0-"/2
  File "lib/phoenix_live_view/upload.ex", line 234, in Phoenix.LiveView.Upload.consume_uploaded_entry/3
  File "lib/myapp_web/live/item/show.ex", line 153, in MyAppWeb.ItemLive.Show.handle_progress/3
  File "lib/phoenix_live_view/channel.ex", line 144, in anonymous fn/4 in Phoenix.LiveView.Channel.handle_info/2
  File "lib/phoenix_live_view/channel.ex", line 995, in Phoenix.LiveView.Channel.write_socket/4
  File "lib/phoenix_live_view/channel.ex", line 137, in Phoenix.LiveView.Channel.handle_info/2
  ```

### Expected behavior

No error.

I know that this isn't much information to replicate the issue, this might be some kind of race condition. But I want to put this if to check if anyone might have an idea what it could be.

**Comment by iwarshak** [comment]
@speeddragon I am having a nearly identical issue & am trying to debug it. Did you find out how to duplicate it?

**Comment by iwarshak** [comment]
@speeddragon are you consuming the file in `handle_progress`? also, is your `live_file_input` inside of a component? (for me the answer to both is 'yes')

for me, I see a PID start
```
May 10 11:56:19 16:56:15.705 mfa=Phoenix.Logger.channel_log/3 pid=<0.7644.52> [info] JOINED lvu:0 in 27ms 
```

then as soon as the upload is complete and I try to consume it, I get an error saying that the above process is gone, but I see no logs about *why* it's gone

```
May 10 11:57:34 16:57:31.494 mfa=:gen_server.error_info/7 pid=<0.4081.52> [error] GenServer #PID<0.4081.52> terminating 
info May 10 11:57:34 ** (stop) exited in: GenServer.call(#PID<0.7644.52>, :consume_start, :infinity) 
info May 10 11:57:34     ** (EXIT) no process: the process is not alive or there's no process currently associated with the given name, possibly because its application isn't started 
```

**Comment by speeddragon** [comment]
```
|> allow_upload(:dropbox,
           accept: ~w(.jpg .jpeg .png),
           max_entries: 12,
           max_file_size: 20_000_000,
           auto_upload: true,
           progress: &handle_progress/3
         )}
```

```
defp handle_progress(:dropbox, entry, socket) do
    if entry.done? do
      picture =
        consume_uploaded_entry(socket, entry, fn %{path: path} ->
          CloudImages.upload(...)
        end)

      {:noreply, assign(socket, :uploaded_files, [picture] ++ uploaded_files)}
    else
      {:noreply, socket}
    end
  end
```

`live_file_input` isn't inside a Component, is a render file (`show.html.leex`)

This might be a race condition bug.

**Comment by iwarshak** [comment]
👍 Your code looks nearly identical to mine. Not sure what the problem can be, as I see no meaningful errors.

**Comment by mcrumm** [comment]
Okay, I _may_ have an inkling as to what's happening here, and if I am correct then it's a bug. We set a timeout with each received chunk. If we don't receive a chunk within the timeout (default `10s`) we close the channel normally.

The chunk timer is removed _after_ the entry has been consumed, and I believe therein lies the problem. If your callback to consume the entry exceeds the chunk timeout, then we end up closing the upload channel in the meantime.

**Comment by iwarshak** [comment]
@mcrumm do you mean my `consume_uploaded_entry` callback taking more than 10s? because my callback doesn't even get a chance to run...

**Comment by mcrumm** [comment]
@iwarshak Indeed, it's harder to explain why the pid would not be alive to receive `:consume_start` unless the upload was cancelled 🤔

**Comment by iwarshak** [comment]
@speeddragon with lots of help from @mcrumm, I discovered what was happening in my case was (most likely):

- progress events were getting fired correctly from the browser
- the events were not responded to quickly enough (not 100% sure why as of yet)
- the JS would see that a push message failed to get a response, so it reloaded the page

You can emulate this by adding a `:timer.sleep(5000)` in your progress handler, and uploading a decently sized attachment

**Comment by mcrumm** [comment]
Quick update: the chunk timer is **not** the culprit.  However there are several things that could cause the upload channel process to go away:

1. Client-side timeout to the progress reply (i.e. you took longer than 30s to consume the file)
2. Client-side cancels the upload while you are consuming it
3. Client-side disconnect

Upon further discussion we created #1454 to track consuming uploads asynchronously because, no matter what we do for auto-uploads, you will always be at the mercy of a client-side reply timeout if you synchronously consume the file.  

@speeddragon For the time being the solution is to `File.cp!` the tmp file to another location and then spawn a separate process to do the work you're currently doing in the `consume_uploaded_entry` callback.

@iwarshak As we discussed earlier, `:timer.sleep/1` test is a red herring, because you are slowing down the response to each progress event, which will necessarily cause the upload channel to finish processing long before the progress events are handled, leading to a client-side reply timeout.

**Comment by iwarshak** [comment]
@mcrumm yep - I only pointed out the `timer.sleep` because that emulates what was *really* happening in production, which was: my LiveView was not responding to progress events fast enough.

**Comment by iwarshak** [comment]
Ok - I am fairly certain I figured out what the root of my issue was, and it was exactly what @mcrumm mentioned in his comment to @speeddragon above. My code looked like

```
if entry.done? do
  consume_uploaded_entry(socket, entry, fn(meta = %{path: path}) ->
    GenServer.cast(self(), {:process_file, %{path: path}})
   end)
 else
  socket
end

```

My upload auto-starts, and my form has text inputs on it. *Some* JS event was taking longer than 30 seconds to get a response back and causing the whole form to reload. I was calling `cast` so that it would be handled asyncronously *after* all the progress messages happened, but I still had user's uploads failing.

It just dawned on me that the users whose uploads failed had pretty big uploads, and `process_file` can take a while. What I am nearly positive is happening is:

- file uploads fine
- LV starts processing it in `process_file`
- user types in more inputs into the form while it's processing and it's *those* events that time out

I was so tunnel visioned on the first half of the sequence, that I completely neglected the second half.

What I plan on doing instead is:

```
if entry.done? do
  consume_uploaded_entry(socket, entry, fn(meta = %{path: path}) ->
    Task.async(fn() ->
       ... process file...
       {:process_file_result, result}
    end)
else
  socket
end
```

and 

```
def handle_info({_ref, {:process_file_result, res}}, socket) do
 ...
end
```

Many thanks to @mcrumm and @chrismccord for patiently helping me through this issue.

**Comment by enkr1** [comment]
Does anyone have a better example? I am kinda lost...

**Comment by ZombieHarvester** [comment]
I'm having the same issue from time to time. 

Can someone pls explain the use case for the `{:postpone, _}`? 

The documentation is vague: `return {:postpone, my_result} to collect results, but postpone the file consumption to be performed later.` and it still supposed to return some kind of result?
