### ISSUE TITLE
Proposal: Include more debugging information in development mode for views and components

### ISSUE THREAD

**Issue by hubertlepicki** [phoenixframework/phoenix_live_view#1444]
I stumbled upon this tweet from @arathunku a while ago and it's indeed super handy.

https://twitter.com/arathunku/status/1387851415381553157/photo/1

It's super handy to the point of me actually thinking this should be default. And maybe not in a HTML comment but added as liveview / component wrapper attribute by default.

The reason is that often I want to inspect what is on LiveView's socket/assigns and this is a good way to identify a process - by PID, and often better / more flexible than just printing out debugging info or hooking into telemetry events to capture what's going on.

It could also open the possibility of building something like React Developer Tools (https://chrome.google.com/webstore/detail/react-developer-tools/fmkadmapgofadopljbjfkapdkoienihi) that would be a Chrome/Firefox extension that could overlay the LiveView components on the page and allow easy inspecting of their state in visual way.

An alternative approach suggestion would be welcome, maybe I am simply missing a good way to inspect the state of particular components.

**Comment by josevalim** [comment]
I think this is relatively easy to add to your LiveView layout, so that's the route we recommended going. I am not sure if this is something it is generally safe or recommended for us to do by default. I can't think of something that could go wrong at the moment but I can see people not being pleased with this information being available by default in prod, for example.

**Comment by hubertlepicki** [comment]
Alright.

**Comment by arathunku** [comment]
Thanks for mentioning me @hubertlepicki, I'd have missed it otherwise!!! 

My solution is simple but doesn't cover all cases - mainly, stateful live components with their own processes and pids. It of course depends on your liveview structure so my solutions work only "most of the time".

I actually wonder what would be non-instrusive way of introducing additional debug info into layouts without having to change them so that we could easily map LiveView processes to their parts of the page. Maybe something like custom `.leex` compiler would be needed that would wrap everything and add PID, or just before returning an update via websocket, add PID to response and handle it on client side... no idea. Having PID would indeed be super useful in building dev tools like React, that would be amazing.

**Comment by hubertlepicki** [comment]
Well, it is a proposal and afaik proposals are allowed... I think.

Either way I would love to have *something* that allows me to go through the components on the page and see their states, and even better, the history of state / changes as things are happening. React Dev Tools is amazing in doing just that for React.

Currently I find myself in a world where I have to mix in logger messages, outputting the structs to HTML and getting info from pids and it really could be better and probably should.

**Comment by jakespracher** [comment]
Dissatisfied with the LiveView debugging experience, I found the above tips and then this thread. Is there a discussion on the forum we can link to here?

While enabling this by default in prod isn't sensible, exposing it by some means other than adding a bunch of extra code (like below) would definitely be a productivity win.

https://arathunku.com/b/2021/debug-few-things-we-can-do-with-liveview-pid/
