### ISSUE TITLE
Callback for errors

### ISSUE THREAD

**Issue by spinettaro** [phoenixframework/phoenix_live_view#1446]
Hi,

it would be nice to have a callback function to handle any error may happen on the LiveView page. 
It should work like the Plug.ErrorHandler for Phoenix, then just a common callback to handle any error. 

https://hexdocs.pm/plug/Plug.ErrorHandler.html 

Cheers

**Comment by josevalim** [comment]
Hi 👋 !

LiveView is a very different model though. Given it is process-based, if your need is monitoring, then all errors from processes are automatically logged. In case of the client, errors automatically trigger the client to retry or to request the page. If you want anything more specific, then you wrap the specific functionality in your code. If that's not enough, please provide a more complete example of what is missing, otherwise the errorhandler approach simply doesn't map here.
