### ISSUE TITLE
handle_params/3 hook not invoked with default implementation

### ISSUE THREAD

**Issue by dmorneau** [phoenixframework/phoenix_live_view#1563]
### Environment

* Elixir version (elixir -v): Elixir 1.12.2 (compiled with Erlang/OTP 24)
* Phoenix version (mix deps): phoenix 1.5.10
* Phoenix LiveView version (mix deps): phoenix_live_view 0.16.0

### Actual behavior

When attaching a hook for handle_params/3 using attach_hook/4, the hook is only invoked if the LiveView implements a handle_params/3 handler.

### Expected behavior

I would hope for the hook to be invoked no matter if the LiveView implements handle_params/3 or not, or failing that a mention of the limitation in the documentation.

The practical use case for us is storing `uri` into an assign, to highlight the active tab when the user navigates between views. Thank you!

**Comment by josevalim** [comment]
I believe the issue is in those two lines:

https://github.com/phoenixframework/phoenix_live_view/blob/3d1eb6752399060eebdaa7112f959ee81e7d630d/lib/phoenix_live_view/static.ex#L279

https://github.com/phoenixframework/phoenix_live_view/blob/master/lib/phoenix_live_view/channel.ex#L378

I think we need to update them to also check if there are no lifecycle hooks. There is already a function that is meant to encapsulate this: https://github.com/phoenixframework/phoenix_live_view/blob/3d1eb6752399060eebdaa7112f959ee81e7d630d/lib/phoenix_live_view/static.ex#L292 - i would make it more generic to check both the view and the presence of life-cycle hooks, move it to the Utils module, and reuse it throughout.

**Comment by josevalim** [comment]
There is a question though about what happens if someone registers a hook for handle_params and the view is not at the root. If you simply change the code above, it will now start raising, but it will raise when LiveView calls `handle_params`, which may be confusing. If we want to keep this behaviour, then we should probably raise early on.
