### ISSUE TITLE
HTTP logs LiveView.Plug without LV module 

### ISSUE THREAD

**Issue by chrismccord** [phoenixframework/phoenix_live_view#1591]
We need to at least provide the liveview module so folks know what is being mounted   I thought we did this previously so may be a regression

**Comment by josevalim** [comment]
If I have to guess, the logging works for live views without action, because we use the LiveView as action. For LiveViews with action, then the action is the actual action, so we lose the LiveView information. I guess one solution is to implement `init/1`+`call/2` in the actual LiveView module and then we call it instead with the action (and it just delegates to the plug). This way the logging is correct.

**Comment by josevalim** [comment]
Closed by #1939.
