### ISSUE TITLE
Provide a unified mechanism to message the parent/child

### ISSUE THREAD

**Issue by josevalim** [phoenixframework/phoenix_live_view#1597]
Today, there is no unified mechanism for a component to talk to the parent where the parent may be a LiveView or a LiveComponent.

**Comment by robacourt** [comment]
We've seen the need for unified messaging too, to allow us to break down large LiveViews into smaller components.

Our solution has been to add a `send_info/2` function to LiveViews and LiveComponents which sends to `handle_info/2` in either a LiveView or a LiveComponent. This is our library to implement this: https://github.com/Dyad-AI/live_message

We were wondering if this was in line with the current thinking about what the interface should be for unified messaging, so we don't have to migrate too much when it becomes part of the framework.

Feedback for our solution has been positive so far, one piece of constructive criticism was that using `handle_info/2` in LiveComponents gives the impression that the LiveComponent is a GenServer so should work with things like PubSub. With a bit more code it could indeed work with PubSub which would be nice, allowing LiveComponents to subscribe directly, but the idea that this may cause confusion still stands. Perhaps `handle_message/2` for both LiveViews and LiveComponents and a `send_message/2` function would cause less confusion, but if you did then implement it for PubSub this would mean PubSub would no longer receive messages on `handle_info/2` which may not be desirable.

Any feedback would be appreciated. Many thanks.

**Comment by chrismccord** [comment]
I am not yes sure if an abstraction around this is necessary. I keep being well served by having the parent tell the child how they want to be notified via a function.

parent is LV

```heex
<.live_component
  module={...}
  on_complete={fn result -> send(self(), {:complete, result}) end}
>
```

parent is LC
```heex
<.live_component
  module={...}
  on_complete={&send_update(__MODULE__, id: @id, action: :complete, result: &1)}
>
```

And the child just calls the function. What I like about this is the contract then *stays on the parent*, so they decide what message they will receive and show, which means you don't need to go digging. I think the only thing I would change is `send_update` to yourself is a little verbose, so we could maybe introduce:

```heex
<.live_component
  module={...}
  on_complete={&send_update(@myself, action: :complete, result: &1)}
>
```

Thoughts?

**Comment by robacourt** [comment]
Yes, I like that solution, thanks Chris! I like the idea of the more concise `send_update` function too.

One thing our solution addresses that this does not is the coupling between message receiving and component initialisation. To receive messages in a LiveComponent you have to do something like:

```elixir
def update(%{message: :clear_items}, socket) do
  # handle message
  {:ok, socket |> clear_items() }
end

def update(assigns, socket) do
  # Initialise state
  {:ok, socket}
end
```

Sure they're in two different function heads, but it's not as nicely separated as if you had a `handle_info/2` as well as the `update/2`. Also with `update/2` you're passing it `assigns` which suggests it's the state for the component, not a message. Sure you can get it to work (as above) but it feels a bit hacky.

For our solution we're doing that hack in the library so the user (developer) sees messages arrive in `handle_info/2` for the LiveComponent.

Thinking further ahead, it would be nice if LiveComponents could subscribe to PubSub, would you want that to go to `update/2` too? It would seem nicer if the messages could arrive in `handle_info/2` for the LiveComponent. Obviously behind the scenes the LiveView process would receive the message, pattern match that it's for a LiveComponent and forward it on using `send_update`, but that should be transparent to the user (developer). 

If `handle_info/2` seems to imply the LiveComponent is a GenServer then perhaps `handle_message/2` might be a clearer name.

None of this is holding us back, we can just use `update/2` this way. But it would feel a bit neater if message handling was separated by the framework. What do you think?

**Comment by chrismccord** [comment]
`update/2` isn't component initialization tho – it is called whenever the parent renders (or re-renders) the child, so you can receive updated assigns from the parent. A separate callback is possible, but keep in mind this part of the lifecycle. For example, the way a component even messages itself today via work done in an async task is to send_update back to itself. A unified approach will need to take all this into consideration and be applicable to all these cases imo.

**Comment by robacourt** [comment]
Sorry, "initialisation" is the wrong word, but given the `assigns` parameter it seems to be about setting state (or perhaps the parameters of the component) not about message handling. 

The result of an async task also seems like something that's a message not a new set of assigns. Having `handle_message({:processing_complete, results}, socket)` means the response is explicitly handled, perhaps checking the assigns are in the right state to be changed, rather than hidden in an update function that perhaps just merges the assigns. This would also keep it in line with what would happen in a LiveView, for standardisation of code and potentially for Task reuse.

So `update/2` seems suitable for assigns and change of assigns by the parent, but something like `handle_message/2` would be better suited for: async results, doing something after a wait, PubSub subscriptions and handling messages from child LiveComponents. What do you think?

**Comment by JoshBones** [comment]
big disclaimer: I'm a front end guy who's only started dabbling with elixir / LV in the past few months so please forgive any errors or incorrect nomenclature.

I've been experimenting with something similar to what @chrismccord is using, but allowing arbitrary user defined fns for handling the messages instead of just `handle_info` for views and `update` for components as I've found having particularly  the number of `update` functions scale out makes the component harder to understand.

for views I've defined a macro that looks like this:

```ex
defmacro __using__(_opts) do
    quote do
      def create_callback(cb) when is_function(cb) do
        &send(self(), {:callback_function, cb: cb, value: &1})
      end

      def handle_info({:callback_function, cb: cb, value: value}, socket) do
        {:noreply, cb.(socket, value)}
      end
    end
end
```

and for components:

```ex
defmacro __using__(opts \\ []) do
    quote do
      def create_callback(cb, my_id) when is_function(cb) do
        &send_update(self(), __MODULE__, id: my_id, _type: :callback_function, cb: cb, value: &1)
      end

      def update(%{_type: :callback_function, cb: cb, value: value}, socket) do
        {:ok, cb.(socket, value)}
      end
    end
end
```

this is mostly working fine, but I've run into issues with defining an `update` fn for components due to the way LV handles it being optional. At the moment the components will need to define their own fallback `update` function that merges the assigns into the socket if they use this, which feels like a bit of a hack.

I could define it in the macro, but then there are issues if the user wants to override it with their own logic.

Anyone have any ideas how this could be improved?

**Comment by robacourt** [comment]
> Anyone have any ideas how this could be improved?

Have a look at our library @JoshBones : https://github.com/Dyad-AI/live_message
