### ISSUE TITLE
@socket not available in function components

### ISSUE THREAD

**Issue by thorsten-de** [phoenixframework/phoenix_live_view#1625]
While converting an app to live_view 0.16, i got some issues for components that use my `Router.Heplers`. As `@conn` in regular views, `@socket` is ubiquitous in any `LiveView` or `LiveComponent`. But it *is not available in function components*.

I appreciate that function components are lightweight, but not having `@socket` available was quite a surprise. If that is intentional, it could be mentioned in the docs. While upgrading, I faced several other issues (with upgrading Surface) and it took quite a while to figure out this one.

So, what would be the blessed way to generate urls in functional components? 

- building urls in parent stateful components or views and pass them down
- passing `@socket` down myself

Both seem inconvenient when functional components are nested more deeply.

**Comment by josevalim** [comment]
Hi @thorsten-de! 👋 

You need to explicitly pass the socket as argument to all function components that may need the socket. That's because function components are not really specific to LiveView. They can be used to generate emails, regular HTTP requests, and so on.

Besides the two options you mentioned, there are two additional ones:

1. Pass the URL as parameter
2. Use the endpoint to generate a URL. So something like `Routes.my_app_path(Endpoint, :index, [_])`

I hope this clarifies it!

**Comment by thorsten-de** [comment]
Thank you for reminding me of using the endpoint, that option slipped my mind.

I really like the lean and "less magic" route of phoenix.
