### ISSUE TITLE
Wrong documentation for `JS.dispatch/3`

### ISSUE THREAD

**Issue by moogle19** [phoenixframework/phoenix_live_view#1684]
### Environment

* Elixir version (elixir -v): Elixir 1.12.3 (compiled with Erlang/OTP 24)
* Phoenix version (mix deps): 1.6.2
* Phoenix LiveView version (mix deps): 0.17.1
* Operating system: macOS
* Browsers you attempted to reproduce this bug on (the more the merrier): Safari, Firefox
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Actual behavior

The documentation states the `:to` selector in `dispatch/3` as optional:
https://github.com/phoenixframework/phoenix_live_view/blob/4ba702329be92394d9299ade0d0a73eb1e49f354/lib/phoenix_live_view/js.ex#L133-L134

But it isn't:
https://github.com/phoenixframework/phoenix_live_view/blob/4ba702329be92394d9299ade0d0a73eb1e49f354/lib/phoenix_live_view/js.ex#L145-L147

(tried it with `JS.dispatch(some_cmd, [])`)

### Expected behavior
It should either default to the interacted element or the documentation shouldn't state it as optional.
I am not sure what the better behaviour is here.

**Comment by rktjmp** [comment]
Should this also be callable without any options?

The documentation specifies two options, both *optional*, but this call fails:

```html
<div phx-click={JS.dispatch("my_event")}></div>
```

```
function Phoenix.LiveView.JS.dispatch/1 is undefined or private
```

You're required to pass an empty list,

```html
<div phx-click={JS.dispatch("my_event", [])}></div>
```

The documentation doesn't outright *say* the list is optional, but it's sort of implied by both options *being* optional?

Proposed (I guess) changes could be seen here: https://github.com/rktjmp/phoenix_live_view/commit/69c8416e1dbce7479847113f6ac3899fdd74a361 I can submit a PR if pr-worthy. Not sure if the behaviour is intentional to be honest.
