### ISSUE TITLE
Is the transition API intentional?

### ISSUE THREAD

**Issue by en30** [phoenixframework/phoenix_live_view#1737]
Thank you for creating this great library. I am excited about JS Commands!
I've recently been trying to use JS Commands in my project, and I'm a little confused about the transition API, so let me ask if the API is intentional.

### Environment
* Elixir version (elixir -v): `Elixir 1.12.2 (compiled with Erlang/OTP 24)`
* Phoenix version (mix deps): `1.6.2`
* Phoenix LiveView version (mix deps): `0.17.5`
* Operating system:  macOS 11.6
* ~Browsers you attempted to reproduce this bug on (the more the merrier):~
* ~Does the problem persist after removing "assets/node_modules" and trying again? Yes/no:~

### Actual behavior
In the following, I will use the example classes `{"ease-out duration-300", "opacity-0", "opacity-100"}` taken from [HexDocs](https://hexdocs.pm/phoenix_live_view/0.17.5/Phoenix.LiveView.JS.html).

The current behavior is like below.

- adds `"ease-out duration-300"` and `"opacity-0"`
- wait for `:time` option value
- adds `"opacity-100"` and removes `"ease-out duration-300"` and removes `"opacity-0"`

### Typical behavior
[Alpine.js](https://alpinejs.dev/directives/transition#applying-css-classes), [Vue.js](https://vuejs.org/v2/guide/transitions.html#Transition-Classes) and [React](https://reactcommunity.org/react-transition-group/css-transition) adopt something like below.

- adds `"ease-out duration-300"` and  `"opacity-0"`
- wait for 1 animation frame
- removes `"opacity-0"` and adds `"opacity-100"`
- wait for `transitionend`
- removes `"ease-out duration-300"` and `"opacity-100"`

Is the current behavior intentional?

**Comment by chrismccord** [comment]
We similarly do the "typical" behavior. Add "ease-out duration-300", next animation frame add "opacity-0", next animation frame add "opacity-100", then waiting for `:time`, and remove.
https://github.com/phoenixframework/phoenix_live_view/blob/aa9ecc31f2fd847537c4ada8ae90eb7a28adf364/assets/js/phoenix_live_view/js.js#L135-L143

If something isn't working as expected, please let us know, but I'm using tailwind UI animations within these primitives. I believe we are functioning as you outlined for alpine/vue/react. Thanks!

**Comment by en30** [comment]
@chrismccord Thank you for taking your time.

I confirm that `toggle` and hence `hide` and `show` work in the "typical" way. But `add_class`, `remove_class` and `transition` do not seem so.
https://github.com/phoenixframework/phoenix_live_view/blob/aa9ecc31f2fd847537c4ada8ae90eb7a28adf364/assets/js/phoenix_live_view/js.js#L52-L76

I created a repository to reproduce the behavior.
https://github.com/en30/test_js_commands
Note that you have to reload after an action because some classes remain.

**Comment by totorigolo** [comment]
I came here to see if I was the only one noticing this surprising behavior. I share the same observations as @en30:

> `toggle` and hence `hide` and `show` work in the "typical" way. But `add_class`, `remove_class` and `transition` do not seem so.

My use case is a sliding side panel, that starts off hidden, and that you slides into view when you click a button. The panel does not cover all the screen, so I'm showing a div with semi-opaque background to hide the rest of the page. Therefore, I need to animate two different elements, so a single `toggle` does not work.

At first, I thought "ok, this is simple, two `show/hide` and I'm done". Well... it works for sliding the panel, but for the background it took me multiple tries:
- `toggle`/`show`/`hide` do not work because they remove the end class when the animation is complete, so I would get the nice transition then brutal switch to dark background.
- `JS.add_class("bg-opacity-70", to: "##{id}-bg")` does not work because it's missing the `bg-opacity-0` to start the animation. I cannot add it as initial class in the `<div>` because then I would need to remove it using JS command before the animation (hence my PS below).
- `transition` does not work because it first applies the start class, waits, then applies the end class, so the background would transition only at the end of the timer.

I ended up using `transition` but with a very small timer. The animation works, but it's quite confusing.

PS: Not related, but I asked myself because of the difficulties I had to create the animation, I think it could be useful to explain that chained JS commands all execute concurrently, not sequentially.

Here are a few proposals or ideas, if that can help:
- add a `:keep_end_class` option to `toggle`/`show`/`hide`, so that the end class is not removed at the end of the animation.
- explain that `toggle`/`show`/`hide` and `add_class`/`remove_class`/`transition` behave differently, or make them behave similarly.
- explain transitions in a chapter at the top of the module instead of copy-pasting the same comment for all the functions.
- explain that chaining commands do not execute them sequentially.

I would be happy to submit PRs if I can help.
