### ISSUE TITLE
Blur+debounce after live redirect push event to new LiveView

### ISSUE THREAD

**Issue by nickolaich** [phoenixframework/phoenix_live_view#1743]
### Environment

* Elixir version 1.12.3:
* Phoenix version 1.6.2:
* Phoenix LiveView version 0.16.4:
* Operating system - any:

### Actual behavior

LiveView A has an  input with attributes phx-debounce="500" phx-blur="blur-event"
LiveView A handles it correctly

if user types something and click on any link with live_redirect to LiveView B, phoenix quickly replaces it but debounced event was already scheduled on FE and it sends it to the new LiveView B that doesn’t have event handler for event “blur-event”.
If I remove debounce it works like expected but triggers a lot of events to the backend (in our case it works as a typeahead that makes search in db)
### Expected behavior

Is there a way to unregister all debounced events on live redirects or doesn't send them if live-view was changed in the meantime?
Adding handle_event("blur-event") to all live views or catch-all event handlers on all of live views doesn't look like a good option.

**Comment by mveytsman** [comment]
@ghedamat and I paired on digging into this one, here's some thoughts.

This is happening because when we do debounces, we set a timeout. These timeouts aren't cleared, instead we use a [counter](https://github.com/phoenixframework/phoenix_live_view/blob/2f6e213cec65e6ce00c906155ff379c14f27675f/assets/js/phoenix_live_view/dom.js#L196-L203) tied to each element to make sure we only do the callback on the last timeout to be triggered.

The timeout and the element is still in memory, so if we do a live_redirect and have a new view we'll still execute the timeout the callback. Since the element (and it's parent LV) are destroyed, we end up falling back on the root LV, . One thing that hides this in normal use is that we check to see if a view is connected before firing events and fail silently if it's not https://github.com/phoenixframework/phoenix_live_view/blob/dfb95e94f0e541bd03e8c1cd5d3a6b9b83028c92/assets/js/phoenix_live_view/view.js#L630-L631-- in my experiments this hid a lot of these in normal use if the debounce was too short.

There are two more edge cases that exist here with components
1) If the target is a component, we end up targeting a component with the same ID on the new LiveView. This may fail in the browser if we can't find a component with the same ID, or we'll just send the message to the wrong component.
2) It's possible to trigger this without switching the parent LiveView. E.g. a timeout that's targeting a component that gets destroyed before it triggers. 

# Solutions

## Probably won't work
1) Check whether the element is still in the DOM when deciding to do the callback.
This is problematic because it may be slow (I can't find an API for "is this element actually rendered" other than checking if it's a child of the document.body, and will still fail in the case where the element is there but the *target* is not.

2) Clean up elements' privates as they get destroyed
Not sure if this can be done efficiently, still doesn't handle the *target* disappearing even if the element does not.

3) Cancel the timeouts when an element is destroyed
This also doesn't account for the target being destroyed, but there may be an unrelated performance gain here -- my intuition is that it's not optimal to set a bunch of no-op timeouts, but I've done no measurements here.

## Best bet
4) We need to check whether the target exists at the time of the callback - but better yet we should resolve the target when we set the timer. I'm thinking we resolve the target to a DOM ID before the timeout, then when we are calling the callback we use `querySelectorAll` to find the DOM node we need. This also handles the case of JS.exec events which can be given query selectors. There's the edge case where a JS.exec on the root layout needs to just target the root view, but we can set that to be the query selector `[data-phx-main="true"]`.

# Other Thoughts
Do we want to log/warn when the live view isn't connected on `pushWithReply?`
Worth it to measure how bad is it to have a timeout for every keypress in a textarea?
