### ISSUE TITLE
Heex Lacks Block Comment Syntax

### ISSUE THREAD

**Issue by Miserlou** [phoenixframework/phoenix_live_view#1761]
Originally reported here: https://github.com/elixir-lsp/vscode-elixir-ls/issues/215

Suppose I have this template block:

![image](https://user-images.githubusercontent.com/139987/142197621-f860c19e-7840-4e98-b14a-c3d2009c98bf.png)

I would like to select all of it and press `Command+/` to comment it all out. This is the result:

![image](https://user-images.githubusercontent.com/139987/142197678-5d32d376-a80b-4b08-ad8e-68b8060a5af6.png)

Rather than having a commented out template, I now I have a wonky page.

It would be great (and pretty much necessary) to have a syntax for commenting out large blocks of a template all in one go, without having to worry about where the comment is stopped because of the template itself.

**Comment by josevalim** [comment]
Right now the only option is to comment each EEx tag individually. This not a Phoenix issue per se, the issue is that Elixir's EEx doesn't support it. Someone is welcome to submit a proposal to the Elixir mailing list, perhaps looking at how multi-commenting syntax is done for languages like PHP, ERb, and so on.

Something else you could do is to define this function component:

```elixir
def comment(_assigns) do
  ""
end
```

And now you can do:

```elixir
<.comment>

</.comment>
```

Around the chunk of code you want to ignore.

**Comment by simonmcconnell** [comment]
PHP `/* ... */`
Surface `{! - -  ...  --} `
Razor `@* ... *@`
ERb looks to use same hacks as EEx.

**Comment by Miserlou** [comment]
Discussion moved here: https://groups.google.com/g/elixir-lang-core/c/NZ5D5YjxoJ0

**Comment by chrismccord** [comment]
Honestly if the prior art is a special comment syntax that's not HTML comments, then I think the `<.comment` function component is the most ideal. We could ship it in `LiveHelpers` and have the vscode-phoenix plugin even syntax highlight it properly.
