### ISSUE TITLE
Add `JS.focus(element)` for programatically moving focus

### ISSUE THREAD

**Issue by ndarilek** [phoenixframework/phoenix_live_view#1765]
Programatically updating focus has several accessibility-related use cases:

* Some implementations might move focus to an `<h1>`, the first child element of `<main>`, or another relevant element on full page transitions. This serves as a quick way to tell screen readers that the page has changed by reading a new title, or by placing focus on newly-arrived text.
* As part of an accessible modal implementation, focus should be moved to specific elements of the dialog when it appears. This may require additional support for something like `setTimeout` to ensure that the focused element is visible before it is explicitly set.
* Focus management in forms and other UI controls is great for directing users to elements that require their attention, or that they may wish to engage with next in complex workflows.

There are some subtleties to this that I'd argue should be baked in:

* Focus cannot normally be set to elements without a focusable tabindex. I'd argue that an implementation should assume the user's intention is to focus the specified element regardless of whether it normally grabs focus. Therefore, it should probably check for a focusable tabindex and, where one isn't present, make the element focusable and restore the old tabindex value after being run.
* As previously stated, some use cases may require that focus change after a short delay, either via `setTimeout` or `requestAnimationFrame`. Perhaps this should be handled by a separate `set_timeout` call, or it might be baked in as an optional argument to hint at its necessity if someone doesn't understand why their modal or other newly-rendered element isn't gaining focus.

**Comment by chrismccord** [comment]
I think focus handling is going necessarily involve more client logic than a set JS commands can accommodate, so I would prefer to wait on this and have folks use hooks where needed. Note that you can also make this work via a JS command if all you really require is focus, by using dispatch + a single LOC in app.js:

```elixir
def focus(%JS{} \\ js) do
  JS.dispatch(js, "js:exec", to: to, detail: %{call: "focus", args: []})
end
```
```javascript
window.addEventListener("js:exec", e => e.target[e.detail.call](...e.detail.args))
```

Thanks!

**Comment by ndarilek** [comment]
I'm in partial agreement in that a robust solution definitely requires 
more consideration. But I think there's a lot of low-hanging fruit that 
this could help address.


For instance, the disclosure pattern as documented at 
https://www.w3.org/TR/wai-aria-practices-1.1/#disclosure can be 
implemented almost entirely in Elixir, and if implemented as documented, 
shouldn't require any `setTimeout` or `tabindex` hacks. Getting deep 
into the focus management trenches likely does require specific 
implementations, but it's definitely a point of friction that I can 
hide/show elements, set/remove attributes, etc., including with 
transitions and timeouts from Elixir, but that I have to resort to hooks 
and JavaScript for even the simplest of focus transitions. Just the 
ability to trigger focus transitions while leveraging whatever mechanism 
delays shows/hides would be very useful to consolidate logic in Elixir, 
even if we punt on tabindex tweaking for a while.


I'd like to request that this issue be re-opened, if only as a place to 
coordinate and brainstorm whether a good focus management primitive is 
possible. Thanks.

**Comment by josevalim** [comment]
> but that I have to resort to hooks and JavaScript for even the simplest of focus transitions. 

You also have to resort to JavaScript to implement dropdowns, drag and drop, clipboard management, password toggles, etc. At the end of the day, there is still a huge amount of functionality that requires dropping to JavaScript and it is not practical for LiveView to manage all of them. Of course, there is always a question of how much should be supported by JS commands but, to me, JS commands are about making it easy for users to not rely on the server (when they don't need the server in the first place) than solving client-side features.

FWIW, we also have a need for focus in Livebook and we are using a custom dispatch: https://github.com/livebook-dev/livebook/blob/b6ddf1883cec5bee80675ff95af8a1619a3da550/assets/js/app.js#L81-L83

**Comment by ndarilek** [comment]
Understood. Thanks for the clarification.

**Comment by mwcampbell** [comment]
To add to what @ndarilek has said on this, please consider that if we want application developers to do the right thing with regard to accessibility, we have to make it easy for them, meaning that as much as possible needs to be built into the framework. So we need _some_ kind of solution for the problems that @ndarilek has raised, built into LiveView. Otherwise, too many application developers will just ignore this.

**Comment by chrismccord** [comment]
@mwcampbell I absolutely agree that we want developers to do the right thing and making the right thing as easy as possible would enable that. The issue with `JS.focus`, is by itself it's not clear how far it gets folks. For example, for UI controls, client-side JavaScript is going to necessarily be involved handling keypress, focus, etc, so if you're already writing JS to support full accessibility then the JS command does not provide much utility. I do think it could be useful for giving focus to something that shows a modal, but the closest we could get is making it wait for `requestAnimationFrame`, but that may not be enough, such as when transitioning which is doing multiple requestAnimatoinFrame's applying different transitions. Our focus would need to be transition aware, and thus far JS commands compose, but are not aware of other commands. Accessibility is very important to us, but I am not yet convinced JS.focus can stand by itself. I will revisit if it turns out to be something generally useful outside of custom JavaScript.
