### ISSUE TITLE
How about `Phoenix.LiveView.JS.toggle` receives two commands tuple?

### ISSUE THREAD

**Issue by en30** [phoenixframework/phoenix_live_view#1766]
Current `Phoenix.LiveView.JS.toggle` is specialized to toggle `show` and `hide`.
If `Phoenix.LiveView.JS.toggle` receives two commands tuple, wouldn't this expand the possibility while still covering the current use case?

## Example Usecase
```ex
toggle({
  set_attribute({"aria-expanded", "true"}, to: "#button") |> show("#content"),
  set_attribute({"aria-expanded", "false"}, to: "#button") |> hide("#content"),
})
```

**Comment by josevalim** [comment]
We don’t want to support nesting of commands by default, due to the complexity that may arise from it. However, maybe we should consider supporting or automatically setting the aria flags as we show/hide?

**Comment by en30** [comment]
I understand that you don't support it for the good reason. Thank you.
I have tried implementing it. Indeed nested commands may become a source of complexity. There should be many pitfalls that I am not aware of too. 

As for adding behavior to show/hide, I don't know if there is a general and good way because there seems to be a wide variety of things to do on show/hide. Unfortunately, I don't know a11y very well.
Also, there is a use case not tied to visibility but which needs two states cycle. For example, [Toggle Switch](https://headlessui.dev/react/switch).

I will use server-side states or client-side hooks (maybe + `execJS`) to implement these use-cases for now. If I find a good pattern, let me give feedback to you.

**Comment by fuchsberger** [comment]
i am also very interested in learning how to best toggle an area-expanded flag without a trip to the server.

**Comment by ewildgoose** [comment]
I've hit a similar problem, in my case I observe that we have add_class / remove_class, but I really want a "toggle_class".

This seems like a simpler concern and inline with the existing API, so perhaps there is room for this

The use case would be such as:
- Toggling a button animates it to be toggled pressed (or unpressed)
- Switches, need a class adding/removing as they are clicked
- Sidebar menus often support clicking to unfold and re-fold them
- Dropdown menus often have an animated icon to indicate state, eg the sidebar above might have a little triangle which points down when unfolded and rotates 90 degree when folded.

Summary: Feature request: Add JS.toggle_class() function to automate toggling adding and removing classes

**Comment by lessless** [comment]
Seconding `toggle_class`

**Comment by woylie** [comment]
I also often find myself longing for a function in the `JS` module to toggle between two attribute values. Some examples:

- toggle `aria-expanded` between `"true"` and `"false"`
- toggle `aria-selected` between `"true"` and `"false"`
- toggle `aria-checked` between `"true"` and `"false"`
- toggle classes, e.g. `"is-active"`
- toggle data attributes

It would be nice to have a `toggle_attribute` and a `toggle_class` function:

```elixir
JS.toggle_attribute("some-element", "aria-expanded", "true", "false")
```

```elixir
JS.toggle_class("some-element", "is-active")
```

Automatically setting certain aria attributes would be nice, but it is a bit unclear how this would work, since the attribute to toggle and where to put it is dependent on the context.

It would be great if binding an attribute to the state of another element was supported in some way. Consider a drawer which is hidden by default on small screens using CSS media queries, but shown by default on larger screens. The button that toggles the drawer visibility needs to have an `aria-expanded` value depending on the sidebar state. At the moment, this isn't possible without involving JavaScript. It would be very convenient if you could bind an attribute directly to the state of another element, very roughly like this:

```html
<button
  phx-click={JS.toggle("main-drawer")}
  aria-expanded={JS.bind("main-drawer", :visible, "true", "false")}
>toggle menu</button>
```

**Comment by josevalim** [comment]
Closing for the same reason as #2619. We will be ok with adding toggle_attribute and there is already a PR.
