### ISSUE TITLE
Assign array is not refreshed when the content is a array for "options" of "select"

### ISSUE THREAD

**Issue by ChristopheBelpaire** [phoenixframework/phoenix_live_view#1783]
### Environment

* Elixir version (elixir -v): 1.12.3
* Phoenix version (mix deps): 1.6.2
* Phoenix LiveView version (mix deps): 1.7.5 
* Operating system: Mac OS X
* Browsers you attempted to reproduce this bug on (the more the merrier): 
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: yes

### Actual behavior
Hello!
When I use an assign array for "option" in an html select, the select options are not updated when the array is updated.
This is a regression since 1.7.0, the following example works with live view 1.6.4 :

```
defmodule BugOptionsLiveWeb.SelectLive do
  use BugOptionsLiveWeb, :live_view

  @spec render(any) :: Phoenix.LiveView.Rendered.t()
  def render(assigns) do
    ~H"""
    <%= Enum.map(@roles, fn({role, id}) -> role end) |> Enum.join(",") %>
    <.form let={form} for={:select} phx-change="validate" phx-validate="validate">
      <%= multiple_select(form, :roles, @roles) %>
    </.form>
    """
  end

  def mount(_params, _p, socket) do
    {:ok, assign(socket, roles: ["Admin": "1", "Power User": "2", "Basic User": "3"])}
  end

  def handle_event("validate", %{"select" => %{"roles" => [role_id]}}, socket) do
    IO.inspect(role_id)
    roles = Enum.reject(socket.assigns.roles, fn({role, id})-> id == role_id end)
    IO.inspect(roles)
    {:noreply, assign(socket, roles: roles)}
  end
end
```
 Here is a repo with the example  : https://github.com/ChristopheBelpaire/live_view_option_refresh_bug
### Expected behavior

In my example, If I click on one of the option in the select, it should be removed

**Comment by zorn** [comment]
I ran into what I think is a similar bug in my client's LiveView app.

We have a form on a LiveView page and as they fill out this form and hit submit we generate the wanted resource, display the list of resources on the page and then reset the `changeset` managing the form to a new `changeset` allowing a new resource to be created. Our observed bug behavior, running the newest version of LiveView `1.7.5`, was that the select input we had was not resetting as we expected.

I worked around the bug by generating a random UUID value called `changeset_id`, stored it on the assigns and then when we reached that point where we were resetting to a new changeset, would generate a new `changeset_id`. Since we attach that as the `id` of the `select` it resolved the issue for us.   

```
        <%= select f,
          :survey_type,
          survey_type_values(),
          prompt: "Select a survey type...",
          id: @changeset_id
        %>
```

Posting here for more awareness and workaround ideas.

**Comment by josevalim** [comment]
I have looked into this and the behaviour is "expected". LiveView does not change values of inputs that are currently focused. This is to avoid latent diffs undoing the job the user just did. In certain cases, however, like the two mentioned above, we want the opposite. Using the `id` is a solid trick to force LiveView to think it is a new component, therefore applying the desired changes.
