### ISSUE TITLE
Send referring URL on live redirect as param

### ISSUE THREAD

**Issue by chrismccord** [phoenixframework/phoenix_live_view#1789]

**Comment by mcrumm** [comment]
question: Would it make sense to send the referrer in `connect_params`?

I ask because historically params have been for path params, query params, and body params. Given that we send the connect params on each join, I wondered if it might make sense to inject the url on live redirect and use [`Document.referrer`](https://developer.mozilla.org/en-US/docs/Web/API/Document/referrer) on the initial join.

**Comment by josevalim** [comment]
Referrer is trickier because we may want to use it in both live_redirect and live_patch? 🤔

**Comment by mcrumm** [comment]
Good point! Any concerns about clobbering user-land params? Maybe we call it `__referrer` or something to attempt to avoid collisions?

**Comment by chrismccord** [comment]
Yeah we'll underscore it like `_target` and document

**Comment by chrismccord** [comment]
Already implemented some time ago as `_live_referer`
