### ISSUE TITLE
`phx-click-away` blocks `phx-click` on other elements

### ISSUE THREAD

**Issue by jonatanklosko** [phoenixframework/phoenix_live_view#1826]
This happens on master. Consider this example:

```
<button phx-click={JS.push("left")}>Left</button>
<button phx-click={JS.push("right")} phx-click-away={JS.push("away")}>Right</button>
```

Clicking on the left button triggers `phx-click-away` on the right, but doesn't trigger the actual click.

**Comment by chrismccord** [comment]
This is expected since we only trigger one in the same click epoch. phx-click-away will only take precedence if the element is visible in the DOM, so it shouldn't steal click unless it is shown, and thus has "focus". For background, we added this behavior because imagine you have a button which toggles a dropdown to be visible. If you click that button again, it should should phx-click-away and hide the active dropdown, but what will happen without this check is the dropdown would immediate toggle back.  I can see how this may be surprising for some UIs, but can you explain your usecase a little more so I can properly think about a way to accommodate it? Thanks!

**Comment by jonatanklosko** [comment]
I see! In Livebook we have this:

![image](https://user-images.githubusercontent.com/17034772/149215227-d94b286f-b158-45ce-9af9-fe40c512f65c.png)

Right-clicking on any file opens the menu. If the user clicks outside the menu we want to close it, but if they click anything inside the menu, we want to close it too. Currently we have `phx-click-away` on the file item, and it is triggered by clicking anywhere in the menu.

**Comment by chrismccord** [comment]
This should work with a single phx-click-away on the menu container, then you can hide the menu when an item is clicked:

```heex
<ul phx-click-away={hide_menu(file.id)}>
  <li>
    <button phx-click={hide_menu(file.id) |> JS.push("rename", values: %{id: file.id})}>Rename</button>
  </li>
  ...
</ul>
```
Does that work?

**Comment by jonatanklosko** [comment]
Yeah, but the the menu we have is a generic component, so closing it explicitly would break the abstraction:

```
<.menu id="my-menu">
  <:toggle>
    <button>Open</button>
  </:toggle>
  <:content>
    <button class"menu-item" role="menuitem">Option 1</button>
  </:content>
</.menu>
```

**Comment by chrismccord** [comment]
internally you are building a ul/li or container equivalent right? In such case you can wrap the slot markup with the js commands, no?

**Comment by jonatanklosko** [comment]
The options can be different elements, so we have just a single content slot for all of them.

```
<:content>
  <button class"menu-item" role="menuitem">Option 1</button>
  <a class"menu-item" role="menuitem">Link</a>
  <button class"menu-item" role="menuitem">Option 2</button>
</:content>
```

With this we leave the menu closing to the caller, while we would like this behaviour automatically.

**Comment by LostKobrakai** [comment]
I'm having problems with this change. This allows `phx-click-away` to work as expected with `JS.show`/`JS.hide`, but not for any of the other api in a "open dropdown" scenario.

Take this example:
```elixir
~H"""
<div id="dropdown"> 
  <button class="button" phx-click={JS.add_class("open", to: "#dropdown")}>
  <div phx-click-away={JS.remove_class("open", to: "#dropdown")}>Some content</div>
</div>
"""
```
```css
#dropdown div {display: none}
#dropdown.open div {display: block}
```

This will close properly when not clicking on the button, but won't close when the cursor is over the button, because both the `phx-click-away` and the `phx-click` fire removing and immediatelly readding the class.

**Comment by jonatanklosko** [comment]
@LostKobrakai you can put `phx-click-away` on the whole `#dropdown` and for the button use `JS.toggle` (we currently don't have `JS.toggle_class`, but that's the idea).

**Comment by jonatanklosko** [comment]
Let's say we have `phx-click-away` on a menu and a regular `phx-click` button somewhere outside. If the user opens the menu and then clicks the other button, it seems correct/intuitive to trigger the click. Does that make sense, or did I miss your point?

**Comment by LostKobrakai** [comment]
I've never seen a menu/modal/overlay (things where I'd use `phx-click-away` on) where I'd expect an click event on outside elements to happen tbh. Clicking outside of what was opened closes that thing and nothing else. I read through your remarks above as well, but I don't really get your usecase of putting the `phx-click-away` on the file instead of the opened menu itself.

**Comment by josevalim** [comment]
FWIW, Gmail does allow you to click on things outside with a dropdown out:

<img width="769" alt="Screenshot 2022-03-16 at 19 45 25" src="https://user-images.githubusercontent.com/9582/158664446-80550230-1b76-4438-a30d-0dbb309593e4.png">

**Comment by jonatanklosko** [comment]
> I've never seen a menu/modal/overlay (things where I'd use phx-click-away on) where I'd expect an click event on outside elements to happen tbh

It depends, if hovering over a button shows a pointer then it's something the user expects.

<details>
<summary>Example</summary>

https://user-images.githubusercontent.com/17034772/158663333-603241c5-42f4-470d-ae9e-c9fc875f8c9a.mp4

</details>

Note that this follows the default JavaScript behaviour and I'm not sure that `phx-click` should behave differently, because then it's confusing.

The approach you mentioned usually involves an actual overlay, to make sure hover outside the menu/modal is ignored ([example](https://mui.com/components/menus/#selected-menu)). So if that's the desired behaviour, you can introduce such overlay, no?

**Comment by LostKobrakai** [comment]
Lets maybe just stick to the example I posted. Let's not care about any additional buttons. What I care about is that the button opening the menu can close it again. This is not really possible currently without hooks or API not yet available, because the click event handler directly reopens the menu. 

I'm not sure how they manage it, but this is what I used previously in alpine.js to do exactly that: https://codepen.io/LostKobrakai/pen/dyJYeRM. 

Using a toggle on the `button` sounds like a good idea in theory, but we'd need a good toggle API, which can not just handle classes, but also all the other things needing to be toggled (e.g. aria attributes).

**Comment by jonatanklosko** [comment]
@LostKobrakai as mentioned, we can accomplish this with an actual overlay:

```heex
<div id="dropdown">
  <button phx-click={JS.add_class("open", to: "#dropdown")}>
    Open
  </button>
  <div class="dropdown-overlay"></div>
  <div class="dropdown-content" phx-click-away={JS.remove_class("open", to: "#dropdown")}>
    Content
    <a href="#">Link</a>
  </div>
</div>

<style>
  #dropdown:not(.open) .dropdown-overlay,
  #dropdown:not(.open) .dropdown-content {
    display: none;
  }

  #dropdown.open .dropdown-content {
    position: relative;
    z-index: 100;
  }

  #dropdown.open .dropdown-overlay {
    position: fixed;
    z-index: 50;
    top: 0;
    bottom: 0;
    right: 0;
    left: 0;
  }
</style>
```

This way, once the menu is open, all other elements are not directly reachable with pointer events :)
