### ISSUE TITLE
Non-root LiveView wont re-render when assigns update via PubSub broadcast during live patch

### ISSUE THREAD

**Issue by rktjmp** [phoenixframework/phoenix_live_view#1867]
### Environment

* Elixir version (elixir -v):
 
    Erlang/OTP 24 [erts-12.2] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [jit]
    Elixir 1.13.1 (compiled with Erlang/OTP 24)

* Phoenix version (mix deps): 1.6.6
* Phoenix LiveView version (mix deps): 0.17.6 (and [e94d145](https://github.com/phoenixframework/phoenix_live_view/commit/e94d145e6c611934c53f16699a393a90f4669443))
* Operating system: Linux
* Browsers you attempted to reproduce this bug on (the more the merrier): Firefox, Chrome
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Actual behavior

Under a particular combination of PubSub + nested Liveview, LV fails to re-render the view when its assigns are updated.

See https://github.com/rktjmp/phx-pubsub-socket-bug for reproduction and more background.

The views assigns do reflect the updated values, and the changes are retained between repeated updates, but the view is never re-rendered.

See also #1866, unsure if the bugs are on the same track, so opening two issues but feel free to close one as a dupe. I would imagine one causes the other, but wouldn't want this one to get missed by accident.

### Expected behavior

It re-renders when assigns are changed.

**Comment by chrismccord** [comment]
Are you providing the nested LV a new ID on handle_params? We don't re-render (remount) a nested child unless its ID changes, so I don't believe this is an issue. Thanks!

**Comment by rktjmp** [comment]
The nested LV is inside the root layout, not sure how I would update its ID from another LVs handle params?

Also it *does* update, if I fire events in the correct order, which would be:
 
- make notification <- re-renders via broadcast
- alice <- no render via broadcast
- bob <- no render via broadcast 
- make notification <- re-render via broadcast

**Comment by chrismccord** [comment]
If you run `liveSocket.enableDebug()` do you see any duplicate ID warnings, and do you see a diff coming over the wire for your update which isn't being applied to the HTML?

**Comment by rktjmp** [comment]
No duplicate ID warnings.

I do see the patch come down the wire:

Here I have clicked:

- Make notification
- Alice
- Bob

No warnings, `ListenLive` view is printing `update`, so they are getting down the wire, but the list of notifications is not updated to contain the two "alice" or "bob" events.

![image](https://user-images.githubusercontent.com/866010/152392210-fe20311a-22c0-416e-9e86-b0da206d3dce.png)

Now I click "Make notification", and they are all rendered:

![image](https://user-images.githubusercontent.com/866010/152392565-e87ec341-3508-4caf-8dcc-57f468717b90.png)

**Comment by rktjmp** [comment]
Also note that removing the sleep from [here](https://github.com/rktjmp/phx-pubsub-socket-bug/blob/02ed73ffc2f5a3c38598ff386527c540aaf93055/lib/sticky_bug_web/live/bug_live.ex#L35) "fixes" the issue, as does swapping the position of the `notify(...)` call per the comments.

My "real" handle params is:
```elixir
  @impl true
  def handle_params(_params, uri, socket) do
    # socket is passed only to extract the topic, no changes are made
    Notify.success(socket, "moved", uri)
    {:noreply, socket}
  end
```

So not exactly a lot of work being done or timing to fiddle with, I think the real app just has more going on in terms of rendering views, etc, that the "sleep" delay is intrinsic.

**Comment by rktjmp** [comment]
Not sure if this is helpful, I guess just confirming the observed.

`view.js` does push the diff into `pendingDiffs`, but somehow they are getting dropped by the time we run `applyPendingUpdates`.

In a working state, the WS events come ordered as `live_patch`, `reply`, `diff`.
In a bad state, the WS events are `live_patch`, `diff`, `reply`, so perhaps the diff is getting discarded because the patch operation is "still pending"? Not 100% on how the whole system works yet.

**Comment by rktjmp** [comment]
I think I tracked this down.

`pendingDiffs` is set correctly on the `ListenLive` view, (we mark the diffs as pending because `this.liveSocket.hasPendingLink() == true` when the diff comes through).

Once the patch comes through, `applyPendingUpdates()` only runs for the main view, via the `pushWithReply` call back, so the non-root view never gets ask to run `applyPendingUpdates()`.

**Comment by rktjmp** [comment]
If anyone else lands on this, I got around it in my particular case by wrapping the "diff event" call in a slept task. Not exactly sustainable but at least it functions until there is a fix in LV.

```elixir
Task.start(fn ->
  Process.sleep(200) # try to pick something that wont outpace the patch event
  Phoenix.PubSub.broadcast(MyApp.PubSub, topic(token), notification)
end)
```

**Comment by inaniyants** [comment]
I had a similar problem in Liveview v`0.17.5` (before the `sticky` option was introduced), I tried to mount dedicated LiveView in the root template to keep its state between `live_redirects`. But it didn't re-render if was coming while the main live_view was replaced with new. There was no official way to keep some liveview state, when `live_redirect` happens and the main LiveView changes.

> `pendingDiffs` is set correctly on the `ListenLive` view, (we mark the diffs as pending because `this.liveSocket.hasPendingLink() == true` when the diff comes through).

You are correct. Back that day I have tracked the problem also, but I refused such a solution and waited for an official solution (like `sticky` option). 

In LiveView v`0.17.6` sticky option was introduced, which enabled to keep the state between `live_redirect`. But neither  `live_redirect` nor `live_patch` isn't updating sticky views with pending diffs, which were come in the background, while the main view had a pending link. In order to solve both problems I have prepared another PR https://github.com/phoenixframework/phoenix_live_view/pull/1885.

**Comment by abstractcoder** [comment]
I just wanted to chime in that I'm currently running into the same issue and am using the work around from @rktjmp 

> If anyone else lands on this, I got around it in my particular case by wrapping the "diff event" call in a slept task. Not exactly sustainable but at least it functions until there is a fix in LV.
> 
> ```elixir
> Task.start(fn ->
>   Process.sleep(200) # try to pick something that wont outpace the patch event
>   Phoenix.PubSub.broadcast(MyApp.PubSub, topic(token), notification)
> end)
> ```

**Comment by tenmoves** [comment]
> I just wanted to chime in that I'm currently running into the same issue and am using the work around from @rktjmp
> 
> > If anyone else lands on this, I got around it in my particular case by wrapping the "diff event" call in a slept task. Not exactly sustainable but at least it functions until there is a fix in LV.
> > ```elixir
> > Task.start(fn ->
> >   Process.sleep(200) # try to pick something that wont outpace the patch event
> >   Phoenix.PubSub.broadcast(MyApp.PubSub, topic(token), notification)
> > end)
> > ```

Hello @abstractcoder  can you please explain what do you mean by "diff event" ? are you catching the diff events somewhere in your code ? 

for information, we might be suffering from the same problem, for us it only happens when we are over a specific number of keys in the assigns (32 without counting the necessary liveview keys like __changed__). 

from our side we don't even receive the diff events when inspecting in the browser.

Thanks,

**Comment by abstractcoder** [comment]
@tenmoves my diff event occurs when my LiveView receives a PubSub broadcast, I update my assigns, and LiveView re-renders the page.

This only occurs when I trigger a redirect at the same time as broadcasting an update.

I have since changed my solution to delay the redirect instead of the broadcast. This is less noticeable to the user so I can have a longer delay, which leads to few cases where my sticky LiveView fails to update.

I am still looking for a permanent fix because this issue still occurs occasionally even when introducing a delay.
