### ISSUE TITLE
A slot entry must be a direct child of a component

### ISSUE THREAD

**Issue by aymanosman** [phoenixframework/phoenix_live_view#1870]
Given

```heex
<.alert>
  <%= for error <- @errors do %>
   <:error>
     Some Error <%= error %>
   </:error>
  <% end %>
</.alert>
```

I get the following error message.

```
invalid slot entry <:error>. A slot entry must be a direct child of a component
```

I'm just wondering whether there is a plan to support such a use-case because it would be neat.

**Comment by thiagomajesk** [comment]
Hey @aymanosman, wouldn't this yield the same result for this use case?

```elixir
def alert(assigns) do
  ~H"""
  <div>
    <ul>
       <%= for error <- @errors do %>
         <li><%= render_slot(error, error) %></li>
       <% end %>
     </ul>
  </div>
  """
end
```

```html
<.alert>
  <:error let="error">
    Some Error <%= error %>
  </:error>
</.alert>
```

**Comment by chrismccord** [comment]
Confirm, @thiagomajesk is the solution to achieve what you want. Thanks!

**Comment by aymanosman** [comment]
That works! Thanks.

There was just a small typo in your example.

This `let="error"` should be `let={error}`

**Comment by ssbb** [comment]
Just to confirm - there is no plans to allow this behaviour so it's by design or just temporary limitation until it will be done?

Like in `<.table>` component example from docs - if I need to hide column based on some conditions. I can just pass something like `<:col show={...}>` and hide it inside table component - it is a way to go?

**Comment by chrismccord** [comment]
confirm
