### ISSUE TITLE
Add Functionality to Execute Only On First Render

### ISSUE THREAD

**Issue by Miserlou** [phoenixframework/phoenix_live_view#1877]
Here's a sticky one!

I have a little random greeter function in my template: `generate_greeting()`, which returns a string like, “Hello!”, “Bonjour!”, or “Konichiwa!”, etc.

If I put this function directly in the template `<%= generate_greeting() %>`, then it displays when the page first loads, but then visibly changes when the WebSocket mounts. (My reading of the docs seem to suggest this shouldn’t happen, but it does, I assume because it's a non-deterministic function.)

I tried using a socket assign in mount, but of course that didn’t work, but that’s expected. So, I have a solution which checks if the socket is already connected to generate the greeting, like so:

```
if connected?(socket) do
      {:ok,
      socket
       |> assign(:greeting, generate_greeting())
    }
else
      {:ok,
        socket
        |> assign(:greeting, "")
      }
end
```

The problem with this is that there is a sudden flash of content only the second mount, which is visually jarring.

So, what I'd like is to call the function _on the first page render only_. It seems like this should be quite easy, but I haven't found a solution.

What I'm imaging is something like:

```
<div phx-update="once">
   <%= generate_greeting() %>
</div>
```

which would tell the renderer to only call this function a single time, and then to treat it as a static content after that.

Any thoughts?
Cheers,
R

**Comment by josevalim** [comment]
I think ignoring some of the content on subsequent renders can lead to weird to trace bugs. For example, what if the user connection quickly drops and reconnects? Should it reload? But what if it should reload because there was a typo in one of the greetings and you just hot fixed it?

I think the correct fix is to give all greetings an ID. In your dead/initial render, you will do this:

    <div data-greeting-id=3>Olá!</div>

Now you can pass a function to LiveSocket that allows you to attach extra parameters to mount:

    let liveSocket = new LiveSocket("/live", Socket, {
      ...,
      params: () => query_greeting_id_from_dom(),
    })

Now in the server you can show the exact same greeting id you did on the initial render.
