### ISSUE TITLE
Question: Nested LiveView Re-render

### ISSUE THREAD

**Issue by pcorey** [phoenixframework/phoenix_live_view#190]
Imagine that I have a LiveView that renders another nested LiveView, `FooLive`. The parent's leex might look something like this:

```
<p>Hey, look at <%= @bar %>!</p>
<%= live_render(@socket, FooLive, %{bar: @bar}) %>
```

When the parent LiveView components updates `@bar` in its assigns, the child LiveView component won't be updated with that new value. The parent component will show the new value of `@bar`, but the child will still have the old value in its `assigns`. I assume this happens because the child only uses `@bar` in `mount`, and is left to manage its own assigns from then on, but this seems really counter-intuitive to me, especially coming from a React mindset. I would expect `@bar` in the child to be updated with the new value, or at least be given some mechanism for making that happen.

I can use `child_id` to force a re-mount if `@bar` changes:

```
<%= live_render(@socket, FooLive, %{bar: @bar}, child_id: @bar) %>
```

But this is clunky if `@bar` doesn't naturally coerce into a string, and is unideal in a lot of situations. I usually don't want to entirely remount my nested component, I just want to update the already mounted component's assigns so it can efficiently update itself.

**Am I missing anything here, or is this how LiveView handles its nested children?**

Maybe a good way of handling this is to add some kind of `update` callback that is called on every re-render with the updated `session` values. That might give us an opportunity to update a nested components `assigns`, if we see fit?

```
def update(params, socket) do
  {:ok, assign(socket, bar: params.bar)}
end
```

Or maybe just call `mount` again without actually re-rendering the entire component? I don't know nearly enough about LiveView's architecture to be making these suggestions, tbh.

I feel like I'm in fairly uncharted waters nested LiveViews like this, but I feel like there's a lot of potential here.

Thanks!

**Comment by chrismccord** [comment]
We don't support passing assigns directly. Perhaps you meant to use the session?

```elixir
<%= live_render(@socket, FooLive, session: %{bar_id: @bar.id}) %>
```

What you want to do is pass bar (or it's minimal data required to rebuild it, via the session). Anytime the parent changes `@bar`, `live_render` will be recalled, and the child will be remounted with the new data (if its session change via the parent, the LV is remounted). This accomplishes your `update` task without a new mechanism. 

Coupled with `assign_new` in the child, you can avoid the extra data lookup as well:

```elixir
def mount(%{bar_id: bar_id}, socket) do
  # use parent's `bar`, falling back to our own lookup
  {:ok, assign_new(socket, :bar, fn -> get_bar(bar_id) end)}
end
```

> Or maybe just call `mount` again without actually re-rendering the entire component? I don't know nearly enough about LiveView's architecture to be making these suggestions, tbh.

This is essentially the above approach does, but it does re-render the entire component as a new mount and new process. The benefit here vs a separate `update` mechanism, is if the data dependency changes, you likely need to refetch your data deps as well, which is what your `mount` code path already accomplishes. A subscription based "let me know when my parent's assign changes" is something we are thinking about, but not ready to pull the trigger on prematurely. The session approach gives you this feature without completing the lifecycle and code paths so that's the way to go for now. Thanks!

**Comment by elcritch** [comment]
This is helpful information! Would it be possible to incorporate it into the documentation? Also, it's unclear to me still if the data passed via the session like `<%= live_render(@socket, FooLive, session: %{bar_id: @bar.id}) %>` is part of the signed session data.

**Comment by chrismccord** [comment]
the session always represents the signed session data, and shoudl be the minimal data necessary to rebuild your full state on mount

**Comment by AllanPinheiroDeLima** [comment]
I did not find this in the docs. Where do I find more information about this behavior ?

**Comment by RodolfoSilva** [comment]
For other folks(like me) that keep asking, how we can fornce the nested LiveView, read this:
https://github.com/phoenixframework/phoenix_live_view/blob/e4c6f7140d5b8c383e584671a63c14e85e9c26e9/lib/phoenix_live_view.ex#L371-L379 

You will need to generate a new `:id` and pass this to `live_render/2`
