### ISSUE TITLE
Change tracking doesn’t pick up change of unrelated assign within list comprehension

### ISSUE THREAD

**Issue by kerryb** [phoenixframework/phoenix_live_view#1908]
Apologies if I’m trying to do something unsupported – I don’t think this falls under the documented heex pitfalls, but maybe I misread them.

### Environment

* Elixir version (elixir -v): Elixir 1.13.3 (compiled with Erlang/OTP 24)
* Phoenix version (mix deps): 1.6.6
* Phoenix LiveView version (mix deps): 0.17.7
* Operating system: Mac OS Monterey version 12.2.1 (21D62)
* Browsers you attempted to reproduce this bug on (the more the merrier):
  * Chrome 99.0.4844.51 (Official Build) (x86_64)
  * Firefox 97.0.1 (64-bit)
  * Safari 15.3 (17612.4.9.1.8)
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: n/a (using esbuild)

### Actual behavior

See [sample app](https://github.com/kerryb/change_tracking_bug).

I have a list comprehension in a template, with an unrelated assign (`@choice`) also used within the block:

```heex
<form phx-change="change">
  <p>Selected item is <%= inspect @choice %>.</p>
  <select name="choice">
    <%= for item <- @items do %>
      <option selected={item == @choice}><%= item %></option>
    <% end %>
  </select>
</form>
```

Selecting a value from the list triggers a `push_patch`, which adds the choice to the URL and updates the displayed value:

```elixir
def handle_event("change", %{"choice" => choice}, socket) do
  {:noreply, push_patch(socket, to: "/#{choice}")}
end

def handle_params(params, _uri, socket) do
  {:noreply, assign(socket, choice: params["choice"])}
end
```

This appears to works correctly, but isn’t actually changing the _selected_ item in the select input. This becomes an issue when using the browser’s back button – if you change the selection a few times, then go back through the history with the back button, the _Selected item is …_ text changes as expected, but the select input doesn’t change to match.

### Expected behavior

The deselected and selected items in the select input should be rerendered when the assigned value changes.

**Comment by josevalim** [comment]
Thanks for the report, it was clear!

This behaviour is intentional. We don't change an input/select/textarea while it is being selected/focused/used because this would lead to race conditions. For example, take an input, as you are typing, it is being validated on the server, the server is sending the filled in input with the "old" version of the value, which you don't want to override the actual value.

There are ways you can address, perhaps you can give a new ID to the select every time it is rendered but it feels like you are running into an anti-pattern, so you should probably revisit the approach altogether.

**Comment by kerryb** [comment]
Thanks for the quick response. Looks like I need to tweak my design a little!
