### ISSUE TITLE
Fragment is being parsed as part of param

### ISSUE THREAD

**Issue by zkat** [phoenixframework/phoenix_live_view#2041]
### Environment

* Elixir version (elixir -v): 1.13.2
* Phoenix version (mix deps): 1.6.9
* Phoenix LiveView version (mix deps): 0.17.9
* Operating system: Windows
* Browsers you attempted to reproduce this bug on (the more the merrier): Edge
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: N/A

### Actual behavior

Given a route like `/foo/:name`, when I try to `push_patch(to: "/foo/bar#fragment", replace: true)`, the LiveView's `handle_params` is receiving `%{"name" => "bar#fragment"}`.

### Expected behavior

I would expect params to be  `%{"name" => "bar"}`.

**Comment by chrismccord** [comment]
I'm not sure what the best approach for handling this would be, but note that you cannot really push a fragment to the server because the browser never sends the fragment on HTTML requests. It is only a local client thing, so I would avoid push_patch with a fragment entirely and let the browser go to the correct anchor on the client. If you need to also change content based on the anchor, I would either ditch the anchor in favor or pretty URL params, or I would use phx-click on a regular anchor with a fragment. Thanks!

**Comment by zkat** [comment]
In my case, it's neither about updating the content based on the hash _nor_ about sending the hash itself to the server (I have that in the handle_params uri param already. What I'm trying to really do is preserve the URL as much as possible when doing a `:replace` on patch.

My use case is that I'm adding a `?` url param to some links, and when the user visits a page with that particular param, I remove _only that param_, and do a `push_patch` into the same view to update the view based on the _param_ change. But as part of that, I want to replace the history entry to have that param removed because it's meant to be a temporary "magic" thing.

So given a URL like `https://my.app/foo/bar?magic=1#some-anchor`, I want to push_patch to `https://my.app/foo/bar#some-anchor`, and replace the history entry accordingly (with `:replace`).

I'm not sure how your suggestion would address this?
