### ISSUE TITLE
Formatter removes space in inline elements

### ISSUE THREAD

**Issue by dvic** [phoenixframework/phoenix_live_view#2043]
### Environment

* Phoenix LiveView version (mix deps): 0.17.10 and master

### Actual behavior

The formatter converts

`<p><b>Foo: </b><%= some_var %></p>`

into

`<p><b>Foo:</b><%= some_var %></p>`

### Expected behavior

To keep the space inside inline elements. When you use this kind of pattern:

```
<p><span class="hidden lg:inline"> at </span><%= time %> hour</p>
```

**Comment by dvic** [comment]
I agree that most of the time we don’t want the space. How much effort is it to change the behavior to only remove the space if the closing tag is directly followed by a space (or newline)? Because in these situations it’s ok to remove the inner space, in other cases it breaks the intended rendering.

**Comment by achempion** [comment]
In the example you've described, having spaces inside `<b>` can be considered as cleanup opportunity for formatter.

As a workaround you can use `&nbsp;` for a space character.

**Comment by dvic** [comment]
> In the example you've described, having spaces inside `<b>` can be considered as cleanup opportunity for formatter.
> 
> As a workaround you can use `&nbsp;` for a space character.

Technically, it' changing the way the HTML is rendered, I could do a search for these kind of common patterns and replace it with another approach (like adding whitespace after like @feliperenan suggested) but it would be nice if the formatter only removed this whitespace if it does not affect the rendering (i.e., if the the closing tag is directly followed by a space or newline, like this:

```html
<p>
  <b>Foo: </b>
  <%= some_var %>
</p>
```

**Comment by leandrocp** [comment]
One possible fix is preserving the text inside inline elements when it's just a text without breaks: https://github.com/phoenixframework/phoenix_live_view/pull/2045

Wdyt? 🤔

**Comment by josevalim** [comment]
What if we keep space around tags? Or is that too complicated?

**Comment by feliperenan** [comment]
@josevalim not sure if I get it. If we keep spaces around we would introduce unwanted spaces, wouldn't we? 🤔

**Comment by josevalim** [comment]
@feliperenan can you give an example? :)

**Comment by leandrocp** [comment]
Are we talking about two scenarios here? :)

One is preserving/keeping spaces between tags, eg: `<b>Foo:</b> <%= some_var %></p>`. AFAIK that space is preserved already so it's fine.

Another one is _adding_ a space, eg formatting `<b>Foo: </b><%= some_var %></p>` to `<b>Foo:</b> <%= some_var %></p>`. If that's the idea I can see it introducing unwanted spaces, for eg one would expect the template `<span>1</span><span>+</span><span>2</span>` to be rendered as "1+2", right?

**Comment by josevalim** [comment]
I was thinking about preserving the space after the opening tag and before the closing tag. So:

```
<p>
  Foo
</p>
```

remains as such because the opening tag is followed by a newline.

And `<p> Foo </p>` remains as so because opening tag and closing tags are followed by spaces. We should only preserve a single space.

WDYT?>

**Comment by josevalim** [comment]
I think complexity wise, we can handle it when we tokenize. When we trim all spaces for the opening tag, we can do:

1. If there are newlines, we trim all spaces and annotate the newline in the node (as we do today)
2. If there are no newlines, but there are spaces and then text, add a single space before the text
3. All other scenarios keep the trimming as is today

The addition here is 2, which only happens when there are no newlines, there is space and some text (but not another tag) after the space. The checking of text is important so `<p> <b>Foo: </b><span>bar</span> </p>` becomes `<p><b>Foo: </b><span>bar</span></p>`.

WDYT?

**Comment by feliperenan** [comment]
@josevalim @leandrocp sent a solution that might solves that based on Jose's last comment. Please, take a look 🙌🏻
