### ISSUE TITLE
Unchanged assigned data being transferred over socket

### ISSUE THREAD

**Issue by sevenseacat** [phoenixframework/phoenix_live_view#215]
### Environment

* Elixir version (elixir -v): 1.7.4
* Phoenix version (mix deps): 1.4.5
* NodeJS version (node -v): 10.15.3
* NPM version (npm -v): 6.9.0
* Operating system: MacOS 10.14.4

### Actual behavior

See commit in sample repo here: https://github.com/sevenseacat/live_view_bug/commit/d516d815d9947accf198aedb05e1d8212ab246b9

When updating a single assigned value in an event, all assigned data is rendered and transmitted back to the client over the socket, even though nearly all of it is unchanged.

This can cause performance issues for a more involved template because each of the assigned elements gets processed and updated in the client.

(see screenshot from Chrome dev tools)

<img width="1254" alt="Screen Shot 2019-05-12 at 2 57 39 pm" src="https://user-images.githubusercontent.com/543859/57578863-53d00880-74c6-11e9-9056-e6bdf3b882c2.png">

### Expected behavior

That only the updated assigned value would be transferred over the socket, and processed on the client.

**Comment by chrismccord** [comment]
In this case, we can't optimize the for comprehension dynamically looking up assigns, because we do our change tracking at compile time (`@my_assign`). So in this example we'd optimize if you had hard-coded the assigns in the template, but the dynamic lookup won't work. From our convo on twitter, it sounds like what you are after in the end is optimized collections, and that is on the roadmap so we would allow append/prepend/remove without re-sending everything. Just to be clear, the following would optimize:

```eex
<h1>Counting <%= @count %> items!</h1>
<ul>
  <li>
    <%= @assigns1 %>
    <button phx-click="change" phx-value="<%= @assigns1 %>">Change Me</button>
  </li>
  <li>
    <%= @assigns2 %>
    <button phx-click="change" phx-value="<%= @assigns2 %>">Change Me</button>
  </li>
</ul>
```

Hope that helps. Thanks!

**Comment by sevenseacat** [comment]
Oh that makes perfect sense. Yeah ideally I'd be using a collection, I was just rather surprised that it didn't work with the separate assigns - didn't even twig that it was my template code causing the issue. Thanks 😊
