### ISSUE TITLE
Support range values on integer attrs

### ISSUE THREAD

**Issue by cblavier** [phoenixframework/phoenix_live_view#2256]
I would like to declare a component attr as such:

```
  attr :value, :integer,
    doc: "A progress value, between 0 and 100.",
    values: 0..100
```

In the storybook library, we're currently handling range values with a dedicated number input

**Comment by Ninigi** [comment]
I think this would be great, but could explode into a number of validation requests (only allow certain ascii strings, validate max length of a list, validate a map, make sure a string value is a valid path in the phoenix routes, etc.)  - what if we could actually add validations like in ecto changesets, with hard error messages when the values don't pass the validation? Is that a good idea, or just totally blowing @cblavier suggestion out of proportion?

The API I am thinking of would feel kind of clunky, so that might be a good indicator I am thinking along the wrong line

```elixir
attr :value,
      :integer,
      doc: "A progress value, between 0 and 100.",
     validate: [
       inclusion: 1..100
     ]

attr :value2,
      :string,
      doc: "A string of 10 lower case letters",
      validate: [
        inclusion: `a`..`z`,
        length: 10
      ]
```
I also have no idea how to handle "validate x OR why" etc., outside of passing a named function.

**Comment by cblavier** [comment]
The range option I'm asking for is only a compile-time hint, not a runtime validation feature.
I'm unsure if it is out of scope for LiveView, but I think it is unrelated to the current ticket.

**Comment by josevalim** [comment]
@cblavier I would be ok with allowing any enumerable in `:values`. We can do the checks using `x in enum`.  :+1:
