### ISSUE TITLE
attribute phx-disable-with does not support double invalid input

### ISSUE THREAD

**Issue by ndrean** [phoenixframework/phoenix_live_view#2274]
### Environment

* Elixir version (elixir -v):
* Phoenix version (mix deps): 1.16.12
* Phoenix LiveView version (mix deps): 0.18.1
* Operating system:

### Actual behavior

When submit several times an invalid form, I should have always the same error message rendered by the changeset. This is not the case.

My form:

```elixir
<.form :let={f}
        for={@changeset}
        id="form"
        phx-disable-with="sending..."
        phx-change="validate"
        phx-submit="up_date"
        phx-target={@myself}
>
   <%= submit "Update" %>
   <%= date_input(f, :event_date, id: "event_date") %>
    <%= error_tag f, :event_date, class: "text-red-700 text-sm m-1" %>
</.form>
...
```

and the "submit" handler:

```elixir
case changeset.valid? do
false ->
      changeset = Map.put(changeset, :action, :insert)
      {:noreply, assign(socket, :changeset, changeset)}
end
```

When I submit my invalid form the first time, I get a normal error message

![Screenshot 2022-10-11 at 18 12 20](https://user-images.githubusercontent.com/6793008/195144595-51315ed1-5722-4897-802a-246a96ab1a22.png)

When I submit it again, the form disappears:

![Screenshot 2022-10-11 at 18 13 45](https://user-images.githubusercontent.com/6793008/195144909-357a72a3-2961-4119-936b-6b90428bc123.png)

It appears that the attribute `phx-page-loading disabled` is set to the form the second time.

Solution: remove `phx-disable-with`

Is this the desired behaviour?

**Comment by chrismccord** [comment]
We need more information to say what is going on here. The fact that the form disappears implies invalid HTML somewhere. If you an provide a reproducible example, please let us know. Thanks!

**Comment by mcrumm** [comment]
You are setting `phx-disable-with` on the form when it is meant to be set on the submit button, for instance:

```html
<button type="submit" phx-disable-with="Saving...">Save</button>
```

Review the [form bindings](https://hexdocs.pm/phoenix_live_view/form-bindings.html#javascript-client-specifics) docs for more info, but move it from the form to the button and you should be good to go :)

**Comment by bogui** [comment]
I can confirm:

I have this html:
``` heex
<button
    type="button"
    phx-click="check_eik_vies"
    phx-value-country={@current_country_id}
    phx-value-eik={@company[:eik].value}
    phx-disable-with="Checking..."
    class="absolute top-0 right-0 p-1.5 text-sm font-medium text-white bg-blue-700 
          rounded-r-lg border border-blue-700 hover:bg-blue-800 focus:ring-4 
          focus:outline-none focus:ring-blue-300 dark:bg-blue-600 dark:hover:bg-blue-700 
          dark:focus:ring-blue-800"
>
    <%!-- <.icon name="hero-magnifying-glass-mini" class="w-4 h-4" /> --%> Search
</button>
```
and I have this check_eik_vies handle_event: 
``` elixir
def handle_event("check_eik_vies", %{"country" => _country_id, "eik" => _eik} = _params, socket) do
    :timer.sleep(5000)
    {:noreply, socket}
end
```

The first click on the button works just fine - its state is set to disabled, the text is set to "Checking..." and after 5 sec, the state and text are rolled back - state: enabled, text: Search (it should be an icon, but I thought the problem is in the icon itself).
![image](https://user-images.githubusercontent.com/15086926/236443015-36850ef0-e280-4ff3-87ed-7181dc10ec8a.png)


The second click, however, sets the state to disable, changes the text to "Checking..." and after 5 sec rolls back the text, but not the state. With the icon the following happens - the state of the button is disabled and the icon element is missing!
Before:
![image](https://user-images.githubusercontent.com/15086926/236443188-47253ffc-6c65-440a-94ae-bdfa54feb3d2.png)
After second click:
![image](https://user-images.githubusercontent.com/15086926/236443309-a3b13d89-faa4-4cb3-8022-ef7aadbe8d6b.png)
