### ISSUE TITLE
Maintain `<details>` native behaviour across LV updates

### ISSUE THREAD

**Issue by LostKobrakai** [phoenixframework/phoenix_live_view#2349]
### Environment

* Elixir version (elixir -v): 1.14.2
* Phoenix version (mix deps): master
* Phoenix LiveView version (mix deps): 15ec572
* Operating system: Mac OS
* Browsers you attempted to reproduce this bug on (the more the merrier): Firefox
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: 

### Actual behavior

Open `<details />` element get's closed with LV updates.

### Expected behavior

`<details />` `open` attribute is maintained beyond LV updates. The attribute is set by user interaction with the browser implementation – no js involved – and that is essentially broken.

**Comment by chrismccord** [comment]
I am unsure about this one because the server could also render it with `open` (or without), so ignoring the server updates to use what is on the client may be incorrect behavior. I think the best option for now until we have a comprehensive answer is to use the dom options and maintain the values yourself:

```javascript
let liveSocket = new LiveSocket("...", {
  dom: {
    onBeforeElUpdated: (fromEl, toEl) => {
      if(["dialog", "details"].indexOf(fromEl.tagName) >= 0){
        Array.from(fromEl.attributes).forEach(attr => {
          toEl.setAttribute(attr.name, attr.value)
        })
      }
    }
  }
})
```

You could also generalize this to allow something like `<any-tag data-keep="open foo bar">` or similar. Thanks!

**Comment by paulstatezny** [comment]
Thanks for this solution Chris!

Note that `["dialog", "details"]` in the above code snippet should be `["DIALOG", "DETAILS"]`, as `element.tagName` [returns an all-uppercase string](https://developer.mozilla.org/en-US/docs/Web/API/Element/tagName) for non-SVG tag names.

**Comment by mendrik** [comment]
> I am unsure about this one because the server could also render it with `open` (or without), so ignoring the server updates to use what is on the client may be incorrect behavior. I think the best option for now until we have a comprehensive answer is to use the dom options and maintain the values yourself:

Problem with "open" attribute is that it does not support [css ::backdrop styling](https://developer.mozilla.org/en-US/docs/Web/CSS/::backdrop) unless it is opened with dialogEl.showModal(). and using phx-ignore works but than nothing inside of the dialog can be updated. tricky.

**Comment by Neophen** [comment]
yeah this basically kills the showModal state in the dom as it recreates the element, so things like animating out the element break.

**Comment by firestack** [comment]
I'm not using `<dialog>` currently, but I am using `<details open>` in HEEx, but I _currently_ want the client to control if it's open or closed. Because the closed state isn't preserved in DOM attributes, only copying attributes doesn't work for this. So instead I special cased this for `HTMLDetailsElement`'s using the [`HTMLDetailsElement` `open` property](https://developer.mozilla.org/en-US/docs/Web/API/HTMLDetailsElement/open)[^1].

```js
/**
 * Controls `<details>` state on the client when LiveView updates the DOM.
 *
 * ---
 *
 * Inspired and derived from
 * - https://github.com/phoenixframework/phoenix_live_view/issues/2349#issuecomment-1430720906
 * - https://github.com/phoenixframework/phoenix_live_view/issues/2349#issuecomment-2164802079
 *
 * and https://elixirforum.com/t/dont-collapse-details/54278
 *
 * @param {HTMLElement} fromEl
 * @param {HTMLElement} toEl
 */
function preserveDetailsOpenState(fromEl, toEl) {
	if (
		!fromEl instanceof HTMLDetailsElement &&
		!toEl instanceof HTMLDetailsElement
	) {
		return
	}

	toEl.open = fromEl.open
}
```

<details>
<summary>Usage</summary>

```js
dom: {
	onBeforeElUpdated: (fromEl, toEl) => {
		preserveDetailsOpenState(fromEl, toEl)
	},
},
```

</details>

[^1]: I've not looked into any possible interactions between this and the [`HTMLDetailsElement` `name` property](https://developer.mozilla.org/en-US/docs/Web/API/HTMLDetailsElement/name) and "radio button" like accordions.
