### ISSUE TITLE
Live uploads drag and drop stops working after selecting a file in the input dialog

### ISSUE THREAD

**Issue by LostKobrakai** [phoenixframework/phoenix_live_view#2392]
### Environment

* Elixir version (elixir -v): 1.14.0
* Phoenix version (mix deps): 1.17.0-rc.1
* Phoenix LiveView version (mix deps): 0.18.4
* Operating system: Mac OS
* Browsers you attempted to reproduce this bug on (the more the merrier): Firefox, Chrome
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no:

### Actual behavior

Using `phx-drop-target` on a live upload input (`max_entries: 1` allows for dropping in images and replaces previously dropped images if present. But using the file selection of the input to select an image further drag&drop attempts seem to no longer work.

### Expected behavior

Drag&Drop overwriting the to selected image anytime.

**Comment by mcrumm** [comment]
Hi @LostKobrakai, thanks for the report! I can confirm the bug exists and it is isolated to `max_entries: 1`.

The problem is with trying to unify the file input element with the drag and drop API. 

For instance, when **selecting a file from the input**, notice the text changes:


https://user-images.githubusercontent.com/168677/212199141-638ed876-065f-4d48-8558-1605dcb45d4b.mov

...and from **drag and drop** it does not:


https://user-images.githubusercontent.com/168677/212199273-ad7e468d-1455-4c29-9100-2150debf1404.mov


The problem arises when `max_entries: 1` because the selected file is retained on the input. First the drop event occurs and updates the internal file list, then the input event is executed and the dropped file is overwritten with the file from the input.

**Comment by mcrumm** [comment]
I think I have a fix, stand by :)
