### ISSUE TITLE
attr and slot functions for LiveComponent?

### ISSUE THREAD

**Issue by alexcastano** [phoenixframework/phoenix_live_view#2407]
Hello,

I'm working on migrating the live view dashboard to the new Phoenix.Component: https://github.com/phoenixframework/phoenix_live_dashboard/pull/394

I realized that most of the code of LiveComponents are related to validations attributes or slots, ie: https://github.com/phoenixframework/phoenix_live_dashboard/blob/master/lib/phoenix/live_dashboard/components/nav_bar_component.ex#L16-L168

AFAIK we cannot use `attr` or `slot` macros in a LiveComponent, but I think it could reduce a lot of code for these components. Do you have any plans to add them? What are the difficulties you think may arise? May I help?

Thank you

**Comment by alexcastano** [comment]
Yes, for sure! Now we have a much better base to build components. 

I found very helpful the `attr` and `slot` macros to create functional (based on simple functions) components. Doing more complex components based on `LiveComponent` I'm missing these macros for default values, for validation and for default values. All these components are doing this all the time. For this reason I opened the ticket. I'm not sure the reason why these macros are only for functional components.

**Comment by connorlay** [comment]
One of the considerations when it comes to `attr` and `slot` for Live Components is how assigns can be updated with [`Phoenix.LiveView.send_update/3`](https://hexdocs.pm/phoenix_live_view/Phoenix.LiveView.html#send_update/3). We don't currently provide any runtime validation for declarative attributes and slots, so one could change the assigns in a Live Component at that deviate from what `attr` and `slot` declare the expected assigns to be.

**Comment by alexcastano** [comment]
I didn't think about runtime or compilation time validations. It's interesting.

Maybe for Live Components can have both validations at runtime and at compilation time. Runtime validations can be executed just before run `update` callback. They will be useful because we are doing this kind of validation on `update/2` anyway!

So Live Components and Phoenix Components have same syntax for these macros but no exactly the same behavior.

Of course, it is a suggestion. I think it would make sense. It's strange to have these useful macros on Phoenix Components and not on Live Components.

**Comment by josevalim** [comment]
I am fine with compile-time only validation. It will provide large benefits and with type systems work the types are only going to get better.

**Comment by chrismccord** [comment]
It is more nuanced than compile/runtime. The biggest issue is the distinction between the assigns you pass to `<.live_component />` and those that are actually assigned in `update/2`. It seems like the most valuable thing to have is the caller gets checks for the `<live_component />` arguments, but you also have the assigns in the LC itself that need to be properly mapped to the render/1 function, so which is declared? Both? Also as Clay mentioned `update/2` can have any number of clauses and accepts updates from both `<.live_component` and `send_update` is it's not immediately clear how attr/slot fits into LC cleanly.

**Comment by dvic** [comment]
And what about using separate macros for *properties* (`prop`) and *data* (`data`)? (like Surface)


Then `prop` is only for `<.live_component />` while `data` can be for setting default assigns and runtime validation of assigns after the update callback.

**Comment by alexcastano** [comment]
I like the idea to start with only compile-time validation. It would be easier to implement because a lot of work has already been done.

Anyway, let me argue in favor of runtime validations just for future reference:

> The biggest issue is the distinction between the assigns you pass to `<.live_component />` and those that are actually assigned in `update/2`. It seems like the most valuable thing to have is the caller gets checks for the `<live_component />` arguments, but you also have the assigns in the LC itself that need to be properly mapped to the render/1 function, so which is declared? Both?

IMHO I think we should declare the former because it is the real input for the component. The result of the `update/2` callback seems more like an implementation detail that should not be important for the caller. But maybe there's something I'm missing.

> Also as Clay mentioned `update/2` can have any number of clauses and accepts updates from both `<.live_component` and `send_update` is it's not immediately clear how attr/slot fits into LC cleanly.

Sorry, I don't understand this problem clearly. At the end of the day, both ways call `update/2` callback; so can't we just call a function to validate the assigns before passing to the `update/2` callback? Or am I missing something here? This function can crash if validations fail. It is better to crash with an understandable and clear message than a random crash message.

I can see a small problem with the `required: true` validation. This validation should only be executed when mounting the LC, but not for future updates. At first sight, it seems something possible to do.

@dvic I don't have enough experience with Surface to have an opinion about it 😅  Let's see what other people think

---

If you agree with at least compile-time validation I can give it a try. I don't know if I will have enough capacity to do it, I have never looked at the LiveView code in depth.

**Comment by alexcastano** [comment]
Hello again!

Not sure if you still think it is a good or a bad idea. In Phoenix Dashboard we "solved" the situation creating "function components" that internally call to `live_component`: https://github.com/phoenixframework/phoenix_live_dashboard/blob/a806655bc473e42cf18ed5e8a814c37f1a5ce039/lib/phoenix/live_dashboard/page_builder.ex#L297-L339

This way, we have attributes/slots validations, default values and documentation in live components. I think this is something good. However, the problem is that if we modify the live component we can forget to update our "function component". Related code should be close. I still see the gap between function and live components.

Feel free to close the issue if you think so :)

**Comment by chrismccord** [comment]
This isn't planned at the moment because the state + render model doesn't quite fit 1:1 with declarative assigns. We may revisit this in the future

**Comment by dlindenkreuz** [comment]
I keep running into the limitation that LiveComponent doesn't support declared attrs or slots. Right now, the [docs around attributes](https://hexdocs.pm/phoenix_live_view/1.2.9/Phoenix.Component.html#module-attributes) do not even explicitly state that `attr` does **not** apply to live components, they only ever mention "function components". Then again, it seems to be possible to use `attr` with live components to define default values but that's inofficial and [can cause weird bugs](https://github.com/phoenixframework/phoenix_live_view/issues/2358)…

This issue was created when the edges were still rough and v0.18 was the latest version, now we're at v1.2.9. Is there a plan to improve the DX around this or did I miss something? Would be great to get more clarity around this bread-and-butter topic.

**Comment by SteffenDE** [comment]
This might only need a doc change. You can define a function component that calls your live_component for you and use attr and slots on that one, passing all `{assigns}`. I know the DX is still not optimal, but I think it’s the best we have at the moment and usually good enough.

**Comment by dlindenkreuz** [comment]
A doc change would definitely help.

Personally, I'd understand this better if these things were clear:
- Why are declarative attrs and slots not applicable? Is it because live components can be updated manually using `send_update`?
  - If so: `send_update` updates `assigns`, which cover both internal state and "external" attrs. Can `send_update` even modify slots?
  - How does this play out with `<.live_component module={FooComponent} id="..." foo="bar" />`? Even without declarative attrs, we can't rely on `foo` always being `"bar"` because a stray `send_update` somewhere else in the codebase may have overwritten it.
  - Side note: Maybe `send_update` would be easier to understand if it only allowed sending assign keys that are not attrs? Or sending generic messages that behave more like `handle_info`, decoupled from the internal `assigns`?
- With declarative `attr :foo, :any`, I can ensure that accessing `assigns.foo` never raises a KeyError. I can also define default values. If declarative attrs are not recommended for live components, how can I achieve the same?
  - `assign_new(socket, :foo, fn -> nil end)` imho is very verbose and, when added to the `update(assigns, socket)` callback, usually needs `assign(socket, assigns)` as well which is a pitfall (forgetting this means no attrs are available in assigns)

There's some confusion in the community (there might be more threads):
- https://forum.elixirforum.com/t/how-to-use-slots-in-live-component/53828
- https://forum.elixirforum.com/t/passing-a-struct-to-assigns-for-a-livecomponent-good-idea-or-not/57907
- https://forum.elixirforum.com/t/are-live-components-ever-getting-props/66845
- https://forum.elixirforum.com/t/how-do-you-verify-assign-propagation-when-updating-a-widely-used-livecomponent/75030
- https://forum.elixirforum.com/t/unable-to-run-update-in-livecomponent/66316
- https://forum.elixirforum.com/t/patterns-for-refreshing-live-component-state-in-response-to-events/64056
  > I don’t like the idea of the caller literally settings assigns that it shouldn’t otherwise know about, but I did consider exposing a function from the live component module that could be called in the live view’s handle_info callback.

I understand that LiveView is modeled around Elixir processes and - sort of - needs to work the way it does right now. Then again, the community produced projects like [Surface](https://github.com/surface-ui/surface), [LiveProps](https://github.com/mbreuer23/phoenix-live-props) and [Lavash](https://github.com/u2i/lavash/tree/main) to unify these internal discrepancies. They provide high-level solutions that devs are familiar with from popular component-based view libs like React and Vue. To me, this + the recurring questions in the community are a signal that LiveView's abstractions currently don't work how developers intuitively expect them to.

**Comment by SteffenDE** [comment]
@dlindenkreuz live components are mostly the way they are because they were the first way to define components in LiveView. Function components and declarative assigns came later. As mentioned above, it is not clear how to best design this and ensure it feels consistent with `send_update`, etc.

> Why are declarative attrs and slots not applicable? Is it because live components can be updated manually using send_update? 

Mostly, yes. That said, you can get compile time validation by wrapping `<.live_component>` in a function component and define attrs and slots on that.

```elixir
attr :id, :string, required: true
attr :open, :boolean, required: true

slot ...

def live_modal(assigns) do
  ~H"""
  <.live_component module={MyAppWeb.ModalComponent} {assigns} />
  """
end
```

> If so: send_update updates assigns, which cover both internal state and "external" attrs. Can send_update even modify slots?

Technically, you could overwrite a slot. A slot is just an assign. There is no API for you to define a slot outside of HEEx though, so in practice you would never do that.

> How does this play out with <.live_component module={FooComponent} id="..." foo="bar" />? Even without declarative attrs, we can't rely on foo always being "bar" because a stray send_update somewhere else in the codebase may have overwritten it.

You can't rely on it. If foo always has to be `bar`, you could add an update clause that raises if you try to update it, but it's probably not a useful example.

```elixir
def update(%{foo: ...}, socket) do
  raise "foo cannot be updated"
end
```

> Side note: Maybe send_update would be easier to understand if it only allowed sending assign keys that are not attrs? Or sending generic messages that behave more like handle_info, decoupled from the internal assigns?

We cannot change how `send_update` works. A send_message or similar could work though.

> With declarative attr :foo, :any, I can ensure that accessing assigns.foo never raises a KeyError. I can also define default values. If declarative attrs are not recommended for live components, how can I achieve the same? 

As mentioned, you can wrap your live component in a function component and get most of those benefits, assuming you don't do arbitrary send_updates that then later mess with those assigns.

> I understand that LiveView is modeled around Elixir processes and - sort of - needs to work the way it does right now.

As mentioned in the beginning, Live Components are mainly the way they are because they were designed like that in the past. And since LiveView is stable now, we can't easily change how they work. If we designed stateful components from scratch, we'd probably do it differently today. That would need some serious effort though and it's not really our focus at the moment. One interesting approach I've seen is to use hooks instead of live components.

If you're struggling with specific things, I'd recommend to open a thread [in the forum](https://forum.elixirforum.com/) (you can ping me). Depending on what you're trying to do, LiveComponents might or might not be the best way to achieve your goals. And the docs can always be improved for sure.
