### ISSUE TITLE
Feature request: Context

### ISSUE THREAD

**Issue by AHBruns** [phoenixframework/phoenix_live_view#2445]
As live views grow, pervasive state such as query params end up getting prop drilled. This makes for more developer work. I think this library should help by providing a way for live views and components to expose their assigns to all their descendants implicitly. Additionally, access to these assigns should be tracked so that when they change only sub-trees which uses them get re-diffed.

React, Vue, Svelte, and Angular all eventually implemented a version of this feature, and none their reasoning was JS or browser specific. Additionally, a version of this feature (without some of the possible performance optimizations) has already been implemented in Surface UI, https://surface-ui.org/contexts.

**Comment by josevalim** [comment]
Hi @AHBruns,

We are familiar with contexts but we still want to push the envelope a bit and understand how far we can get without them. That's because Elixir code allegedly has the same problem: you can have several nested functions and you need to pass information deep inside, but so far Elixir developers managed to solve those problems without introducing a context API in Elixir itself.

For example, in Elixir we can address it with anonymous functions, which mirrors blocks and slots in HEEx. LiveComponents are a stateful option that naturally work as checkpoints of state. In the worst case scenario, you can create your own `@context` map that you pass around, passing a single assign, instead of multiple.

I am aware it is not a perfect analogy, but I hope it shows where our heads are at. We may come back and revisit this, but it would be only after v1.0 is out.

**Comment by AHBruns** [comment]
@josevalim, I'm happy to accept that this may not end up making it into the framework. However, I do want to point out that the comparison with deeply nested function calls is actually quite useful because I would argue Elixir _does_ have a context API. Global state! Just like how JS devs stick stuff on the window, Elixir devs stick stuff in well known Agents or ETS tables when they want to share it in lots of places. After all, what is Application.get_env/2 if not a context API?

The question is why, if all these languages have language level "context APIs" they reimplement it in their frameworks. I believe it's because components have more constraints than functions. Specifically, they need to know which state they're using and when it changes to trigger re-renders. Which you can't do unless you get your state in a known way (assigns).

Interestingly, now that Recat has introduced a first class way to subscribe to external state via useExternalStore context usage is declining and is generally seen as a poor practice. So, maybe there's a discussion to be had about allowing live view components to use external stores? send_update is relative close, but misses because while there's a way to register a component when it mounts and there's no way to unregister it when in unmounts.

Anyway, obvious counter example to the "languages actually do have context APIs" argument is purely functional languages like Haskell which have no concept of global state. In my experience they solve this by hiding context in a monad. This is usually called the state monad.

Implementing a state monad based solution for components in user space would be a total non-starter as it'd require the entire eco-system to adopt the convention of passing an opaque state assign around. Any library that didn't would just be unusable because it'd break the chain. Also, you'd need to write macros to make it non-tedious which would be I think might be hairy since they'd have to expand to a shape that live view could track changes on correctly.

However, it would be relatively easy for the framework to "suck" this state in whenever it renders a component, and make it implicitly accessible. This is, actually exactly how implicits would in Scala. Change tracking would stay the same, just with an extra implicit assign.

My point is just that components have fundamental constraints that functions don't, and while composition via slots can help in certain situations it doesn't address the fundamental problem. All that being said, I can also appreciate that I may be missing something important. Thank you for you time and quick response. Also, sorry for any typos. I'm on my phone.

**Comment by josevalim** [comment]
Although Elixir has facilities for global state, I disagree they are equivalent to the context. The global state in Elixir is mostly used with the explicit purpose of _sharing data between processes_ (which you did mention) but that is clearly not the case with contexts.

To be more precise, if anyone were to write this code:

    agent = Agent.start_link(__MODULE__, fn -> data end)
    some_function(agent)

where:

    def some_function(agent) do
      data = Agent.get(__MODULE__, & &1)
      # do something with data
    end

It would most likely be rejected in most code reviews, because those tools are almost never used to pass data within the same process (and, if you were to do that, the process dictionary would likely be the best-worst tool :D).

Even when it comes to `Application.get_env/3`, the most idiomatic usage is always about reading those values at the surface of your program, rather than scattered around. For example, I would read the application environment when starting the supervision tree, and then keep that as an explicit part of the state. Still then, the configuration data is coming from a separate location than the entity reading it.

On the other hand, contexts are about implicitly passing information _to functions we are going to call ourselves_, and I don't believe Elixir has anything idiomatic in relation to that. 

In any case, I understand the need for the feature, there are [other cases where I considered implicit passing state araound](https://elixirforum.com/t/introducing-for-let-and-for-reduce/44773/121) but it is still pretty far from being a consensus. :)

Thanks for the convo!
