### ISSUE TITLE
Docs for "Disconnecting all instances of a live user"

### ISSUE THREAD

**Issue by ghenry** [phoenixframework/phoenix_live_view#2465]
Hi all,

I think [this part](https://hexdocs.pm/phoenix_live_view/security-model.html#disconnecting-all-instances-of-a-live-user):

> Luckily, it is possible to address this by setting a live_socket_id in the session. For example, when logging in a user, you could do:

```
conn
|> put_session(:current_user_id, user.id)
|> put_session(:live_socket_id, "users_socket:#{user.id}")
```

then says:

> Now all LiveView sockets will be identified and listen to the given live_socket_id. You can then disconnect all live users identified by said ID by broadcasting on the topic:

`MyAppWeb.Endpoint.broadcast("users_socket:#{user.id}", "disconnect", %{})`

shouldn't this be:

`MyAppWeb.Endpoint.broadcast(live_socket_id, "disconnect", %{})`

for example:

```
  def logout(conn, _params) do
    if live_socket_id = get_session(conn, :live_socket_id) do
      SentrypeerWeb.Endpoint.broadcast(live_socket_id, "disconnect", %{})
    end
```

like in `user_auth.ex`:

  https://github.com/phoenixframework/phoenix/blob/bd3ce365dcb1e134e874a86997dfaf35f26ea048/priv/templates/phx.gen.auth/auth.ex#L77

**Comment by chrismccord** [comment]
They are both valid because you are rebuilding it by hand vs fetching it from the session. The current one is more broadly usable because you could kick user from anywhere in the app outside the context of the user's request (the conn), which would be used for admins kicking a user or revoking logins, etc. The `logout` approach from using the value in the session is nice for invalidating all sessions on logout click by the current user. If you'd like to discuss both in the docs, please send a PR. thanks!
