### ISSUE TITLE
Support enforcing single slots

### ISSUE THREAD

**Issue by viniciusmuller** [phoenixframework/phoenix_live_view#2495]
Currently, as far as I know there is no way to enforce that slots cannot be repeated by the caller.

Given the following code:

```elixir
  slot :header
  slot :content
  slot :footer

  def card(assigns) do
    ~H"""
      <div style="max-width: 400px">
        <div class="header">
          <%= render_slot(@header) %>
        </div>

        <hr>

        <div class="content">
          <%= render_slot(@content) %>
        </div>

        <hr>

        <div class="footer">
          <%= render_slot(@footer) %>
        </div>
      </div>
    """
  end
```

This is possible:

```elixir
<Components.card> 
  <:header>
    <h1>I'm a header!</h1>
  </:header>
  <:header>
    <h1>Two headers?!</h1>
  </:header>
  <:content>
    <p>My Component</p>
  </:content>
  <:footer>
    <a href="my.company">link to my company</a>
  </:footer>
</Components.card> 
```

The only way to enforce that a use cannot abuse the component API and pass multiple "content" or "footer" slots is to do this validation inside the component, complicating the code and leading to runtime errors.

Would it be possible to have a option for slots where the API would look like 

```elixir
slot :header single: true
slot :content, single: true
slot :footer single: true
```

and a compilation error would be thrown if it were violated by passing more than a single specific slot

**Comment by chrismccord** [comment]
I'm not sure on this one since slots are collections by default, and if the caller passes two headers, they'd be rendered "correctly". If the caller only wants one header, they should only specify one, so I don't see this as an essential compile-time issue. Note the component can also runtime check if you really wanted it, but I'd need to see more of a problem of this in the wild before adding the feature. Thanks!
