### ISSUE TITLE
Global attrs are always dasherized

### ISSUE THREAD

**Issue by jonatanklosko** [phoenixframework/phoenix_live_view#2545]
```
<div phx-value-what_ever="1" {[{:"phx-value-what_never", 2}]}>
  Test
</div>
```

becomes

```
<div phx-value-what_ever="1" phx-value-what-never="2">
```

---

In other words, this leads to inconsistency between HTML and custom components:

```
<div foo_bar="1" /> (kept as is)

<.my_div foo_bar="1" /> (dasherized when passed as global)
```

**Comment by jonatanklosko** [comment]
This comes from `Phoenix.HTML` [here](https://github.com/phoenixframework/phoenix_html/blob/cf704e4e14b06167ed85635af14cbabc6569d59c/lib/phoenix_html.ex#L316-L317).

It's been like that since day one, but seems leads to this unexpected behaviour. @josevalim thoughts?

**Comment by josevalim** [comment]
The behaviour dates back to Phoenix.HTML where everything was atoms:

    content_tag :div, phx_target: @myself

Should emit:

    <div phx-target="123">

So I think the behaviour for Phoenix.HTML is correct. The question is if Phoenix LiveView wants to preserve this behaviour or not.

Note string keys are not dasherized.

**Comment by jonatanklosko** [comment]
Ah that makes sense, would it be too expensive to convert atom keys to strings here?

https://github.com/phoenixframework/phoenix_live_view/blob/d783c1c54e1266107a2e6bba1563179dd8af033c/lib/phoenix_live_view/tag_engine.ex#L835-L842

**Comment by josevalim** [comment]
@jonatanklosko what is the use case btw? can you provide more context? Why was it given in a splat?

**Comment by jonatanklosko** [comment]
Sounds good, I will PR!

**Comment by crbelaus** [comment]
This change has bitten my team when upgrading from Phoenix LiveView 0.18.18 to 0.20.x.

This broke backwards compatibility in a way that is not mentioned in the changelog so we had a very hard time understanding why some parts of our application were not working well and then it took a while to find out the relevant code that changed the behaviour.

I've initially opened [a thread in ElixirForum](https://elixirforum.com/t/phoenix-components-attributes-dont-replace-underscores-with-dashes-anymore/59618) asking about this. This was before we were able to find out where this is coming from.

We are using HTMX and we have multiple components that require the same attributes so there are many places in which we generate the common attribute keyword list and then pass it to the relevant HTML components.

In Phoenix Liveview 0.18 the underscores were dasherized but this stopped happening on Liveview 0.20.

```
<div {[hx_get: ""]}></div>

# In Phoenix LiveView 0.18.18 this renders:
<div hx-get=""></div>

# But in Phoenix LiveView 0.20 this renders:
<div hx_get=""></div>
```

I am aware that Phoenix LiveView is pre 1.0 so breaking changes are expected. On the other hand every new Phoenix project created with the Phoenix stable version depends on LiveView so this breaking changes affect many projects that didn't explicitly chose to use a < 1.0 library.

This change is particularly hard to adapt to because there is not deprecation notice during compilation that points you to use `func_a` as a replacement of `func_a`.
Instead we would have to check every place that renders HTML (templates, views, HTML modules, components), find every `_` usage and modify it accordingly.

In big projects (ours has thousands of templates and hundreds of views) this is unfeasible to do in a reasonable time and, even if we do it, it is still very brittle as any omission may cause trouble down the road.

I would like to ask reconsidering this decision as it can silently break many applications that will keep working but don't behave as expected.

**Comment by josevalim** [comment]
Reverting it back will just compound the problem, because now those started on v0.19+ will have similar issues. Plus this change is pretty much intentional, as it makes what is written in the tag what you get. v0.20 is our last step before 1.0, so the last opportunity to get these changes in. If it could be clearer in the CHANGELOG, PRs are definitely welcome.
