### ISSUE TITLE
Add :time option to JS.dispatch

### ISSUE THREAD

**Issue by viniciusmuller** [phoenixframework/phoenix_live_view#2550]
It would be nice to have a `:time` option in `JS.dispatch`, so that the event would only be fired after `:time` milliseconds.

Some use cases would be sending a destroy event for a modal component cleanup after a certain time or closing a toast component after X seconds.

A workaround that is currently possible, is to use `JS.hide/show` in a template element and use the `phx:show-start` or `phx:show-end` events to do this, but this is a workaround and doing so hides the code's real intent.

**Comment by chrismccord** [comment]
You can accomplish this by picking up the dispatch in your own event listener and doing the timeout + execution there. The issue with doing it for things like hiding toasts is you want to cancel the hide if the user is current interacting with the toast (like mouse over), so I don't think it's enough to call it a defacto feature. Thanks!

**Comment by thiagomajesk** [comment]
Hi @chrismccord!  I think there's a valid use case here...  

We are building some kind of  "Headless UI" library for Phoenix over here: https://github.com/thiagomajesk/swish/tree/master/lib/swish. This library has a custom-made Portal implementation that we use to correctly position elements. This means that all Portals need to have an attribute `phx-hook="Swish.Portal"` by default.

Our toasts implementation will use this Portal in the future, and since we can't have multiple `phx-hook` defined for them, we need a way to actually close them after X amount of time using commands. 

We want to be able to close a Toast Portal after X milliseconds and we can't push the timeout code to the Portal implementation because it has its own cleanup logic already.

Right now, we can only call the `hide` on click like `phx-click={hide(@toast)` and want to be able to: `phx-mounted={show(@toast) |> hide(@toast, 5000)}`; so it gets dismissed 5 seconds after shown. It's also important that this can be parametrized by the user, so we need to be able to specify while building the `JS` command.

There are also other use cases like waiting for a DOM element to be available to receive the event. 
For instance, we use a `template` tag to represent Portals. When we dispatch, it goes very fast over the wire and the element may not yet "exist" in the DOM yet. If we do this on the client side, it might not get processed in the right order and which causes all sorts of race conditions.

Also, we used to wait for animations to be played in our dialog implementation to passively close it. However, since we don't have any guarantees when the first event for 'transitionstart' or 'animationstart' will be dispatched to the browser (after JS.hide for instance), it gets tricky. It would be easier to rely on the execution order from the command itself: `JS.hide() |> JS.dispatch("now-im-finished", 5000)`.

**Comment by thiagomajesk** [comment]
Just to document since it was a major pain point back in the day... 
A portal component was published with the latest [LiveView 1.1](https://github.com/phoenixframework/phoenix_live_view/blob/v1.1/CHANGELOG.md#portal-component) 👏.
