### ISSUE TITLE
`phx:page-loading-stop` does not get triggered when `push_patch` is used

### ISSUE THREAD

**Issue by bumpah** [phoenixframework/phoenix_live_view#2559]
### Environment

* Elixir version (elixir -v): `Elixir 1.14.3 (compiled with Erlang/OTP 25)`
* Phoenix version (mix deps): `1.7.2`
* Phoenix LiveView version (mix deps): `0.18.18`
* Operating system:`macOS Ventura 13.2.1`
* Browsers you attempted to reproduce this bug on (the more the merrier): `Version 111.0.5563.110 (Official Build) (arm64)`
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: `Yes`

### Actual behavior

Phoenix JS `phx:page-loading-stop` event listener does not get triggered when `push_patch` is used, like it does with using `<.link patch />` -component.
Cause of this updating DOM on `phx:page-loading-stop` event listener can have different and unexpected behaviour when used together.

Single file app to reproduce - [bumpah/debug-phoenix-js](https://github.com/bumpah/debug-phoenix-js)

### Expected behavior

I would expect both of the methods `push_patch` and `<.link patch />` to work in similar way and trigger `phx:page-loading-stop`. On the [single file app](https://github.com/bumpah/debug-phoenix-js) I would expect `<i id="current-query-params" />` element to always have text content of the current url, whether text input or link is used to update url.

**Comment by CoderDennis** [comment]
I did some investigation on this. The issue is that in the file `assets/js/phoenix_live_view/view.js` the function `onLivePatch` calls `this.liveSocket.historyPatch` which does not internally use the `withPageLoading` function. The similar function `onLiveRedirect` (which is just above `onLivePatch`) calls `this.liveSocket.historyRedirect` which DOES use `withPageLoading` internally.

Adding the `withPageLoading` wrapper to the code in `view.js` felt like the wrong way to solve the issue. The `historyPatch` function in `live_socket.js` is already wrapped inside calls to `withPageLoading` elsewhere, so adding it again inside that function wouldn't make sense either.

**Comment by enewbury** [comment]
https://github.com/phoenixframework/phoenix_live_view/blob/5a625b653ea1259847fe556ed170ec2b9ae548e3/assets/js/phoenix_live_view/live_socket.js#L749-L782

Noting the code in question here.  The "pushHistoryPatch" function is used when we click on a <.link> component, and does include the `withPageLoading` helpers. This makes sense because this is initiated on the client, and can immediately emit `page-loading-start` and then when the response returns from the server we can emit `page-loading-stop`.
In the case of `push_patch` it is initiated server side, so we just get a message on the channel "live_patch". This triggers a call to `liveSocket.historyPatch`, which as noted above, doesn't use any loading helpers.

The right thing to do isn't entirely clear to me. We could simply emit a `page-loading-start` immediately followed by `page-loading-stop` but that doesn't really give us much information. I assume we aren't interested in capturing when the "diff" message is received since that is a completely separate event as far as I understand, and I also believe that isn't accounted for in the client-side initiated patch.

**Comment by chrismccord** [comment]
If the server pushes a patch, there is "loading" event in the first place, so I don't think this is something we need to address via loading states. I was going to tell you to listen for the pushstate event but it turns out the browser has no such thing because JavasScript.  I have added a lower level `phx:navigate` event you can listen for to detect any URL change. Thanks!
