### ISSUE TITLE
Sigil ~p breaks url encoded params

### ISSUE THREAD

**Issue by sergiotapia** [phoenixframework/phoenix_live_view#2599]
### Environment

* Elixir version (elixir -v): 1.14.4
* Phoenix version (mix deps): 1.72
* Phoenix LiveView version (mix deps): 0.18.18
* Operating system: Linux
* Browsers you attempted to reproduce this bug on (the more the merrier): Brave

### Actual behavior

Using `~p` with query parameters, make the url break. In the browser, the URL looks like this:

http://localhost:4000/?name%3Dthe%2Bmatrix%26page%3D1%26page_size%3D20%26sort_by%3Dseeders%26sort_dir%3Ddesc

So my `handle_params` would break and consider the entire URL parameters as one string like:

```
def handle_params(params, _uri, socket) do
  IO.inspect params
  # %{"foobar=asdf&bar=asdfasdf&baz=ijasdf" => ""}

  {:noreply, socket}
end
```

So for this to work, I had to use this:

```elixir
def handle_info({:update, opts}, socket) do
  params = merge_and_sanitize_params(socket, opts)
  query_params = URI.encode_query(params)
  path = "/?#{query_params}" # <----- no sigil ~p
  {:noreply, push_patch(socket, to: path, replace: true)}
end
```

And now the URL parameters are parsed properly into a map in `handle_params`.

### Expected behavior

I wanted to encode the filtering/sorting params but doing so broke sigil ~p. It seems if ~p is going to do the encoding itself, it should also allow maps to be used in the string.

Allow me to do this:

```elixir
def handle_info({:update, opts}, socket) do
  params = merge_and_sanitize_params(socket, opts)
  path = ~p"/?#{params}"
  {:noreply, push_patch(socket, to: path, replace: true)}
end
```

**Comment by chrismccord** [comment]
Looks like you are double encoding the query string. ~p accepts a map and encoded for you, so ditch encoding yourself and you should be good. We should raise if we get a binary i think. Sent from my iPhoneOn Apr 20, 2023, at 10:51 PM, Sergio Tapia ***@***.***> wrote:﻿
Environment

Elixir version (elixir -v): 1.14.4
Phoenix version (mix deps): 1.72
Phoenix LiveView version (mix deps): 0.18.18
Operating system: Linux
Browsers you attempted to reproduce this bug on (the more the merrier): Brave

Actual behavior
Using ~p with query parameters, make the url break. In the browser, the URL looks like this:
http://localhost:4000/?name%3Dthe%2Bmatrix%26page%3D1%26page_size%3D20%26sort_by%3Dseeders%26sort_dir%3Ddesc
So my handle_params would break and consider the entire URL parameters as one string like:
def handle_params(params, _uri, socket) do
  IO.inspect params
  # %{"foobar=asdf&bar=asdfasdf&baz=ijasdf" => ""}

  {:noreply, socket}
end

So for this to work, I had to use this:
def handle_info({:update, opts}, socket) do
  params = merge_and_sanitize_params(socket, opts)
  query_params = URI.encode_query(params)
  path = "/?#{query_params}" # <----- no sigil ~p
  {:noreply, push_patch(socket, to: path, replace: true)}
end
Expected behavior
I wanted to encode the filtering/sorting params but doing so broke sigil ~p. It seems if ~p is going to do the encoding itself, it should also allow maps to be used in the string.
Allow me to do this:
def handle_info({:update, opts}, socket) do
  params = merge_and_sanitize_params(socket, opts)
  path = ~p"/?#{params}"
  {:noreply, push_patch(socket, to: path, replace: true)}
end

**Comment by sergiotapia** [comment]
Thanks @chrismccord this worked out fine.

```elixir
def handle_info({:update, opts}, socket) do
  params = merge_and_sanitize_params(socket, opts)
  # `params` is a map.
  path = ~p"/?#{params}"
  {:noreply, push_patch(socket, to: path, replace: true)}
end
```
