### ISSUE TITLE
Heex should join lists into attributes with a separator when using non-class attributes

### ISSUE THREAD

**Issue by sevensidedmarble** [phoenixframework/phoenix_live_view#2604]
Hi there,

The current behavior you get when passing a list to an attribute in heex is like this:

Say you have a list like `tags = ["news", "culture", "society"]` that you pass into an input like:

```
~H"""
  <input value={tags} />
"""
```

You'll get something like:

```
<input value="newsculturesociety" />
```

I think a more useful default would be to make lists joined with a space by default, like:

```
<input value="news culture society" />
```

Not all attributes seem to act this way. Class for instance, does the behavior I describe here. I think it would make the most sense if other attributes behaved the way class does here, considering the pattern of space-delineated lists in attributes is somewhat idiomatic in html.

**Comment by josevalim** [comment]
The current behaviour is pretty much intentional and changing it would be a breaking change. in Elixir we have this concept of IO data where, if you want to add a prefix to strings, you could do `["prefix" | string]` instead of `"prefix" <> string` and skip the string concatenation (which would copy strings). Only classes are an exception because we know concatenating with spaces is safe (something we can't do for IDs, for example).
