### ISSUE TITLE
LiveView disconnects when clicking a download link

### ISSUE THREAD

**Issue by krns** [phoenixframework/phoenix_live_view#2733]
### Environment

* Elixir version (elixir -v): 1.14.3
* Phoenix version (mix deps): 1.6.16
* Phoenix LiveView version (mix deps): 0.19.4
* Operating system: Linux
* Browsers you attempted to reproduce this bug on (the more the merrier): Brave (Chrome)
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Actual behavior

```elixir
defmodule Test.TestLive do
  use Phoenix.LiveView

  def mount(_params, _session, socket) do
    {:ok, assign(socket, count: 0)}
  end

  def render(assigns) do
    ~H"""
    <div>
      <h1>Count: <%= @count %></h1>
      <button type="button" phx-click="increment">increment +</button>
    </div>
    <a href="https://test-live-view.fra1.digitaloceanspaces.com/test.csv">Download</a>
    """
  end

  def handle_event("increment", params, socket) do
    {:noreply, assign(socket, count: socket.assigns.count + 1)}
  end
end
```

https://github.com/phoenixframework/phoenix_live_view/assets/7387295/f1d985c0-4761-4410-8351-83def2748ad8

### Expected behavior

The LiveView should still work.

**Comment by krns** [comment]
Please let me know if you can reproduce the error so I can delete the DigitalOcean Space (S3). Thanks!

**Comment by 03juan** [comment]
Clicking on a link in a webpage initiates a navigation process, which discards the current page and its resources, including WebSocket connections. This happens because WebSockets are tied to the page that created them, and are closed when the page is unloaded. To avoid disconnecting the WebSocket in your case, the link can be modified to download the file or open it in a new tab, both of which will keep the current page and its WebSocket connection active.

`<a href="/path/to/file.csv" download>Download CSV</a>`

`<a href="/path/to/file.csv" target="_blank">Download CSV</a>`

**Comment by krns** [comment]
Thanks! I also just found https://github.com/phoenixframework/phoenix_live_view/pull/2611 which adds support for the `download` attribute which will solve my problem.

Opening the file in a new tab is not an option because of the bad UX.

**Comment by 03juan** [comment]
Good to know it's fully supported in LV from v0.19.0. Thanks!
