### ISSUE TITLE
How do I get diagnostics for a component that doesn't exist via `Code.compile_quoted` or `Code.eval_quoted`? 

### ISSUE THREAD

**Issue by scottming** [phoenixframework/phoenix_live_view#2777]
I am currently supporting real-time compilation for HEEx, but I don't know how to obtain diagnostics for the following two scenarios(Note: that they can be thrown by `mix compile` on save file.):

1. When a function component does not exist.
2. When dealing with the `~p` block.

Furthermore, in this [pull request](https://github.com/lexical-lsp/lexical/pull/323), I have attempted four different compiling or evaluating methods, making the code quite complex. Is there a simpler approach available?

**Comment by josevalim** [comment]
Hi @scottming, I don't understand why those functions need special handling. They are Elixir macros, so as long as you execute the code as Elixir macros, their diagnostics should go through the Elixir apparel that you already have to collect warnings.

**Comment by scottming** [comment]
Hi, @josevalim thanks for your replying.

I think you mean that I should first [evaluate](https://github.com/phoenixframework/phoenix_live_view/blob/v0.19.5/test/phoenix_live_view/html_engine_test.exs#L7) and then [render](https://github.com/phoenixframework/phoenix_live_view/blob/v0.19.5/test/phoenix_live_view/html_engine_test.exs#L25), and collect the diagnostics using the existing collector in Lexical.

However, I've found that this approach doesn't solve all the problems. For example, if I change this [line](https://github.com/phoenixframework/phoenix_live_view/blob/fb111738d56745f37338867b9faea86eb9baa6e1/test/phoenix_live_view/html_engine_test.exs#L451)'s `compile` to `render`, I would get the following:

<img width="671" alt="CleanShot 2023-08-18 at 17 49 30@2x" src="https://github.com/phoenixframework/phoenix_live_view/assets/12830256/a1c5050b-6e3f-4e58-9d20-a795c4b15d0a">

So, how should I transform this [macro](https://github.com/phoenixframework/phoenix_live_view/blob/v0.19.5/test/phoenix_live_view/html_engine_test.exs#L32) into a function? I want it to accept a dynamic string.

```elixir
  defmacrop compile(string) do
    quote do
      unquote(
        EEx.compile_string(string,
          file: __ENV__.file,
          engine: Phoenix.LiveView.TagEngine,
          module: __MODULE__,
          caller: __CALLER__,
          source: string,
          tag_handler: Phoenix.LiveView.HTMLEngine
        )
      )
      |> Phoenix.HTML.Safe.to_iodata()
      |> IO.iodata_to_binary()
    end
  end
```

Forgive me. My understanding of Elixir macros is limited.

**Comment by josevalim** [comment]
What I mean is that you should not need any special addition to get warnings/errors from HEEx, because they use the same infrastructure as the Elixir compiler, and you already getting the warnings and errors from the Elixir compiler.

**Comment by josevalim** [comment]
That's what I am saying. You can't easily expand/execute ~H sigil because it assumes it is running inside the Elixir compiler, potentially inside a module and function, with all the context it carries. It is like trying to expand the "schema" macro in Ecto without having a module. The best way to expand the ~H sigil is by expand the whole module/file it belongs to.

For .heex files, you could also just expand the module that embeds them, however, that may not be obvious. But think about a directory with both foo.html.heex and bar.html.heex, where foo calls bar:

""" 
<.bar ...>
</.bar>
"""

The only reason why `.foo` finds `.bar` is because they are embedded in the same module. The module that embeds them may also define aliases, imports, and local functions used by foo.html.heex. So you can't really expand them without knowing where they are embedded.

Your best option is to have a heuristic that says page_html/foo.html.heex will be embedded by page_html.ex, and then you Code.compile_quote("page_html.ex") instead. That will give you the diagnostics for page_html as well as all heex templates and sigils.

**Comment by chrismccord** [comment]
Closing as this is not an issue on LiveView. Thank you!
