### ISSUE TITLE
Unauthorized live_redirect when using `live_render` inside a non-live view

### ISSUE THREAD

**Issue by zediogoviana** [phoenixframework/phoenix_live_view#2832]
### Environment

* Elixir version (elixir -v): 1.15.5-otp-26 (erlang 26.0.2)
* Phoenix version (mix deps): 1.7.7
* Phoenix LiveView version (mix deps): 0.20.0
* Operating system: MacOs 13.5.2
* Browsers you attempted to reproduce this bug on (the more the merrier): Firefox, Chrome
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Actual behavior

I'm rendering a live component inside a dead view using [live_render/3](https://hexdocs.pm/phoenix_live_view/0.20.0/Phoenix.Component.html#live_render/3).

An example of a partial `index.html.heex` file that is a non-live view, but renders a live component inside it. This component is pretty much a button that opens a modal.

```elixir 
<div>
  <.link navigate={~p"/"}>Return</.link>
  <span>Want to know more?</span>
  <%= live_render(@conn, MyAppWeb.CustomModalLive) %>
</div>
```

When viewing pages that have this `live_render` call, trying to click a `<.link />` or a table item from the default `MyAppWeb.CoreComponents`, doesn't happen anything (and these are not directly related to the live component). 

The browser console shows the following debug/error messages (but nothing on the iex)

<img width="1440" alt="Screenshot 2023-09-28 at 14 40 06" src="https://github.com/phoenixframework/phoenix_live_view/assets/25623039/b92ab612-8bc9-4af5-9531-ee10afba75e2">

### Expected behavior

When clicking the `<.link />` component, I get redirected to `/`. 

This worked with the previous version of `live_view` (0.19.5), and I'm not finding any changes regarding this specific function in the changelog for 0.20.0.

Thank you 😃

**Comment by chrismccord** [comment]
Live navigation is not supported outside of `live` routes in the router. You almost never want to live_render form the controller stack.

> This worked with the previous version of live_view (0.19.5)

This was never supported :)

**Comment by josevalim** [comment]
To be clear, if it worked, it was by accident. Officially it was never supported. :)

**Comment by zediogoviana** [comment]
Thank you both for the quick reply and Sorry, for the confusion!

Can you point me to how I can do this correctly? My pages are all non-live views, but in some specific cases, I need to add some "reactivity", like opening and closing some informational modals. I'd prefer to not convert these pages into fully live-view ones. Is this possible?

When reading the docs for `live_render` I thought it for use cases like this one 😅 

> When rendering a LiveView inside a regular (non-live) controller/view

**Comment by josevalim** [comment]
Use `<.link href={...}>` :)

**Comment by travelmassive** [comment]
Thanks for spotting this @zediogoviana — I am caught by this issue as well and can't upgrade to 20.0.

We use LV almost everywhere *except* our public-facing CMS (static pages such as about, etc) and moderator back-end.

We use live components for the navbar and account dropdown menu. 

This obviously worked until this support was dropped. I am unsure what to do? I have to either refactor a lot of code into LV, or duplicate my navbar and account menus and have non-liveview versions.

Given that the links contain a valid "href", I don't see why it makes sense to prevent the user from clicking the link? 

Screenshot below to demonstrate what I'm facing:

<img width="1297" alt="Screenshot 2023-09-29 at 2 25 56 pm" src="https://github.com/phoenixframework/phoenix_live_view/assets/8967051/621f3b66-0ff3-44dc-8723-b9033d4d7acc">

**Comment by josevalim** [comment]
Can you folks provide more context? You cannot render a LiveComponent outside of a LiveView anyway, so by definition you must have a LiveView on the page. A minimal app that reproduces this is welcome.

There are two possible issues here:

1. You are inside a LiveView and linking to a non-LiveView using `<.link navigate>`. This should not work and I don't believe we should fix this. Even if this worked before, it was inefficient, because we would try to reach out to the server to see if the new page was a LiveView, only to find out it wasn't.

2. You are inside a non-LiveView and you are linking to a LiveView using `<.link navigate>`. @chrismccord, in this case, I think we should make it work. I can see a menu being used both inside a LiveView and outside of one, and having to swap between href/navigate would be, at best, very annoying. Perhaps we can annotate when a LiveView is mounted at the router at the HTML level, and if we can't find a LiveView to redirect, we just href it, without going to the server.

**Comment by chrismccord** [comment]
> You are inside a non-LiveView and you are linking to a LiveView using <.link navigate>. @chrismccord, in this case, I think we should make it work.

this is how it works today. The client reaches out to the server and is told it is unauthorized and the client falls back to a full page request  (via window.location = …) which is what @zediogoviana screenshot shows. 

Given the info we have everything is working as intended. @zediogoviana are you saying the client logs that it is falling back but never actually makes the page request? We didn’t change the failsafe behavior but it’s possible something slipped in that prevents it. Note that this is only *failsafe* behavior and means all your links like this will incur a 2x RTT penalty so it’s not something you intentionally want to rely on.

**Comment by zediogoviana** [comment]
Hi everyone!

> Given the info we have everything is working as intended. @zediogoviana are you saying the client logs that it is falling back but never actually makes the page request?

Well, no log was ever displayed on the iex side, so I believe the page request never gets made.

I'll try to provide a minimal working app as @josevalim requested, as soon as possible. But pulling my original code snippet, my code was pretty much something like this:

```
<div>
  <.link navigate={~p"/"}>Return</.link>
  <span>Want to know more?</span>
  <%= live_render(@conn, MyAppWeb.CustomModalLive) %>
</div>
```

This is a portion of a Non-live view page, rendered from a regular controller. So, the navigation `link` is still under a dead view, I guess.

The Live Component gets rendered using `live_render` (It's just an informational modal, no navigation). The problem was not inside the Live Component but with the `link` in the dead view.

Hope this provided a bit more context, while I'm not able to provide a full example.

**Comment by josevalim** [comment]
I need to confirm: is your home page a LiveView or a DeadView?

**Comment by travelmassive** [comment]
My issue is point 2 in @josevalim earlier comment: "inside a non-LiveView and you are linking to a LiveView using <.link navigate>".

When I click the link in my menu (see my screenshot) the page is not loaded. Previously in 0.19.5 and earlier, clicking the menu link would work. I understand the 2x RTT penalty that Chris mentioned and willing to wear it.

In my case, my home page (/) is a LiveView.

Happy to do apply any patches or small code changes to help test.

**Comment by zediogoviana** [comment]
I'm partial point 2. I am inside a non-LiveView and I'm linking also to a non-LiveView. The LiveView component is just a modal/popup for "extra" reactivity when showing information. It's one of those `(i)`-like buttons.

**Comment by josevalim** [comment]
@zediogoviana so in your case it sounds good that it breaks. It was being inefficient for reason. :)

**Comment by chrismccord** [comment]
I'll see if we can detect this case on the client (controller live_render => dead navigate) and avoid the 2x RTT, but we won't be able to avoid the 2x RTT for the (live route => dead navigate), so you will still need better structure to avoid the pitfalls

**Comment by zediogoviana** [comment]
True @josevalim ! I fixed this by moving everything to non-LiveView, using JS only.

From my side, it was a mixture of starting from the wrong place and having the luck of it working (even if it was not supposed to) 😅 

Thank you everyone for the help!

**Comment by travelmassive** [comment]
I think it's the commit 633f3565ea0d39abc4b9fdb9a0e80a2334c21a7e for #2716 that is causing the issue for me.

This guard ```if(this.isMain()){ this.onRedirect({to: this.href}) }``` in onJoinError(resp) in view.js

**Comment by travelmassive** [comment]
Here's what the HTML looks like for a menu link rendered by a LV component. The new behaviour in view.js prevents this link from working. I would assume that the href should be respected and the client allowed to follow the link.

```<a href="http://www.travelmassive.com/pages/work-with-us" data-phx-link="redirect" data-phx-link-state="push">```

I am happy to test any patches and open to other workarounds. -- Ian

**Comment by jonatanklosko** [comment]
In Livebook we have a dead view where we render a LV with list of items. Each item is a live navigation and in the latest LV it fails with the same error. For now we are going to change it to a regular link.

**Comment by chrismccord** [comment]
Live navigation is not supported for dead views, so regular links is an easy solution if you aren’t trying to share the links across dead/live. We will try to have the client detect this case without a round trip and do a regular window location navigation

**Comment by srcrip** [comment]
@chrismccord @josevalim would it be possible to re-consider this one? At work we have a legacy app with a lot of dead views where we also made use of this old behavior, migrated to latest, and it is now broke and we have to move all the links.

I understand it's not the intention of navigate to have ever worked on DVs. I think some work was done that kind of restored some of the behavior cause navigating to a DV from a LV seems to work on 0.20.x. navigating to a LV from a DV does not seem to work.

Like I said I understand that it's not intended and never was intended behavior, but I feel like if LV.js can easily detect this state and fall back to a href we should do it: rather than break someone's app if they happen to make this mistake in the future.

It was mentioned that there's concerns it would take a full page request to pull off that behavior, but couldn't LV.js simply check if the socket is connected before doing a navigate, and if it is fallback to an href? Perhaps I'm missing something but I feel like that would fully restore the behavior of navigate working in all situations and 'progressively enhancing' the situation when you're in a LV.

I would be happy to provide the PR but I know this is controversial so I wanted to maybe try to align everyone before putting in the work to see if it's doable. But I think it would be, and I think if we can make LiveView "just work" on this issue with less thinking required we should do it.

**Comment by josevalim** [comment]
> I think some work was done that kind of restored some of the behavior cause navigating to a DV from a LV seems to work on 0.20.x. navigating to a LV from a DV does not seem to work.

Correct, we restored navigating from a DV to a LV. However, I am sorry to say, but it really does not make sense to support from a LV to a DV. You said it should work "rather than break someone's app if they happen to make this mistake in the future", but the issue is that navigating from LV to a DV will require two round-trips, because the client needs one request to detect it was not a LV and then it does a regular browser redirect. Therefore, if we leave this working, it means links will now have double the latency and, as you can see per this thread, a lot of people were doing that accidentally.

If you need help upgrading your app, you can try writing a script that detects all `navigate={~p"/..."}`, parse the URLs out, and calls `Phoenix.Router.route_info` to see if it is a LiveView or not.

**Comment by srcrip** [comment]
Thanks @josevalim. I found out later today that the case we were running into was actually not related to this, so sorry for confusion.

However, while we thought that this was the problem, I'm kinda confused as to the state of things right now. In my apps I just use navigate everywhere, cause although I knew it was undefined behaviour it seemed to work ok. You commented that some of that undefined behavior was added back in, but as far as I can tell it seems like it was totally added back in.

My confusion stems around navigating from a LV to a DV. Your comment made me think that that is not supposed to work anymore (when using `navigate`) but in fact it does seem to work for me. So as far as I can tell:

1. you can use `navigate` to go from a LV to a LV without problems
2. you can use `navigate` to go from a LV to a DV without problems
3. you can use `navigate` to go from a DV to a LV without problems
4. you can use `navigate` to go from a DV to a DV without problems

In my testing all these seem to work without throwing an error that stops the navigation in some way. Am I just getting lucky, or am I misinterpreting your statement to mean that something actually *is* going wrong and I'm just not seeing it? Or am I getting some kind of performance hit that I'm not seeing?

**Comment by josevalim** [comment]
The recommendations have always been the same:

1. patch is within the same LV
2. Navigate to LVs
3. Everything else is href 

I will make sure this is listed in the docs once I am back home but I believe it is, since it is quite “old”.

you may navigate to a DV, but that’s not officially supported and you will surely pay double latency when going from LV to DV.

**Comment by srcrip** [comment]
I know it's not supposed to work I'm just confused that it still seems to. I didn't notice any double latency, but maybe I was just not testing it right?

**Comment by josevalim** [comment]
Can you please provide a sample app that shows what you are seeing to make sure we are on the same page?
