### ISSUE TITLE
Textareas being formatted by HTMLFormatter

### ISSUE THREAD

**Issue by APB9785** [phoenixframework/phoenix_live_view#2838]
### Environment

* Elixir version (elixir -v): 1.15.5
* Phoenix version (mix deps): 1.7.7
* Phoenix LiveView version (mix deps): 0.19.5
* Operating system: OS X 12.6.6
* Browsers you attempted to reproduce this bug on (the more the merrier): Firefox
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Actual behavior

HTMLFormatter is adding a newline between `<textarea>` tags, which adds unexpected whitespace to the rendered output
```
iex(1)> Phoenix.LiveView.HTMLFormatter.format("<textarea class=\"test\"></textarea>", heex_line_length: 10)
"<textarea class=\"test\">\n</textarea>\n"
```
The tag `phx-no-format` has no effect.  The newline is still added even when that attr is included.

### Expected behavior
```
iex(1)> Phoenix.LiveView.HTMLFormatter.format("<textarea class=\"test\"></textarea>", heex_line_length: 10)
"<textarea class=\"test\"></textarea>\n"
```

**Comment by leandrocp** [comment]
For extra context, this assertion fails:

```elixir
      assert_formatter_doesnt_change(
        """
        <textarea></textarea>
        """,
        line_length: 5
      )
```

But seems like it shouldn't. And the root cause is the check `buffer != []` here https://github.com/phoenixframework/phoenix_live_view/blob/1626c384094894a1112da0365d33fd8844a35148/lib/phoenix_live_view/html_formatter.ex#L482 Idk why only nom-empty elements are preserved, but removing that check all tests pass, including the assert above.

**Comment by josevalim** [comment]
@leandrocp please send a PR with tests. I think your changes are good.

**Comment by leandrocp** [comment]
@josevalim thanks. @APB9785 will push a PR soon.
