### ISSUE TITLE
Unable to upload files in a batch one by one

### ISSUE THREAD

**Issue by luka-TU** [phoenixframework/phoenix_live_view#2846]
### Environment

* Elixir version (elixir -v): Elixir 1.15.0 (compiled with Erlang/OTP 25)
* Phoenix version (mix deps): 1.7.7
* Phoenix LiveView version (mix deps): 0.20.0
* Operating system: macos Ventura 13.6
* Browsers you attempted to reproduce this bug on (the more the merrier): Chrome
* Does the problem persist after removing "assets/node_modules" and trying again? Yes

### Actual behavior
I am trying to upload files in a batch but sequentially (example: select multiple files in the file picker, and get them to be uploaded one by one).

For that I have implemented a hook like this:

```js
const Uploader = {
  mounted() {
    this.el.addEventListener("change", (e) => {
      e.preventDefault();
      e.stopImmediatePropagation();

      let files = Array.from(this.el.files);
      const uploadName = this.el.dataset.uploadName;

      if (files && files.length > 0) {
        for (const file of Array.from(files)) {
          this.upload(uploadName, [file]);
        }
      }
    });
  }
}

export default Uploader;
```

which is referenced from [this example](https://github.com/mcrumm/live_upload_example/blob/main/assets/js/resize_input.js).

The first file in the batch gets uploaded well, but the rest are stuck in the pre-uploading state inside the `uploads` assign, and nothing happens.
I am using `auto_upload: true`.

### Expected behavior
The files get uploaded one by one, until the whole batch is complete.

**Comment by Zurga** [comment]
For what it is worth, I maintain a [fork](https://github.com/Zurga/phoenix_live_view/tree/upload_in_batches) of liveview that has batch uploading. You could use it as inspiration.

**Comment by chrismccord** [comment]
What is your max entries? Can you share your elixir code?

**Comment by SteffenDE** [comment]
Can you try `{:phoenix_live_view, github: "SteffenDE/phoenix_live_view", branch: "issue_2965_assets", override: true}` and see if that helps? That addresses a similar issue when calling upload multiple times.

**Comment by SteffenDE** [comment]
So I just tested this with the changes from https://github.com/phoenixframework/phoenix_live_view/pull/3004 and the PR does indeed solve the problem of the files being stuck, **BUT**: even with those changes the code in your hook will not do what you want. If `max_entries` is set to one, only the last file will be uploaded because the loop in the hook calls the `upload` method without waiting for uploads to complete. If `max_entries` is larger than the number of uploads, all uploads will happen at the same time.

What you can try to do is what is shown in #2965: listening for complete uploads in `handle_progress` and pushing an event to your hook to send the next file:

```elixir
def handle_progress(:files, entry, socket) do
    if entry.done? do
      {:noreply, push_event(socket, "upload_send_next_file", %{})}
    else
      {:noreply, socket}
    end
  end
```

It would be nice if `upload` in a hook could be awaited, but that would definitely require some changes to the LV JS code.
