### ISSUE TITLE
Trying to cancel the events from "phx:page-loading-start" doesn't do anything to stop page load

### ISSUE THREAD

**Issue by sevensidedmarble** [phoenixframework/phoenix_live_view#2926]
### Environment

* Elixir version (elixir -v): 1.14.2
* Phoenix version (mix deps): 1.6.15
* Phoenix LiveView version (mix deps): 0.18.11
* Operating system: Mac
* Browsers you attempted to reproduce this bug on (the more the merrier): Chrome
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Actual behavior

Trying to write a hook that can cancel page loads based on a form being dirty, but it doesn't seem to work with live navigation:

```javascript
const DirtyFormHook = {
  mounted() {
    this.beforeUnload = (e) => {
      if (this.el.hasAttribute('data-dirty-form')) {
        e.preventDefault()
        e.returnValue = ''
      }
    }

    this.pageLoadingStart = (e) => {
      if (e.detail.kind === 'initial') {
        return
      }

      if (this.el.hasAttribute('data-dirty-form')) {
        if (!confirm("Are you sure you want to leave this page? You have unsaved changes.")) {
          e.preventDefault()
          e.stopImmediatePropagation()
        }
      }
    }

    window.addEventListener('beforeunload', this.beforeUnload, true)
    window.addEventListener('phx:page-loading-start', this.pageLoadingStart, true)
  },
  destroyed() {
    window.removeEventListener('beforeunload', this.beforeUnload, true)
    window.removeEventListener('phx:page-loading-start', this.pageLoadingStart, true)
  }
}
```

### Expected behavior

This kinda thing works fine with beforeunload, so I'd expect you'd be able to cancel page loads from liveview too.

**Comment by josevalim** [comment]
Those events were designed for notifying you, cancelling them does not have an effect, especially because it is also called on initial load and other scenarios where it wouldn’t make sense to cancel. I think the safest bet is to intercept the click event itself on a form or link that could lead to navigation.

**Comment by dlindenkreuz** [comment]
Sorry for necromancing this thread, but it would be great to have a solution since this is a common use case for heavy forms, payment flows, active chat support sessions etc.

One would also need to intercept the **native browser back button action**, which can be either a hard page reload (already covered by `beforeunload`) or a `popstate` history API call.

The latter is impossible to hook into at the moment:

https://github.com/phoenixframework/phoenix_live_view/blob/dacbd1575cf03a932eb54c672c36a84b837a0d9e/assets/js/phoenix_live_view/live_socket.ts#L1355-L1382

I researched the order of events:
- `popstate`, not cancelable
  - inside handler, window.location already has a new value
  - upon "cancel" e.g. via `window.confirm("are u sure?")`, SPA router libraries usually call `history.replaceState()` here to inject the previous URL, otherwise the address bar will inevitably change
- `beforeunload`
  - blocking is possible here but popstate has already fired

Maybe LiveView could fire a new `phx:before-navigate` event before updating internal state in the snippet above and return early if `dispatchEvent` return value is `false`. It would then need to inject the previous URL from the internally tracked stack with `history.replaceState()`.

<details><summary>This is what TanStack Router roughly does `onPopState`</summary>
<p>

[Original code](https://github.com/TanStack/router/blob/41f7bf32837e751b2874e7d827f7456f8a5bd716/packages/history/src/index.ts#L405-L452)

Simplified version with some comments:

```ts
const onPushPopEvent = async () => {
  if (ignoreNextPop) {
    ignoreNextPop = false
    return                          // ← skip if we caused this popstate ourselves (rollback)
  }

  const nextLocation = parseLocation()
  const delta = nextLocation.state[stateIndexKey] - currentLocation.state[stateIndexKey]
  const isForward = delta === 1
  const isBack    = delta === -1
  const isGo      = (!isForward && !isBack) || nextPopIsGo
  const action    = isGo ? 'GO' : isBack ? 'BACK' : 'FORWARD'

  if (skipBlockerNextPop) {
    skipBlockerNextPop = false      // ← skip blockers if programmatic navigation set this flag
  } else {
    const blockers = _getBlockers()
    if (typeof document !== 'undefined' && blockers.length) {
      for (const blocker of blockers) {
        const isBlocked = await blocker.blockerFn({
          currentLocation,
          nextLocation,
          action,
        })
        if (isBlocked) {
          ignoreNextPop = true      // ← prevent re-entry when we call go(1) below
          window.history.go(1)         // ← undo the navigation by going forward 1 step
          return                    // ← bail out, don't update internal currentLocation
        }
      }
    }
  }

  currentLocation = parseLocation() // ← navigation was allowed, commit location
}
```

</p>
</details>

**Comment by SteffenDE** [comment]
@dlindenkreuz we looked into this for https://github.com/phoenixframework/phoenix_live_view/pull/3051. The browser API is just very bad. And even if we made this work (preventing the client initiated popstate navigation), you still wouldn't be able to prevent a server initiated navigation, because if you do push_navigate, the old process is gone by the time the client can react to it. Maybe we could revisit this if we can agree on a smaller scope. I'd suggest to open a new issue for discussion.

**Comment by SteffenDE** [comment]
@dlindenkreuz also, you can try registering your own popstate listener by ensuring it registers before you create your `LiveSocket` instance. Then you could replicate the TanStack code and ensure you synchronously call `stopImmediatePropagation` when a blocker is active. You'll still need to manually prevent link clicks (a capture phase click listener on document could solve that) and as mentioned, server-side navigation cannot be cancelled in any way.

**Comment by SteffenDE** [comment]
@dlindenkreuz please try https://github.com/phoenixframework/phoenix_live_view/pull/4332

```elixir
{:phoenix_live_view, github: "phoenixframework/phoenix_live_view", branch: "sd-cancel-nav-assets", override: true}
```

and let me know if that works for you!

**Comment by dlindenkreuz** [comment]
Just adjusted my `dirty_back_button` and it works with the WIP phoenix_live_view branch 🫶 

```elixir
attr :form, Phoenix.HTML.Form, required: true
attr :rest, :global, include: ~w(navigate patch)

def dirty_back_button(assigns) do
  assigns = assign(assigns, :dirty, assigns.form.source.changes != %{})

  ~H"""
  <.button
    id="back-btn"
    type="button"
    phx-hook=".DirtyBack"
    data-dirty={to_string(@dirty)}
    size="icon"
    {@rest}
  >
    <.icon name="hero-arrow-left" />
  </.button>
  <script :type={Phoenix.LiveView.ColocatedHook} name=".DirtyBack">
    export default {
      mounted() {
        this.handleBeforeUnload = (e) => {
          if (this.el.dataset.dirty === "true") {
            e.preventDefault()
            e.returnValue = ""
          }
        }
        window.addEventListener("beforeunload", this.handleBeforeUnload)

        this.handleBeforeNavigate = (e) => {
          if (this.el.dataset.dirty === "true") {
            if (!confirm("You have unsaved changes. Are you sure you want to leave?")) {
              e.preventDefault()
            }
          }
        }
        window.addEventListener("phx:before-navigate", this.handleBeforeNavigate)
      },
      destroyed() {
        window.removeEventListener("beforeunload", this.handleBeforeUnload)
        window.removeEventListener("phx:before-navigate", this.handleBeforeNavigate)
      }
    }
  </script>
  """
end
```

**Comment by srcrip** [comment]
Thanks for implementing this @SteffenDE!
