### ISSUE TITLE
raise if a non router-based LV attempts to live redirect

### ISSUE THREAD

**Issue by chrismccord** [phoenixframework/phoenix_live_view#309]
Only the root may issue live redirects

**Comment by samuelpordeus** [comment]
@chrismccord Hello, I wrote a test for this scenario, but I couldn't think in a good way to know if a LV is non router-based using `live_redirect/2`.

I was thinking about using something like `route_info/4`, but since we only have the `socket` and the path we are going to (not from) on `live_redirect/2`, I don't know what to do. 🤔

I may be missing something, but if you could give me any hint, I would appreciate it a lot 😬
