### ISSUE TITLE
Documentation for phx-update doesn't mention append, which example uses

### ISSUE THREAD

**Issue by Munksgaard** [phoenixframework/phoenix_live_view#3177]
The [DOM patching & temporary assigns](https://hexdocs.pm/phoenix_live_view/dom-patching.html) guide specifies that the `phx-update` attribute is allowed to take on one of three values: `replace`, `ignore` and `stream`. However, further down in [the example](https://hexdocs.pm/phoenix_live_view/dom-patching.html#temporary-assigns), a fourth option is being used, namely `append`.

Is `append` a valid option for `phx-update` or is it an old option that has been removed and the documentation not updated properly? Are there other valid options that are undocumented?

**Comment by josevalim** [comment]
Good find. append/prepend have been deprecated, the whole section is outdated. I have removed the old parts and merge into the bindings guide. :) TY!

**Comment by Munksgaard** [comment]
You're very welcome. Thanks for the speedy response!

**Comment by TheArrowsmith** [comment]
With this change, the "guides" no longer mention `temporary_assigns` at all, and the only explanation of `temporary_assigns` is this [one sentence](https://hexdocs.pm/phoenix_live_view/1.0.0-rc.6/Phoenix.LiveView.html#c:mount/3) in the docs for `mount/3`:

> `:temporary_assigns` - a keyword list of assigns that are temporary and must be rest to their value after every render. Note that once the value is reset, it won't be re-rendered again until it is explicitly assigned

I'm a bit confused as to what purpose `temporary_assigns` still serves, since it's no longer needed when streaming collections. Presumably it's not completely useless, as the `phx.gen.auth` LiveViews still use it for their `form` assigns; see e.g. this line from `UserRegistrationLive`:

```elixir
    {:ok, socket, temporary_assigns: [form: nil]}
```

`UserLoginLive` renders the form with `phx-update="ignore"` but other auth forms don't so I'm guessing `phx-update="ignore"` isn't needed for temporary assigns - so why is it used on `UserLoginLive`?

I'm struggling to understand what `temporary_assigns` still achieves because I can't detect any appreciable difference in behaviour on (for example) `UserLoginLive` when I remove the `temporary_assigns` option from mount. The wording of the docs makes me think that the `@form` assign would be "reset" in some way but I'm not sure what gets reset. E.g. if I add a button to `UserLoginLive` that prints the value of `@form` post-render...

```elixiri
   def render(assigns) do
     ~H"""
       …
+    <button phx-click="click">Click me</button>
     """
   end

…

+
+  def handle_event("click", params, socket) do
+    IO.inspect(socket.assigns.form)
+    {:noreply, socket}
+  end
 end
```

When I click this button I can see that `@form` is still a `%Form{}` and doesn't seem to have been "reset" from what it was initially when mounted.

Can you please clarify what the use case still is for `temporary_assigns` and how it's meant to work? I'm happy to submit a PR to the docs just as soon as I've gained a bit more clarity myself.

**Comment by josevalim** [comment]
Temporary assigns are still useful for data you don't expect to change after the initial render. For example, imagine you are implementing a blog. When showing a post, it is a waste to keep the whole post body in memory. So you set the post body as a temporary assign [body: nil]. Now whenever the body is set, it will be set back to nil after rendering,  and you don't keep several kbs per user in memory.

It is defintiely more niche now though. The most common use case was for collections (as they are the most obvious "large things we keep in memory").

**Comment by TheArrowsmith** [comment]
Ahhhh I see, so because you're passing the *value* of `nil` as the temporary assign in mount then it gets to reset to `nil` after render.

In that case the only thing I don't understand is what the `temporary_assigns` call achieves in `UserLoginLive` for example:

```elixir
    {:ok, assign(socket, form: form), temporary_assigns: [form: form]}
```

We're telling `@form` to reset to the `form` as it was first initialized on mount. But the value of `@form` never gets changed again after mount (the LV has no event handlers), so the temporary assign only gets "reset" to the same value that it already had, no?

**Comment by josevalim** [comment]
It is probably redundant there then.
