### ISSUE TITLE
Disconnecting live instances on log out does not work when setting `with: :clear_session` in `:protect_from_forgery`

### ISSUE THREAD

**Issue by Munksgaard** [phoenixframework/phoenix_live_view#3210]
### Environment

* Elixir version (elixir -v): 1.16.1
* Phoenix version (mix deps): 1.7.11
* Phoenix LiveView version (mix deps): 0.20.5
* Operating system: NixOS
* Browsers you attempted to reproduce this bug on (the more the merrier): Firefox
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Actual behavior

In a project using `phx.gen.auth` to handle authentication, disconnecting all liveview connections of a particular user when logging out does not work when `with: :clear_session` is specified in the `:protect_from_forgery` plug.

To reproduce, put the following in your `router.ex`:

```elixir
    plug :protect_from_forgery, with: :clear_session
```

Then open two separate logged in tabs and log out in one of them. Observe that the other doesn't automatically disconnect and log out as well.

### Expected behavior

Other tabs are automatically disconnected as well.

**Comment by Schultzer** [comment]
I wonder if this has ever worked for an LV since the two tabs would be two different sessions (WebSockets), even though it's the same user account. Usually, this kind of thing is solved by a fingerprint; I've done so myself in a couple of projects using Pow and then disconnected the LV with the fingerprint as live_socket_id. That being said, it sounds like you want to be able to log out a user across all possible sessions. This requires you to invalidate all sessions associated with a user; I wouldn't say this is common unless you let the user know that, but you should be able to modify the code, too. Instead of invalidating a specific session, it invalidates all sessions belonging to the user. 

https://github.com/phoenixframework/phoenix/blob/main/priv/templates/phx.gen.auth/context_functions.ex#L232

As the code is generated, it would be hard for me to be more concrete than pointing out the above. I hope this helps.

**Comment by Munksgaard** [comment]
Just to be clean: without `clear_session` it does log out my across all my open tabs. I'm not sure exactly what the mechanism behind that functionality is though.

**Comment by Schultzer** [comment]
> Just to be clean: without `:clear_session` it does log out my across all my open tabs. I'm not sure exactly what the mechanism behind that functionality is though.

I see, from plug itself: https://github.com/elixir-plug/plug/blob/v1.10.0/lib/plug/csrf_protection.ex#L83

> * `:clear_session` -  for invalid requests, this plug will set an empty
      session for only this request. Also any changes to the session during this
      request will be ignored.

Since you are clearing the session, and there is two websockets open, then I doubt that LV / phx.gen.auth is smart enough to keep track of the open websockets, since that infomation might be stored in the cookie session.

I have previously built proprietary infrastructure around securing websockets especially long running, as far as I know, there is no solution on the market regardless of what your are using phx.gen.auth, pow and etc.

**Comment by Munksgaard** [comment]
Thank you for your comment. I had overlooked the sentence about "changes to the session", so I guess this is all working as intended. I'll close the issue :-)
