### ISSUE TITLE
put_flash lack documentation, :warning not supported

### ISSUE THREAD

**Issue by ponychicken** [phoenixframework/phoenix_live_view#3342]
In the put_flash docs, there is no clear mention what types are supported. Seems like :info, :error, but not :warning.

It would be good to state this and maybe also support a ;warning flash

**Comment by SteffenDE** [comment]
This is because put_flash does not care about the types at all. The info and error flash come from the generated core components: https://github.com/phoenixframework/phoenix/blob/25e891f172045aa0391d30bfd794111235041159/installer/templates/phx_web/components/core_components.ex#L147-L151

So if you add a `warning` flash there and also implement the styles in your flash component, it will work just like the others. You could also call it `warn`, `information` or whatever key you like :)

A PR to improve the docs is always appreciated though!

**Comment by ponychicken** [comment]
Ok, I will add something along this lines to the docs.
