### ISSUE TITLE
Empty trailing whitespace in `class` attribute

### ISSUE THREAD

**Issue by Gigitsu** [phoenixframework/phoenix_live_view#3384]
### Environment

* Elixir version (elixir -v): Elixir 1.16.1 (compiled with Erlang/OTP 26)
* Phoenix version (mix deps): 1.7.14
* Phoenix LiveView version (mix deps): 0.20.17
* Operating system: Debian GNU/Linux 12 (bookworm)
* Browsers you attempted to reproduce this bug on (the more the merrier): *
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: yes

### Actual behavior

I have a component with a `class` attribute that is merged with some default classes, like this:

```elixir
attr :class, :string, default: nil

def my_component(assigns) do
  ~H"""
  <div class={["required-class", @class]}>
    ...
  </div>
  """
end
```

If `@class` is `nil` (the default value) the component is rendered with an empty trailing space: `<div class="required-class " ... `

This issue occurs only if `@class` is the last element of the list.

I can fix this with `class={["required-class" | List.wrap(@class)]}` but this feels like a workaround.

### Expected behavior

Trailing whitespace should be removed for the class attribute.

**Comment by SteffenDE** [comment]
This is because of how the template is compiled. At compile time we know that `"required-class"` is a static string and therefore already build the expression for `"required-class " <> escape(@class)` (pseudo-code). It's only at runtime that we know that `@class` is actually nil, but the code for concatenating the escaped `@class` assign is already built. (@josevalim correct me if I'm wrong)

https://github.com/phoenixframework/phoenix_live_view/blob/32561b4a548015721dda0c9373a029ef3930178b/lib/phoenix_live_view/html_engine.ex#L89-L103

As this doesn't have any negative consequences despite not looking as nice, I'm not convinced that this is a real issue.

**Comment by josevalim** [comment]
Exactly. We do this because it is the most efficient code we can emit, that avoids string manipulations at compile-time and can inline whole static parts.

**Comment by Gigitsu** [comment]
Fair enough, thank you for the answer
