### ISSUE TITLE
Possible issue with form diffing

### ISSUE THREAD

**Issue by iwarshak** [phoenixframework/phoenix_live_view#3414]
### Environment

* Elixir version (elixir -v): 1.15.6
* Phoenix version (mix deps): 1.7.14
* Phoenix LiveView version (mix deps): 1.0.0-rc.6 (5abb0fc)
* Operating system: mac
* Browsers you attempted to reproduce this bug on (the more the merrier): 
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no:

### Description

I have a real life scenario where I am using an embedded_schema form to back my LV's form. This is to decouple the Ecto schema from the form & do complex validations, etc. 

The issue is that my both forms validation & save events had set the action to `:validate` but I ran into a case where not all errors are showing up in the case when you partially fill out the form and then submit it. You can see it in an example app I published: https://github.com/iwarshak/lvformdiffbug

I believe I traced it down to https://github.com/phoenixframework/phoenix_live_view/blob/main/lib/phoenix_component.ex#L1505

What I think is happening is that I am assigning a new form object to the socket, but the diff engine is not seeing an actual difference and not rendering the form and fields again. There is a difference though:  the `_unused_last` parameter has been replaced with `last` and an error *should* be rendered. 

This is possibly an edge case, but it is certainly unexpected to not have the form not re-render when its underlying data & params have changed. As `Phoenix.Component.used_input?` becomes more adopted, I can see this issue cropping up.

**Comment by SteffenDE** [comment]
LV only re-renders when the input is considered changed. The code that checks this is here:

https://github.com/phoenixframework/phoenix_html/blob/c966418f6f71b9a514c08fd4b204b18154ce9a01/lib/phoenix_html/form.ex#L199

As the value is included in the change this should work, but I didn’t try the reproduction yet. I’ll try to look into this tomorrow.

Do you have any specific reason to not use a different action for the submit case?

**Comment by iwarshak** [comment]
My embedded_schema had a `validate` function which did all the validations and set the action to `validate`. My LV "save" event called `validate` and if it validated, I transformed the embedded schema to a DB backed schema and persisted it. 

It is known and documented that you have to set an action for errors to be displayed, but it was unexpected that I could not re-use an action name.

**Comment by SteffenDE** [comment]
Hi @iwarshak,

I just tried your repro and from LV's perspective the field actually did not change:

When the validate event is handled, the value of the field is set to an empty string `""`, the errors are set to `can't be blank`, but because the field is unused, the errors are not rendered. When the save event is triggered, all conditions checking if the input changed are false: the action, errors and input values are the same -> LV does not re-render the field. Using a different `action` in `to_form` for validate and submit will work around this for now. The action you pass to `to_form` also overrides the action set on the changeset, so you should not need to modify your validation function.

<hr>

@josevalim we could change https://github.com/phoenixframework/phoenix_live_view/blob/5abb0fcd5211cbc089d863200926a529ad3c9625/lib/phoenix_live_view/engine.ex#L1278-L1280 to something like:

```elixir
defp recur_changed_assign([{:access, head}], %Form{} = form1, %Form{} = form2) do
  Form.input_changed?(form1, form2, head) and
    Phoenix.Component.used_input?(form1, head) === Phoenix.Component.used_input?(form2, head)
end
```

and then any change in field usage would also re-render, wdyt?

**Comment by josevalim** [comment]
The real issue is that we are accessing the `form` field from the `Field` struct, and that bypasses change tracking. Given that we are the ones bypassing it ourselves, I believe your solution is correct @SteffenDE. Go for it!
