### ISSUE TITLE
Form reset not setting _unused params

### ISSUE THREAD

**Issue by dbsimmons64** [phoenixframework/phoenix_live_view#3468]
### Environment

* Elixir version (elixir -v): 1.17.3
* Phoenix version (mix deps): 1.7.14
* Phoenix LiveView version (mix deps): 1.0.0-rc.1
* Operating system: Mac OS X 14.4.1 (23E224)
* Browsers you attempted to reproduce this bug on (the more the merrier): Chrome Version 129.0.6668.100, Firefox 130.0.1
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Actual behavior

I have an application with a form on a page rather than being a modal. When the user submits the form I ceate a new `changeset` and reply to the browsser. This resets the form on the browser but does not reset the _unused params so that entering a value in a field trigger validation and reporting of errors on all fields.

I have created a Repo with as simple as possible example: https://github.com/dbsimmons64/simple.

To replicate:

1. Enter the `name` and `age` of a pet and hit submit
2. The newly created `pet` is added to the list and the form is cleared
3. Enter a new pet `name` and see how `age` now reports an error even though it hasn't been touched by the user.

### Expected behavior

Expect the form to behave as when first loaded i.e. not report errors on fields that haven't been touched by the user.

**Comment by SteffenDE** [comment]
I don't think there's anything to be done here. If you stay on the same page, keeping the old form in the DOM, there's no way for LV to know that the fields should be considered unused again. You'll need to explicitly reset the form, which can happen in multiple ways:

1. navigate to the same LV using push_navigate, which will recreate the LV and therefore also remount the page
2. roll the ID of the form
3. add a hook to your form and push_event a "reset" event, then do `this.el.reset()` in your hook

**Comment by dbsimmons64** [comment]
Thanks @SteffenDE. I thought this might be the case but wanted to check. Is there anyway that `to_form` could be enhanced with a `:reset` option so the frontend knows to reset the unused params?

**Comment by andrewtimberlake** [comment]
@SteffenDE points 1 and 2 are nice ideas.
How do you handle the UX of having either the last input used remain in focus, or moving focus back to the beginning of the form on “reset”?
I find if I use `form.reset()` and move focus, the input still is marked as used, even if I reset after the focus change. Also form reset doesn’t reset the form’s `phx-has-submitted` private state.

**Comment by SteffenDE** [comment]
@dbsimmons64 I don't see an nice way to make that work. `to_form` only creates a server-side structure that is then rendered in the DOM. We'd need to have `simple_form` or `Phoenix.Component.form/1` create some kind of magic attribute that the client could react on when the DOM is patched, but I'm not convinced, as the alternative solutions are quite simple (see below).

@andrewtimberlake we handle reset events on forms and reset both the internal focus and submitted states:
https://github.com/phoenixframework/phoenix_live_view/blob/ebca5e7b83bb703a97d1eadd87b404072ad3295c/assets/js/phoenix_live_view/dom.js#L346-L351

Here's how the solutions would look like:

1. navigate to the same LV using push_navigate, which will recreate the LV and therefore also remount the page

```diff
diff --git a/lib/simple_web/live/pet_live/index.ex b/lib/simple_web/live/pet_live/index.ex
index f616446..745e338 100644
--- a/lib/simple_web/live/pet_live/index.ex
+++ b/lib/simple_web/live/pet_live/index.ex
@@ -61,7 +61,7 @@ defmodule SimpleWeb.PetLive.Index do
          socket
          |> stream_insert(:pets, pet)
          |> put_flash(:info, "Pet created successfully")
-         |> assign(:form, to_form(changeset))}
+         |> push_navigate(to: ~p"/pets")}
 
       {:error, %Ecto.Changeset{} = changeset} ->
         {:noreply, assign(socket, :form, to_form(changeset))}
```

2. roll the ID of the form

That one actually doesn't work, as the state on the input fields themselves doesn't get reset if only the form id changes :(

3. using push_event and an event handler (I did not add a hook)

```diff
diff --git a/assets/js/app.js b/assets/js/app.js
index d5e278a..95e379f 100644
--- a/assets/js/app.js
+++ b/assets/js/app.js
@@ -33,6 +33,10 @@ topbar.config({barColors: {0: "#29d"}, shadowColor: "rgba(0, 0, 0, .3)"})
 window.addEventListener("phx:page-loading-start", _info => topbar.show(300))
 window.addEventListener("phx:page-loading-stop", _info => topbar.hide())
 
+window.addEventListener("phx:reset-form", (e) => {
+  document.getElementById(e.detail.id).reset();
+});
+
 // connect if there are any LiveViews on the page
 liveSocket.connect()
 
diff --git a/lib/simple_web/live/pet_live/index.ex b/lib/simple_web/live/pet_live/index.ex
index f616446..38bfd9a 100644
--- a/lib/simple_web/live/pet_live/index.ex
+++ b/lib/simple_web/live/pet_live/index.ex
@@ -61,7 +61,8 @@ defmodule SimpleWeb.PetLive.Index do
          socket
          |> stream_insert(:pets, pet)
          |> put_flash(:info, "Pet created successfully")
-         |> assign(:form, to_form(changeset))}
+         |> assign(:form, to_form(changeset))
+         |> push_event("reset-form", %{id: "simple-form"})}
 
       {:error, %Ecto.Changeset{} = changeset} ->
         {:noreply, assign(socket, :form, to_form(changeset))}
```

The two solutions here work fine from my testing. The simpler one is the push_navigate way, although it remounts the whole page, so that might not be what you want, but most of the time it's probably fine. The "clean" way is to use `form.reset()`, which also works from my testing.

**Comment by dbsimmons64** [comment]
Thanks @SteffenDE. I've switched to `push_navigate` as it works fine. Agree remounting the whole LV isn't ideal in some cases but it seems fine in mine.

**Comment by chrismccord** [comment]
Closing as we have a satisfactory solution for this case. Thanks!
