### ISSUE TITLE
Checkbox - handle_event params indicates that the value is always "on" regardless of check state

### ISSUE THREAD

**Issue by jeremyowensboggs** [phoenixframework/phoenix_live_view#442]
### Environment

* Elixir version (elixir -v): 1.7.3
* Phoenix version (mix deps): 1.4.10
* Phoenix live_view: 0.3.1
* NodeJS version (node -v): 10.15.3
* NPM version (npm -v): 6.10.3
* Operating system: Mac OSX 10.14.6

### Actual behavior

When a 'phx-click' is on a checkbox element, the resulting event always indicates that the value of the checkbox is "on"

`<input type="checkbox" phx-click="check-go-lite"></input>`
```
  def handle_event("check-go-lite", params, socket) do
    IO.inspect(params["value"], label: "Value")
    {:noreply, socket}
  end
```
No matter what: `Value: "on"`

### Expected behavior
The value of the event should indicate if the checkbox is selected or not.

**Comment by jeremyowensboggs** [comment]
We are using 0.3.1, updated live_view version in the environment.

**Comment by snewcomer** [comment]
Ah I know what the issue is.  The default value of a checkbox is "on".  If the value is **checked**, "on" is sent to the server when the form is submitted.  If **unchecked** in a form, the value won't be sent to the server.  

We are taking it at face value and not considering if it is checked or unchecked in `pushEvent`.  I think we need to detect if a checkbox and sent the value accordingly.

Would you like to try out a PR on this?  I'd be happy to as I have another checkbox bug I want to fix on master.  Let me know what you would like to do!

Other note - the phoenix checkbox element has an `unchecked_value` as well if you need to sent "something" on a form submit.
https://hexdocs.pm/phoenix_html/Phoenix.HTML.Form.html#checkbox/3

**Comment by jeremy-365** [comment]
Thanks, if you want to have at it, please do.
