### ISSUE TITLE
toOutputBuffer error on 0.4

### ISSUE THREAD

**Issue by cadebward** [phoenixframework/phoenix_live_view#462]
### Environment

* Elixir version (elixir -v): 1.9.2
* Phoenix version (mix deps): 1.4.10
* NodeJS version (node -v): 8.11
* NPM version (npm -v): 5.6
* Operating system: OSX

### Actual behavior

Loading up a LiveView route after upgrading to 0.4.0 and 0.4.1 throws a client error:

```
phoenix_live_view.js:1 Uncaught TypeError: Cannot read property '0' of undefined
    at Object.toOutputBuffer (phoenix_live_view.js:1)
    at Object.toString (phoenix_live_view.js:1)
    at e.value (phoenix_live_view.js:1)
    at Object.eval [as callback] (phoenix_live_view.js:1)
    at eval (phoenix_live_view.js:1)
    at Array.forEach (<anonymous>)
    at e.value (phoenix_live_view.js:1)
    at Object.eval [as callback] (phoenix_live_view.js:1)
    at e.value (phoenix_live_view.js:1)
    at Object.eval [as callback] (phoenix_live_view.js:1)
```

The unminified locations is here: https://github.com/phoenixframework/phoenix_live_view/blob/448e22642e89de7c26fc8eeb12a49c64d925a496/assets/js/phoenix_live_view.js#L148

This error will be logged each time a `live_link` is clicked that routes to this component. For example, take the following route:

```
live "/path/:param", LiveViewComponent
```

Then when i want to change the param, I use:
```
live_link("Change Params", to: Routes.live_path(assigns.socket, __MODULE__, :new_param))
```

Triggering that link fires off that same uncaught type error mentioned above.

### Expected behavior

Clicking a `live_link` changes to the provided route.

**Comment by chrismccord** [comment]
Can you provide a minimal template + LV module which reproduces this? That would be extremely helpful. Thanks!

**Comment by cadebward** [comment]
I wiped all my `node_modes` and `_build`, added in the new socket in the `app.js`, and now its all working. Thanks

**Comment by trentjones21** [comment]
Just wanted to comment that I got this exact same error message on 0.4.1.  I didn't have any problem at all while developing locally, but the error shows up whenever I deploy my project to Gigalixir.  So clearing `node_modules` and `_build` isn't really an option for me.  

Just letting you know in case you want to reopen the issue.

**Comment by JonRowe** [comment]
I also have this issue when deploying to Heroku

**Comment by overture8** [comment]
I also got this issue when upgrading to 0.4.1. Like @trentjones21, it only shows up for me when deploying to Gigalixir.

**Comment by JonRowe** [comment]
@overture8 its due to a stale JS cache in your `phoenix_static_buildpack.config` add (or create with): 
```
clean_cache=true
```

To the config file, push a deploy, and then if you wish remove / revert it and this problem should go away.

**Comment by overture8** [comment]
@JonRowe Sorry, I completely missed your initial reply to this thread somehow. I tried your suggestion and it worked! Thanks - it has been driving me crazy.

**Comment by tfwright** [comment]
I just noticed what I think is the same or a similar issue on 0.14.1 when calling `pushEvent`. I see an update occur in debug output but then I get the following error on Chrome instead of the expected DOM update:

![Screen Shot 2020-08-19 at 12 18 57 PM](https://user-images.githubusercontent.com/501/90668776-308e2000-e216-11ea-80b3-37db09e45ef4.png)

Source trace shows: `t.buffer+=n[0]` as the location of the error.

Unfortunately removing `_build` and `node_modules` did not resolve the issue.

`"phoenix_live_view": {:hex, :phoenix_live_view, "0.14.1", "92a5a6e4227a9bc546f602373bc7b24bb031457b015ec078d3b3bbcecd29611d", [:mix], [{:jason, "~> 1.0", [hex: :jason, repo: "hexpm", optional: true]}, {:phoenix, "~> 1.5.3", [hex: :phoenix, repo: "hexpm", optional: false]}, {:phoenix_html, "~> 2.14", [hex: :phoenix_html, repo: "hexpm", optional: false]}, {:telemetry, "~> 0.4.2 or ~> 0.5", [hex: :telemetry, repo: "hexpm", optional: false]}], "hexpm",`

**Comment by chrismccord** [comment]
@tfwright please try 0.14.1 and report back (with the usual deps dance). Thanks!

**Comment by tfwright** [comment]
I was actually able to find a work around for this, but I'm not entirely sure what's happening. I suspect you will, but otherwise I will be happy to help track down the root cause.

I tracked the error back to a specific commit where I refactored some list code into a live component. Depending on the content of the assigns, certain members of the list should be hidden. To achieve this, I added a helper that filtered them, looking something like this:

```
          <%= for item <- @items |> filter(assigns) do %>
            <%= live_component @socket, MyApp.Live.Component, id: 'id', ... %>
          <% end %>
```

On a hunch I removed that filter logic and used it to hide the item via css instead. That solved the error. I am guessing this has something to do with how LV derives DOM updates?

**Comment by ccapndave** [comment]
I'm also getting this error after upgrading from 0.12.1 to 0.14.4.

In my case it seems to be dependant on the order I click on things.  If I click first on UI element A, then I get the error, and clicking anything else also throws the error from then on.  If I click first on UI element B then I don’t get the error and everything works normally (including clicking on A).

Sorry this is a bit vague...
