### ISSUE TITLE
Using live_link with Hooks + preventDefault()

### ISSUE THREAD

**Issue by jamilabreu** [phoenixframework/phoenix_live_view#492]
### Environment
* Phoenix LiveView version (mix deps): master

### Actual behavior
```
**Template**
<%= live_link to: "/example-route", "phx-hook": "ExampleHook" do %>Example Live Link<% end %>

**LiveSocket.js**
hooks.ExampleHook = {
  mounted() {
    this.el.addEventListener("click", event => {
      event.preventDefault();
      console.log("MOUNTED");
    });
  }
}
```
console.log("MOUNTED") executes in the console, but the live_link transition isn't prevented as expected with `event.preventDefault();`

**Comment by alvises** [comment]
Have you tried `e.stopImmediatePropagation();` ?

**Comment by jamilabreu** [comment]
@alvises I tried `stopPropagation`, which didn't work - but `stopImmediatePropagation` seems to do the trick :D Thanks!

@chrismccord I'm happy to update the docs if this is by design

**Comment by jamilabreu** [comment]
FYI: Noticing that the desired result is only achieved with two calls. Either:
```
e.preventDefault();
e.stopImmediatePropagation();
```
or
```
e.preventDefault();
e.stopPropagation();
```

**Comment by snewcomer** [comment]
@jamilabreu Since the window owns the `click` listener on a live_link, you are correct.  Either of those two will work since you need to avoid browser default with the `a` href && prevent the event from bubbling up to the window listener. (`stopImmediatePropagation` will also stop bubbling to other events on this specific element that were added after the `click`).

We do need to document how event listeners using hooks vs. LV events.  However, I think that will need some good thought.  I'll make sure to follow up with this in the near future as this is something I have been paying close attention to.

Thanks again for the issue 👍. Hopefully this will provide some documentation for others in the meantime.
