### ISSUE TITLE
live_link does not apply changes to gettext macro

### ISSUE THREAD

**Issue by StormBytePP** [phoenixframework/phoenix_live_view#519]
**Environment**

- Elixir version (elixir -v): v1.9.4 Erlang/OTP 22
- Phoenix version (mix deps): v1.4.11
- Phoenix LiveView version (mix deps): ref 57f2ef7
- NodeJS version (node -v): v13.2.0
- NPM version (npm -v): v6.13.1
- Operating system: Gentoo Linux (amd64, Kernel-5.2.0)

When you have code in a leex template like:

`<h2 align="center"><%= gettext "Change language:" %></h2>`

When locale is changed via live_link, that text remains static.

I noticed that changing code to:
```
<% text = gettext "Change language:" %>
<h2 align="center"><%= text %></h2>
```

This issue seems to happen only when rendered leex file is not changed (because if another leex file is being rendered then the content changes)

While workaround exists by assigning gettext output to variables instead of direct rendering them, it is very annoying to do so.

Is there any configuration I've missed or is this a bug?

**Comment by josevalim** [comment]
Correct. LiveView considers the code to be static because it does not use any assigns. We could add some sort of annotation that forces these statics to be recomputed... but then it would also mean that this information would be resent on every LiveView event.

I think a simpler fix is simply to not use `live_link` for changing the idiom. It is not a frequent action, so it is fine for it to go through the regular request life-cycle.

Thanks for the report!
