### ISSUE TITLE
Key events phx-keydown and phx-keyup don't work in Firefox

### ISSUE THREAD

**Issue by denvaar** [phoenixframework/phoenix_live_view#546]
### Environment

* Elixir version (elixir -v): 1.9.1
* Phoenix version (mix deps): 1.4.10
* Phoenix LiveView version (mix deps): 0.4.0
* NodeJS version (node -v): 10.15.1
* NPM version (npm -v): 6.9.0
* Operating system: OSX

### Actual behavior

I'm not seeing handle_event being invoked when using `phx-keydown`/`phx-keyup`. The bug seems to only happen when using Firefox. I switched to Chrome and the events show up as expected. No error is shown server side nor client side. [Here is the code](https://github.com/denvaar/liveview_examples/blob/game-example/lib/demo_web/live/game_live.ex).

### Expected behavior

I expect `handle_event` to be called in response to `phx-keydown`.

**Comment by denvaar** [comment]
I'm sorry - this appears to work now. I must have missed something. I think adding phx-target="window" made the difference.

**Comment by snewcomer** [comment]
@denvaar Just an FYI, this is likely because the `document.activeElement` is the body and no elements ever receive focus...aka not one of the dots in your game when the keydown is called.  Perhaps there is some documentation improvements to further indicate this type of scenario.  I'll look back at this next week. Thank you for the issue!
