### ISSUE TITLE
updated() method of a form's hook gets called even if no update is performed in 0.8.0

### ISSUE THREAD

**Issue by sfusato** [phoenixframework/phoenix_live_view#658]
### Environment

* Elixir version (elixir -v): 1.9.1
* Phoenix version (mix deps): 1.4.9
* Phoenix LiveView version (mix deps): 0.8.0
* NodeJS version (node -v): 13.5.0
* NPM version (npm -v): 6.13.4
* Operating system: Manjaro Linux
* Browsers you attempted to reproduce this bug on (the more the merrier):  Firefox, Chrome
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Actual behavior
I've recently upgraded liveview from 0.7.1 to 0.8.0 in a project and noticed what seems to be a bug.

`updated()` method of a form's hook gets called even when there's no update made to any assigns.

### Expected behavior
I would expect `updated()` to be called only when "the element has been updated in the DOM by the server"

Demo project: https://github.com/sfusato/phoenix_live_view_example

1. Go to: http://localhost:4000/users/5/edit
2. Edit the `Username` field and watch the developer console log.

The form has phx_change: "validate" and phx_hook: "SavedForm". 

```
 def handle_event("validate", _value, socket) do
    IO.puts("handle_event => validate")
    IO.puts("SavedForm.updated() hook will get called in 0.8.0, but not in 0.7.1")

    {:noreply, socket}
  end
```

The websocket response is this:
```
["5","25","lv:phx-FfafeWAZ2YxFyxKD","phx_reply",{"response":{},"status":"ok"}]
```
Yet, `updated()` is still called.

Works as expected in 0.7.1. Update the version to 0.7.1 and switch the plugs in router.ex.

**Comment by feliperenan** [comment]
Hi, just to add a little bit of more information about this issue :wave:

I'm also experiencing this on the master branch. It seems that it started to happen after this change: https://github.com/phoenixframework/phoenix_live_view/commit/e96158f76cb5fc1b4e46953ab10f96a1b88ab9fd

If I use [the commit before](https://github.com/phoenixframework/phoenix_live_view/commit/29d494c078be64ffba82e2a93a18027daad13d6b) as reference I see the expected behaviour pointed by @sfusato. But I couldn't get it working just reverting that change back on top of the last changes (master branch) and I'm not sure why yet.

**Comment by chrismccord** [comment]
The form receives css loading classes on change, so the DOM element is indeed updated. This is expected behavior. Thanks!

**Comment by sfusato** [comment]
The form receives css loading classes even when there's no change to the form? In this case, a `phx-hook` on the form will fire `beforeUpdate` and `updated` every single time.

**Comment by chrismccord** [comment]
The form receives css loading classes when the child inputs of the form have changed
