### ISSUE TITLE
Edge case: phx-update

### ISSUE THREAD

**Issue by jamilabreu** [phoenixframework/phoenix_live_view#701]
Sharing a edge-case here:

([Animate.css](https://daneden.github.io/animate.css/)) uses css classes for animation, and every few seconds I'm using LiveView to replace this html:

```
     ~E"""
        <span id="<%= word %>" class="animated flipInX faster inline-block">
          <%= word %>
        </span>
      """
```

As of today I need to add an `id` to remount the entire element, because of how `phx-update=replace` works (the element/classes don't change, so the animation doesn't trigger).

Would an option to `phx-update=refresh` or similar be possible? It'd eliminate the need to add an otherwise unnecessary `id` attribute.

This might defeat the purpose of LiveView, but just throwing it out there 😅

**Comment by OvermindDL1** [comment]
Isn't that how CSS animations are supposed to work?  At least that's how I've relied on it.  The animations should only play when the CSS class changes.  Thus I'm not sure what `refresh` would do?  If you want an animation to play constantly then you can make a repeating animation in CSS, otherwise things like changing the ID would be perfect for recreating it?

**Comment by chrismccord** [comment]
As @OvermindDL1 said, this is expected behavior since it's actually a bug if we replaced a DOM node instead of updating it, since all the event listeners, etc, you have wired up would be wiped out. The id trick is the way to go if you truly want a new dom node, which allows the CSS animation will kick in because a new node is inserted in the DOM. I consider this a very reasonable tradeoff vs complexity in adding a new feature. Thanks!
