### ISSUE TITLE
debounce should trigger immediately on blur

### ISSUE THREAD

**Issue by chrismccord** [phoenixframework/phoenix_live_view#745]

**Comment by msaraiva** [comment]
Hi @chrismccord!

I think `phx-debounce` and `phx-throttle` falls in the exact same problem of `phx-target` as they also assume that all events of a DOM element are strongly related and consequently should share the same idiosyncrasies. As I tried to explain in this [comment](https://github.com/phoenixframework/phoenix_live_view/pull/669#issuecomment-593630346), they shouldn't. Going this path will lead to more and more tailor-made code trying to fill the gaps when implementing different components with different requirements. 

Instead of assuming anything about how debouncing should work for `keydown` and `blur` together because we have an "autocomplete text input" in mind, we should make the model flexible and extend it to accept setting those customizations individually, i.e, allowing the user to set a `phx-keydown-debounce` without interfering with other events like `blur` or `click`. This model (or any other similar alternative you come up with) is much more flexible and requires much less maintenance since we don't have to think about all possible use-cases that will appear in the future.

**Comment by josevalim** [comment]
I think those are separate discussions. The reason why we should invoke debounce/throttle on blur is because, once there is a blur, **there is a guarantee that the input will no longer change or get a keydown**. Therefore, waiting for the throttle/debounce period when you know something won't change makes the UI feel sluggish.

What you are saying would be true for a component that has both phx-keydown and phx-change. However, blur is a complete separate discussion.

**Comment by msaraiva** [comment]
@josevalim thanks for the clarification. I still think it's risky to assume the user will always want to immediately trigger the event on blur instead of, for instance, to cancel it. It sounds to me that having: 

  1. the ability to configure the events individually (as proposed)
  1. having a mechanism to let the user fire or cancel the delayed action (it could be on blur or on any other event)

would be much more flexible at the cost of being more verbose. However, I'm not sure if `#2` would be even possible.

**Related question**: is it possible today to fire the delayed event when the user hit, let's say `Enter`? It's quite common to do that in autocomplete inputs to allow the user to confirm immediately. So usually you should have `debounce` applied to any key except `Enter`.

**Comment by josevalim** [comment]
> the ability to configure the events individually (as proposed)

Unfortunately this won't be fixed by adding phx-blur-debounce. That's because:

1. Once you blur a debounced/throttled change event, you have three options: abort, wait or perform immediately. None of them would be captured by making phx-blur-debounce/throttle its own thing

2. phx-blur is generally speaking a completely separate event from phx-change/phx-keydown. If you have both phx-blur and phx-change, then I would expect two events to be emitted, in addition to the points listed in 1

So I really don't think we should be mixing these discussions. As I said, phx-blur-debounce may have its own merits, but it is completely orthogonal to a throttled/debounced change or keydown event.

Your suggestion 2 may actually work though, we could do something `phx-blur="phx-change:cancel"` but @chrismccord has been generally against having a meta-language and honestly that is not much better than "phx-change-on-blur=cancel".

Finally, even if your point is "we need to make all of this customizable", we still need to choose a proper default. And I think submitting the throttled/debounced change/keydown in blur is the better default.

> Related question: is it possible today to fire the delayed event when the user hit, let's say Enter? 

Pressing enter either blurs or submit the form, which should emit the submit event. I am not sure if it cancels any throtled or debounced event though.

**Comment by msaraiva** [comment]
@josevalim thanks again. I agree this could be a different discussion so I'll just leave a comment regarding _"against having a meta-language"_ since I'm not sure what would be considered a meta-language or not :)

I understand the concern but I think It's going to be hard to make events flexible enough without implementing some kind of modifier API that allows customizing events individually. Almost every modern UI framework incorporated the idea. `Vue.js`, `Svelte`, `Alpine.js`, they all implemented modifiers for events. For instance, in Alpine.js you can do:

```html
<input x-on:input.debounce="doSomething()">
``` 

you can even set the wait time:

```html
<input x-on:input.debounce.200="doSomething()">
``` 

I'm not sure Vue and Svelte have already a specific modifier for `debounce`. I believe they don't, but since the event handlers run on the browser, they provide other built-in alternatives. For Phoenix LV where the event handlers run on the server, this is even more critical since the user won't have an easy way to achieve the same goal. Maybe using JS hooks? I'm not sure yet how complicated that would be.

So in case you want to discuss alternatives in the future, please let me know :)

Here are some links for reference on modifiers:

  * https://github.com/alpinejs/alpine#x-on
  * https://vuejs.org/v2/guide/events.html#Event-Modifiers
  * https://svelte.dev/docs#on_element_event

Cheers.

**Comment by silva96** [comment]
this could be related with my issue? #927
