### ISSUE TITLE
Docs: Phoenix.LiveComponent id: also DOM ID or not?

### ISSUE THREAD

**Issue by Qqwy** [phoenixframework/phoenix_live_view#747]
On the documentation page of [Phoenix.LiveComponent](https://hexdocs.pm/phoenix_live_view/Phoenix.LiveComponent.html)

the [Targeting Component Events](https://hexdocs.pm/phoenix_live_view/Phoenix.LiveComponent.html#module-targeting-component-events) section states

> For example, if the UserComponent above is started with the :id of 13, it will have the DOM ID of user-13. Using a query selector, we can sent an event to it with:

However, in [Stateful Components Lifecycle](https://hexdocs.pm/phoenix_live_view/Phoenix.LiveComponent.html#module-stateful-components-life-cycle), preceding it, it is stated:

> Also note the given :id is not necessarily used as the DOM ID. If you want to set a DOM ID, it is your responsibility to set it when rendering:

Unless I am missing something, only one of these can be correct. Which is it?

**Comment by josevalim** [comment]
They are both correct because the previous component explicitly converts the component ID  to DOM ID:

>     <div id="user-<%= @id %>" class="user"><%= @user.name %></div>

:)

**Comment by christopherdbull** [comment]
Just to jump on this: I have a parent LiveComponent which has an `id:` set and this becomes the DOM id, however, in one of this LiveComponents child components, the `id:` is set again, however it doesn't become the DOM id, and thus can't be used for `phx-target` etc. Is this expected behaviour? It's quite confusing.

**Comment by okariFrankline** [comment]
@christopherdbull when using live_component/3 call, the the LiveComponent module name and an id are explicitly required in order to identify the live component. However, this is is not used as the DOM ID. It's up to you to declare the DOM ID for the root html tag for your component. As such, for your child components, you should explicitly give them DOM ids, so that you will be able to target them using phx-target. 
The important thing to remember is that the :id passed to live_component/3 is not automatically used as the DOM id for that component. In fact you can set the DOM id to be something different entirely.

**Comment by christopherdbull** [comment]
@okariFrankline thank you for clearing that up! I think the docs could be made more explicit on this point.
