### ISSUE TITLE
CSS not applied to the page using `live/4` of Phoenix.LiveView.Router

### ISSUE THREAD

**Issue by karloescota** [phoenixframework/phoenix_live_view#750]
### Environment

* Elixir version (elixir -v): 1.9.2
* Phoenix version (mix deps): 1.4.16
* Phoenix LiveView version (mix deps): 0.10.0
* NodeJS version (node -v): v12.4.0
* NPM version (npm -v): 6.9.0
* Operating system: MacOS 10.14
* Browsers you attempted to reproduce this bug on (the more the merrier): Google Chrome
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Actual behavior
CSS is not working when using `live/4` of Phoenix.LiveView.Router.

This is the side-by-side comparison, left using `live_render/3`, right using `live/4`
<img width="1114" alt="Screenshot 2020-04-01 at 6 02 27 PM" src="https://user-images.githubusercontent.com/7534948/78126836-ba934300-7445-11ea-83a4-c5ca85f5eddf.png">

router.ex
```
...
scope "/", LoyaltyWeb do
  pipe_through :browser

  get "/", PageController, :index
  live "/search", SearchLive
end
```

page/index.html.exx
```
<%= live_render(@conn, AppWeb.SearchLive) %>
```

search_live.ex
```
def render(assigns) do
  ~L"""
  <div>
    <table>
      <tr>
        <th>Attribute</th>
        <th>Column A</th>
        <th>Column B</th>
      </tr>

      <tr>
        <td>Email</td>
        <td>Value</td>
        <td>Value</td>
      </tr>

      <tr>
        <td>First Name</td>
        <td><%= @first_name %></td>
        <td>Value</td>
      </tr>

      <tr>
        <td>Last Name</td>
        <td>Value</td>
        <td>Value</td>
      </tr>
    </table>
  </div>
  """
end

def mount(_params, _session, socket) do
  {:ok, assign(socket, :first_name, "First")}
end
```

app.css
```
@import "./phoenix.css";
@import "../../deps/phoenix_live_view/assets/css/live_view.css";

body {
  background-color: orange;
}
```

### Expected behavior
CSS should be applied on right side screenshot - orange body.

Not sure, maybe I missed out something. I just followed the [Installation Guide](https://hexdocs.pm/phoenix_live_view/installation.html).

Thanks!

**Comment by sfusato** [comment]
You missed a step that will appear in the Installation Guide once a new release will be pushed.

In the meantime, check the [layouts section in master](https://github.com/phoenixframework/phoenix_live_view/blob/master/guides/introduction/installation.md#layouts).

**Comment by josevalim** [comment]
Thanks @sfusato!

**Comment by 1player** [comment]
I'm confused as well, I've followed the master docs and I still can't make it work: the main confusion stems from the fact that https://github.com/phoenixframework/phoenix_live_view/blob/master/guides/introduction/installation.md#layouts says to use a separate pipeline for live controllers and `put_root_layout`, whereas https://hexdocs.pm/phoenix_live_view/Phoenix.LiveView.html#module-live-layouts talks about root layout used for both the normal non-LiveView path (app.html) and LiveView (live.html).

Which is the correct way?

My non-LiveView app has a default and naked layout, currently set with `put_layout`: the render flow is easy:

Layout (by default app.html.eex) -> Calls `render @view_module, etc.` -> Inner template

Refactoring everything to use `put_root_layout` for regular and Live templates sometimes causes it to go into an infinite loop, which might be a user error, also because it introduces a new rendering level:

Root layout (set by put_root_layout) -> `<%= @inner_content %>` -> ??? -> Layout (by default app.html.eex, I guess live.html.leex on LiveView) -> ??? -> Inner template

What exactly is the code path? When should root layout used `@inner_content` instead of `render @view_module, ...`? The Phoenix Live View example repo uses both:

* https://github.com/chrismccord/phoenix_live_view_example/blob/master/lib/demo_web/templates/layout/root.html.eex
* https://github.com/chrismccord/phoenix_live_view_example/blob/master/lib/demo_web/templates/layout/bare.html.eex
