### ISSUE TITLE
phx-hook not working on elements that have class

### ISSUE THREAD

**Issue by D4no0** [phoenixframework/phoenix_live_view#756]
When adding hook to an element that has class tag, the hook is not getting called. This bug seems to happen on all HTML elements.

Wroking example: https://github.com/D4no0/phoenix_live_view_example/tree/hook_bug

**Comment by chrismccord** [comment]
`updated` is only triggered if the element changes, which you are likely seeing since we set classes on the `phx-` bindings while waiting on a server response. You will notice that all the elements trigger `mounted` properly. If you add something via an assign to the other hook elements, you'll indeed see the updated hook trigger. Thanks!

**Comment by D4no0** [comment]
Then can you please tell me why updated is called on an element with `phx-click` that is hooked, however when you add class to it, it doesn't happen? I seem to lack something here.

I also turned on debugging option on sockets, and the update event is called in both cases, however in the case when the button has class the object list is empty.
