### ISSUE TITLE
Dangling LiveView processes in tests

### ISSUE THREAD

**Issue by wojtekmach** [phoenixframework/phoenix_live_view#887]
Currently, when we do `live(...)` in tests, the resulting LiveView process is linked to LiveView supervisor which means it can outlive the test process that started it. This is especially problematic when the LiveView is using other processes e.g. it still tries to use a DB connection even though that connection is already dead because the test process exited.

To solve this scenario we will do a few things:

* [x] (https://github.com/elixir-ecto/ecto_sql/pull/229) Add `Ecto.Adapters.SQL.Sandbox.start_owner!/2` and `stop_owner/1`. With this, the owner of the connection will be a separate process (from the test process) that we will terminate it in `on_exit/1` 

* [x] (https://github.com/phoenixframework/phoenix/pull/3856) Add `start_owner!/2` and `stop_owner/1` to `mix phx.new` generator

* [x] (https://github.com/elixir-lang/elixir/pull/10035) Add `ExUnit.fetch_test_supervisor/0`

* [x] (#887) Start LiveView processes in tests under test supervisor. This will "backport" the `ExUnit.fetch_test_supervisor!/0` function and use it. With this, in tests we will start LiveView processes under the test supervisor and ExUnit will guarante these will be terminated before `on_exit` callbacks are run (so LiveView processes will be terminated before DB connection is terminated)

**Comment by mackshkatz** [comment]
@wojtekmach to make sure I understand the reason this solution works, is it because now:
 - the process which owns the connection is no longer the test process
 - the owner process is explicitly stopped when the test exits, so thanks to OTP/supervisor trees any other process that may have been started during the test run, is properly killed
 - which means, even if there is a client process still attempting to use the db connection, it won't outlive the test process (which previous was not linked in any way to any child processes, so there was no way to kill them to not leave them dangling)

Does this sound right? Thanks for the fix!

**Comment by wojtekmach** [comment]
@mackshkatz yup, pretty much! 

> any other process that may have been started during the test run

> even if there is a client process still attempting to use the db connection

it all depends how these processes are started: if they're linked to the test process or the LiveView process, they will be now properly killed. Otherwise, e.g. these processes are not linked to anything, they may still outlive the the connection process.

**Comment by mackshkatz** [comment]
@wojtekmach awesome, thanks! That makes sense, I actually realized that after I typed that up, because we were dealing with a process that was started (but not linked) outside of the control of the test, so we were still getting "owner exited"-esque errors. Thanks for the response!
