### ISSUE TITLE
Form field loses focus when image conditionally appears

### ISSUE THREAD

**Issue by henrik** [phoenixframework/phoenix_live_view#909]
### Environment

* Elixir version (elixir -v): 1.10.3
* Phoenix version (mix deps): 1.5.1
* Phoenix LiveView version (mix deps): 0.12.1
* NodeJS version (node -v): Assuming it's unrelated
* NPM version (npm -v): Assuming it's unrelated
* Operating system: macOS
* Browsers you attempted to reproduce this bug on (the more the merrier): Chrome, Safari, Firefox (all have this issue)
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no:  Assuming it's unrelated

### Actual behavior

![bug](https://user-images.githubusercontent.com/216/82591618-8a3f6980-9b97-11ea-8497-888a8df65548.gif)

As soon as I enter the first character in the input field, triggering the "show the image" condition, the form field loses focus.

(If I click to re-focus it and keep typing, the field keeps focus. It's just when the image appears that focus is lost.)

### Expected behavior

To be able to keep typing as the image appears.

### Example code

```
def mount(_params, _session, socket) do
  {:ok, assign(socket, text: "")}
end

def render(assigns) do
  ~L"""
  <%= if @text != "" do %>
    <img src="https://ludu-assets.s3.amazonaws.com/course-icons/26/I5mCOcqaE6RHdfD3Q1Ta" alt="" />
  <% end %>
  <form phx-change="bug_out">
    <input type="text" name="text" value="<%= @text %>"/>
  </form>
  """
end

@impl true
def handle_event("bug_out", %{"text" => text}, socket) do
  {:noreply, assign(socket, text: text)}
end
```

**Comment by chrismccord** [comment]
Can you provide the form an ID and report back? What is likely happening is the image appears as a prior sibling to your form, and we remove and replace the form as a new child because its location in the siblings index changed, and it lacked an ID. Thanks!

**Comment by henrik** [comment]
@chrismccord Hah, you're right. That fixed it. Thank you! That was quick :D

**Comment by chrismccord** [comment]
We've talked about requiring forms to have an ID for a long time, which would have fixed this (provided you saw the console warning), but in general there are cases where when we patch the DOM and the siblings change, a sibling without an ID will be replaced in the DOM rather than moved, and in those cases having an ID on the sibling matins the DOM node. Perhaps a section of the docs would be helpful?

**Comment by henrik** [comment]
Yeah, I think something in the docs would likely have helped.

Happy to make a PR. Does something like this capture it accurately?

> We strongly recommend putting a unique HTML "id" attribute on forms. When DOM siblings change, elements without an ID will be replaced rather than moved, which can cause issues such as form fields losing focus.

**Comment by josevalim** [comment]
> Happy to make a PR. Does something like this capture it accurately?

It is gold. :+1:

**Comment by hubertlepicki** [comment]
Very interesting, I stumbled upon this autofocus of input next to a form issue just now too. It's been a custom form, not generated through LiveView/Phoenix helpers, and indeed adding an ID to the form solved it.

Just letting everyone know that the fix still works.

**Comment by hubertlepicki** [comment]
So in my case I stumbled upon this and indeed adding a *stable* ID fixed the problem.

The issue I had is that I was using a form with ID that changed between the initial, server-side render, and the sequential render when the WebSocket client connected. My form was getting a *different* ID, which triggered the same bug described above: the first input of the form that I explicitly labeled as having autofocus was losing it.

The fix was to make sure the ID was on the form and it was not changed between the original and the following renders.
