### ISSUE TITLE
Ability to await in beforeDestroy callback

### ISSUE THREAD

**Issue by syfgkjasdkn** [phoenixframework/phoenix_live_view#915]
### Environment

* Elixir version (elixir -v): 1.10
* Phoenix version (mix deps): 1.5
* Phoenix LiveView version (mix deps): 0.13
* NodeJS version (node -v): v14.2.0
* NPM version (npm -v): 6.14.4
* Operating system: macos
* Browsers you attempted to reproduce this bug on (the more the merrier): safari, chrome, firefox
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: yes

### Actual behavior

Right now the `beforeDestroy` callback needs to be synchronous which prevents us from implementing leave transition for destroyed elements. 

### Expected behavior

If it was possible to have the callbacks be awaited, then we'd be able to fade elements out like

```js
async beforeDestroy() {
  this.el.classList.add("opacity-0");
  await transitionEnd(this.el);
}
```

**Comment by josevalim** [comment]
This is intentional. The issue is: what happens if you are transitioning your element our and then another diff comes on the page? The destroyed element would be removed in the middle of its transition. For this reason, transitions require a bit more thought and it is probably best it is a separate mechanism rather than `beforeDestroy`.

**Comment by syfgkjasdkn** [comment]
@josevalim Thank you for the explanation!

>  [...] it is probably best it is a separate mechanism rather than beforeDestroy.

What that mechanism could be?

**Comment by josevalim** [comment]
@syfgkjasdkn we don't know yet, unfortunately. We have talked about phx-remove, but we haven't landed anything yet.
